### ISSUE TITLE
[cosmwasm-stargate] Allow for optional Authorization details when connecting

### ISSUE THREAD

**Issue by mikedotexe** [cosmos/cosmjs#1007]
I saw this comment about Figment's API keys and thought it would be good to create an issue.
https://github.com/cosmos/awesome/issues/17#issuecomment-1019447433

I'm not super familiar with the Cosmos tooling, but I have been successfully talking to a testnet RPC by basically doing:

```js
const client = await CosmWasmClient.connect(RPC_ENDPOINT)
let balance = await client.queryContractSmart('junoAbc123…', {
    balance: { address: encodedAccount },
  })
console.log(`Balance: ${balance.balance}`);
```

It looks like in the `cosmwasm-stargate` package, the `connect` function only takes an endpoint and no more details for authorization.

https://github.com/cosmos/cosmjs/blob/40a1121b8ee358a5fd2a875dcc56714b77ac8e29/packages/cosmwasm-stargate/src/cosmwasmclient.ts#L93-L96

When you look at Figment's system it'll give you an API key such that you can access using an Authorization header, like:

```sh
curl https://cosmoshub-4--rpc--full.datahub.figment.io/status -H Authorization: abc123…
```

Might be a consideration to have this `connect` call take an object instead, so it might have less problems with backwards compatibility later.

For instance, it could be:

```js
 public static async connect({ endpoint: string, authorization: string}): …
```

Or maybe there's a way to use the abstraction in cosmjs and add this type of authorization, but I wasn't able to find it.

**Comment by webmaster128** [comment]
Good point. I wan't aware such headers were used in the Comsos space.

This is the same problem in every CosmJS package that connects to a node. If we start working on this, I would not add autorization support but HTTP headers in general. Next user will need cookies or something custom here.

An alternative solution would be https://github.com/cosmos/cosmjs/pull/981 where you create a wrapper RPC object that injects the headers. However, I'm not exactly sure if we should support #981 right now.

**Comment by daoauth** [comment]
Create and use [`httpclient`](https://github.com/cosmos/cosmjs/blob/main/packages/tendermint-rpc/src/rpcclients/httpclient.ts) externally. 

for example

```javascript
const authProvider = new HttpClient(endpoint, authorization);
const client = await StargateClient.connect(authProvider);
```

**Comment by daoauth** [comment]
@webmaster128 What actions do I need to add to apply the wrapper RPC? Are there any necessary process?

**Comment by webmaster128** [comment]
I think this is pretty clear. It's just a matter of API design. Do we want the functionality and do we want it this way. While it might look simple for this use case, there are other things to consider, like: what are the implications for websocket users? Will websockets even be relevant? What about grpc enpoints to connect to? What's a good name for interface of we make it public?

The change would be relatively easily to implement it it was just the Tendermint 0.34 client. But it has to propagate though all the stack to be usable in the higher level clients.

**Comment by daoauth** [comment]
This is an interface inspired by [Ethereum Provider JavaScript API(eip-1193)](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md). As you said, it is not an interface that can be used in all cases. However, there are many advantages to setting up and using stargate client, and it will be a very necessary interface for developers and users in many cosmos webs.

**Comment by webmaster128** [comment]
@mikedotexe can you check if https://github.com/cosmos/cosmjs/pull/1112 serves your needs?

**Comment by webmaster128** [comment]
See https://github.com/cosmos/cosmjs/blob/ae06012/packages/cli/examples/figment.ts for how to use a Figma endpoint (or other endpoint that requires custom HTTP headers) in the next release (0.28.4+). Please note that Firma's CORS policy makes it impossible to connect to the data hub from a browser. But it works server-side in node.js applications.
