### ISSUE TITLE
Update ics23 package

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#1032]
Once we have a new version, we can update it here to remove a lot of old hashing libs. See https://github.com/confio/ics23/issues/75

**Comment by ethanfrey** [comment]
cosmjs 0.6.8 has been released. It should be drop in compatible with better deps.

I should release 0.7.0 next week with support for SMT non-existence proofs (eg future sdk)

**Comment by webmaster128** [comment]
Great thanks. In #1050 we already see how the runtime dependency js-sha512 is removed. With #966 many more old school hashing implementations will disappear as well.
