### ISSUE TITLE
Will cosmos officially release a version of Java's signature sdk?

### ISSUE THREAD

**Issue by jc0803kevin** [cosmos/cosmjs#1035]
Will cosmos officially release a version of Java's signature sdk?

**Comment by webmaster128** [comment]
There is no such think as official in Cosmos. Many different organizations work on many different components. CosmJS is one of those components. It's devewloped by a company called Confio funded primaliry through the Interchain foundation. Many people like and support it but does not mean 1. it is still maintained tomorrow and 2. no alternative is developed by a different player.

That being said, I am not aware of any popular Java client SDK. There might be one, but I'm just a small fish doing this JavaScript thing here and don't know.

Hope you find a solution! Closing as out of scope for CosmJS.
