### ISSUE TITLE
Can't find TextDecoder

### ISSUE THREAD

**Issue by madhanrajR** [cosmos/cosmjs#1041]
![Screenshot from 2022-02-14 16-54-58](https://user-images.githubusercontent.com/20437319/153855985-d7a8aca2-3b41-4e68-8021-bd4cb450e95c.png)

**Comment by webmaster128** [comment]
What JS environment are you running this in? A global TextDecoder should be standard these days as far as I can tell.

**Comment by webmaster128** [comment]
Could you solve the problem? Could you share your solution?
