### ISSUE TITLE
How to convert cosmos public key to ethereum address?

### ISSUE THREAD

**Issue by chismo950** [cosmos/cosmjs#1044]
use @cosmjs/crypto?

**Comment by nooomski** [comment]
What exactly do you mean @chismo950 ? Cosmos public keys aren't related to Ethereum addresses.

**Comment by webmaster128** [comment]
⚠️ Warning: With great power comes great responsibility

This is very well possible. It is probably big hackery and should not be done, but it can be done.

Like Ethereum, Cosmos SDK uses secp256k1 keypairs. So you can (not should) use an Ethereum keypair for a Cosmos chain and vice versa. The biggest difference is that Ethereum uses uncompressed secp256k1 pubkeys and Cosmos uses compressed secp256k1 pubkeys.

The steps are as follows:

1. Uncompress the secp256k1 pubkey (#1047)
2. Create a Keccak256 hash of the 64 bytes after the leaxing 0x04 byte and cut the last 20 bytes ([as done here](https://github.com/iov-one/iov-core/blob/db5c65323574b595292513b7f51e12dddd87db33/packages/iov-ethereum/src/address.ts#L64-L65))
3. Hex encode the 20 byte result of 2. and prefix with `0x`
4. (optional) Implement the upper/lower case checksum from EIP-55 [as implemented here](https://github.com/iov-one/iov-core/blob/db5c65323574b595292513b7f51e12dddd87db33/packages/iov-ethereum/src/address.ts#L29-L58).

Point 4 is out of scope for CosmJS but the rest can be done with the general purpose tooling you find here.

**Comment by chismo950** [comment]
> ⚠️ Warning: With great power comes great responsibility
> 
> This is very well possible. It is probably big hackery and should not be done, but it can be done.
> 
> Like Ethereum, Cosmos SDK uses secp256k1 keypairs. So you can (not should) use an Ethereum keypair for a Cosmos chain and vice versa. The biggest difference is that Ethereum uses uncompressed secp256k1 pubkeys and Cosmos uses compressed secp256k1 pubkeys.
> 
> The steps are as follows:
> 
> 1. Uncompress the secp256k1 pubkey ([Add Secp256k1.uncompressPubkey #1047](https://github.com/cosmos/cosmjs/pull/1047))
> 2. Create a Keccak256 hash of the 64 bytes after the leaxing 0x04 byte and cut the last 20 bytes ([as done here](https://github.com/iov-one/iov-core/blob/db5c65323574b595292513b7f51e12dddd87db33/packages/iov-ethereum/src/address.ts#L64-L65))
> 3. Hex encode the 20 byte result of 2. and prefix with `0x`
> 4. (optional) Implement the upper/lower case checksum from EIP-55 [as implemented here](https://github.com/iov-one/iov-core/blob/db5c65323574b595292513b7f51e12dddd87db33/packages/iov-ethereum/src/address.ts#L29-L58).
> 
> Point 4 is out of scope for CosmJS but the rest can be done with the general purpose tooling you find here.

Thank you very much, I did it!

**Comment by tungle-notional** [comment]
Hi. Is there a way to convert from eth address to cosmos chain address in Go?

**Comment by baoskee** [comment]
> ⚠️ Warning: With great power comes great responsibility
> 
> This is very well possible. It is probably big hackery and should not be done, but it can be done.
> 
> Like Ethereum, Cosmos SDK uses secp256k1 keypairs. So you can (not should) use an Ethereum keypair for a Cosmos chain and vice versa. The biggest difference is that Ethereum uses uncompressed secp256k1 pubkeys and Cosmos uses compressed secp256k1 pubkeys.
> 
> The steps are as follows:
> 
> 1. Uncompress the secp256k1 pubkey ([Add Secp256k1.uncompressPubkey #1047](https://github.com/cosmos/cosmjs/pull/1047))
> 2. Create a Keccak256 hash of the 64 bytes after the leaxing 0x04 byte and cut the last 20 bytes ([as done here](https://github.com/iov-one/iov-core/blob/db5c65323574b595292513b7f51e12dddd87db33/packages/iov-ethereum/src/address.ts#L64-L65))
> 3. Hex encode the 20 byte result of 2. and prefix with `0x`
> 4. (optional) Implement the upper/lower case checksum from EIP-55 [as implemented here](https://github.com/iov-one/iov-core/blob/db5c65323574b595292513b7f51e12dddd87db33/packages/iov-ethereum/src/address.ts#L29-L58).
> 
> Point 4 is out of scope for CosmJS but the rest can be done with the general purpose tooling you find here.

⚠️ THIS IS NOT TRUE!

Ethereum uses different HD path (`m/44'/60'/0'/0/0`) than Cosmos (`m/44'/118'/0'/0/0`). So the secp256k1 Cosmos pubkey you find in transactions will NOT CONVERT. 

Please do not use this in production. ❌

**Comment by webmaster128** [comment]
> Ethereum uses different HD path (`m/44'/60'/0'/0/0`) than Cosmos (`m/44'/118'/0'/0/0`)

The chain itself does not care which derivation path you use. In fact it can't even know where the derived keypair is coming from. The problem you will have though is compatibility with other wallets.

**Comment by baoskee** [comment]
> You can derive addresses the "Ethereum way" and the "Cosmos way" because in both cases the addresses are just derived from the pubkey, which comes from the private key, which comes from the HD path of the mnemonic.

For simplicity reasons and avoiding confusion, TAILWIND will just return the Ethereum path public key for users. I think it's pretty stress-inducing when you import the same keys and the addresses don't match. 

Although for Dapps (as opposed to wallets), getting the Ethereum key from Cosmos key would presumably be easier. 

Thanks @webmaster128 @codebycarson for the clarification. One more question: "The chain does not care about HD Path." Is this true for Ethereum as well or is it just Cosmos SDK chains?

**Comment by webmaster128** [comment]
It's the same for both Ethereum and Cosmos. You don't need to use HD derivation at all and can just have a raw private and public secp256k1 key.

```
mnemonic + HD path  ----->  private key  ----->  public key  ------>  address
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
client-side only (invisible to the chain)
```

>  then I assume that would not be the same for two different HD paths from the same mnemonic

Two paths just give you two different private keys, two different public keys, two different addresses. So completely independent accounts from the perspective of the chain.
