### ISSUE TITLE
Add waiting time to timeout error message

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#1066]
![image](https://user-images.githubusercontent.com/2603011/156322118-8a2e0c80-5d32-48cf-89f0-cff749e9a9a3.png)

In an error case like this it would be interesting to understand how long the client waited for the inclusion of a tx. That allows for interpretation how realistic it is that the tx will make it into a block. E.g. if a chain has 3 second block times and the error says "after 60 seconds" you know that 20 blocks have been created without your transaction. If it says "after 10 seconds" and you have a 6 second block time, that can mean you did not make it in the first block but it is still likely the tx will show up.

**Comment by wenmoonsir** [comment]
Can we increase timeout somehow to wait for this tnx? not sure where to do it

**Comment by abhimonu7555-cyber** [comment]
Free fire id
