### ISSUE TITLE
Add support for vesting messages (MsgCreateVestingAccount)

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#1074]
There seems to be one message only: https://github.com/cosmos/cosmos-sdk/blob/v0.45.1/x/auth/vesting/types/msgs.go

This came up in https://github.com/cosmos/cosmjs/pull/1062 but the author decided to just be selfish and fork away instead of creating a trivial PR to add this type to the codebase.

**Comment by dreamcodez** [comment]
@webmaster128 this 'selfish' author wanted to test that his approach worked before sending a PR upstream. Also, I have no idea how to get the checked in node_modules build chain working. Please note the number of files changed. 

I'm happy to submit these changes upstream when I understand the codebase better.

**Comment by webmaster128** [comment]
Hey @dreamcodez, thank you! For CosmJS maintenance we use yarn 3 for package management. This makes the setup a bit tricks. See https://github.com/cosmos/cosmjs/blob/main/HACKING.md for a starting guide how to work in CosmJS. Let me know if something is missing or unclear.

**Comment by webmaster128** [comment]
@dreamcodez do you want to give this ticket a try? In https://github.com/cosmos/cosmos-multisig-ui/pull/54 you see how the message type is used and the Amino JSON converters are implemented when this is done on the user's side. But it would be great to get it in here to be easily available to every user.

**Comment by webmaster128** [comment]
In https://github.com/cosmos/cosmjs/pull/1114 we have the message type working with sign mode direct. Unfortunately Amino JSON signing is causing trouble. Looking at https://discord.com/channels/@me/892065058132205629/961632553415098448 it seems like the message type was not properly registered in Cosmos SDK 0.44/0.45. However, people report that signing with the Go CLI client and Ledger works, which indicates the same bug we found for authz messages in https://medium.com/p/8754a0dc2a88.

Is there any value for users to get the direct sign mode merged without Amino JSON support?

**Comment by webmaster128** [comment]
See https://github.com/cosmos/cosmjs/issues/1115 for the follow-up ticket for Amino JSON support
