### ISSUE TITLE
Breaking change to `assertIsBroadcastTxSuccess` was not listed in 0.27 changelog

### ISSUE THREAD

**Issue by williamchong** [cosmos/cosmjs#1076]
the breaking change commit which renamed `assertIsBroadcastTxSuccess` in `stargateclient`:
https://github.com/cosmos/cosmjs/commit/5baf9781def1124616710f9225baa27d97f5129c

`assertIsBroadcastTxSuccess` is actually used in many of the stargate + cosmjs example, say
https://gist.github.com/webmaster128/8444d42a7eceeda2544c8a59fbd7e1d9#send-your-first-stargate-transaction-from-javascript

It would be nice to list this renaming of `assertIsBroadcastTxSuccess` to `assertIsDeliverTxSuccess` in change log to save people's troubleshooting time

**Comment by msteiner96** [comment]
The change seems to be in 0.27.0's changelog:

https://github.com/cosmos/cosmjs/blob/e098e763ddc19800ee9408f1160949929af1da1b/CHANGELOG.md?plain=1#L40-L41

**Comment by williamchong** [comment]
Would be nice if we mention that `assertIsBroadcastTxSuccess` was `replaced`, instead of using the word `Add` which does not hint any breaking change

**Comment by webmaster128** [comment]
You are right. What is missing is the CHANGELOG entry for this PR https://github.com/cosmos/cosmjs/pull/946, which came before the one listed in the CHANGELOG.

Thanks
