### ISSUE TITLE
DirectSecp256k1HdWallet.fromMnemonic secret network is diff from keplr

### ISSUE THREAD

**Issue by dwfe2** [cosmos/cosmjs#1100]

**Comment by webmaster128** [comment]
Secret network uses a different path that the Cosmos Hub. See https://github.com/chainapsis/keplr-wallet/blob/71b77e1d3fa0a92c4823097e439611a4cdda2754/packages/extension/src/config.ts#L223  and https://github.com/satoshilabs/slips/blob/master/slip-0044.md.

You can try something like this:

```ts
const path = [
    Slip10RawIndex.hardened(44),
    Slip10RawIndex.hardened(529),
    Slip10RawIndex.hardened(0),
    Slip10RawIndex.normal(0),
    Slip10RawIndex.normal(0),
  ];

ops.hdPaths = [path];
```

**Comment by dwfe2** [comment]
secret is 529
