### ISSUE TITLE
Usage of payer field for a transaction

### ISSUE THREAD

**Issue by xpt1x** [cosmos/cosmjs#1118]
Is it possible to use a different fee payer for a transaction ?

Suppose userA wants to send some funds to userB, can we involve userC to pay for this transaction ?
So that userA and userC signs the transaction and transaction proceed
Ref: https://docs.cosmos.network/v0.42/core/proto-docs.html#fee

**Comment by webmaster128** [comment]
Not yet. This is tracked as _Feegrant support (Cosmos SDK 0.43)_ in #1105.

I once saw a CosmJS fork implementing that but I never heard from the authors again and do't recall where/who that was.

**Comment by xpt1x** [comment]
Thanks for quick reply, will track
