### ISSUE TITLE
SigningStargateClient.connectWithSigner endpoint Error

### ISSUE THREAD

**Issue by zwht** [cosmos/cosmjs#1125]
`const network = {
  url: 'http://localhost:8080/rest',
  headers: {
    'Content-Type': 'application/json'
  }
}
const chainId = 'osmosis-1'
const offlineSigner = window.keplr.getOfflineSignerOnlyAmino(chainId);
const client = await SigningStargateClient.connectWithSigner(
  network,
  offlineSigner,
);`

Error：
`"TypeError: url.startsWith is not a function"
 at Function.connectWithSigner (signingstargateclient.js?172a:66:1)
`

Version 0.28.3 source code：
`public static async connectWithSigner(
    endpoint: string | HttpEndpoint,
    signer: OfflineSigner,
    options: SigningStargateClientOptions = {},
  ): Promise<SigningStargateClient> {
    const tmClient = await Tendermint34Client.connect(endpoint);
    return new SigningStargateClient(tmClient, signer, options);
  }`
  
 builded code signingstargateclient.d.ts：
 `static connectWithSigner(endpoint: string, signer: OfflineSigner, options?: SigningStargateClientOptions): Promise<SigningStargateClient>;`
 
 Why is there no HttpEndpoint？

**Comment by msteiner96** [comment]
This change is unreleased. If you need it, you should consider to build it by yourself instead of waiting for a release. The 0.28.3 version of this code is:

```ts
  public static async connectWithSigner(
    endpoint: string,
    signer: OfflineSigner,
    options: SigningStargateClientOptions = {},
  ): Promise<SigningStargateClient> {
    const tmClient = await Tendermint34Client.connect(endpoint);
    return new SigningStargateClient(tmClient, signer, options);
  }
```
(*https://github.com/cosmos/cosmjs/blob/v0.28.3/packages/stargate/src/signingstargateclient.ts*)

Got commited yesterday: https://github.com/cosmos/cosmjs/commit/7d62e8fc0d1c79e2ff5268d77584153256d4f769
Also in changelog "unreleased": https://github.com/cosmos/cosmjs/blob/main/CHANGELOG.md

**Comment by zwht** [comment]
If I use it like this, I get a cross domain error

`const network = 'https://lcd-osmosis.keplr.app';
const chainId = 'osmosis-1'

const offlineSigner = window.keplr.getOfflineSignerOnlyAmino(this.chainId);
const client = await SigningStargateClient.connectWithSigner(
  network,
  offlineSigner,
);
`
Access to fetch at 'https://lcd-osmosis.keplr.app/' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by zwht** [comment]
If I set the proxy, an error will be reported：
`
 proxy: {
      // 配置跨域
      '/rest': {
        target: 'https://lcd-cosmoshub.keplr.app',//后端接口地址
        ws: true,
        changOrigin: true,
        pathRewrite: {
          '^/rest': ''
        }
      }
    }
`
asyncToGenerator.js?1da1:6 Uncaught (in promise) Error: Bad status on response: 404

**Comment by zwht** [comment]
> This change is unreleased. If you need it, you should consider to build it by yourself instead of waiting for a release. The 0.28.3 version of this code is:
> 
> ```ts
>   public static async connectWithSigner(
>     endpoint: string,
>     signer: OfflineSigner,
>     options: SigningStargateClientOptions = {},
>   ): Promise<SigningStargateClient> {
>     const tmClient = await Tendermint34Client.connect(endpoint);
>     return new SigningStargateClient(tmClient, signer, options);
>   }
> ```
> 
> (_https://github.com/cosmos/cosmjs/blob/v0.28.3/packages/stargate/src/signingstargateclient.ts_)
> 
> Got commited yesterday: [7d62e8f](https://github.com/cosmos/cosmjs/commit/7d62e8fc0d1c79e2ff5268d77584153256d4f769) Also in changelog "unreleased": https://github.com/cosmos/cosmjs/blob/main/CHANGELOG.md

build error：https://github.com/cosmos/cosmjs/issues/1117

**Comment by msteiner96** [comment]
Yes I understand the problem too, that's why you can also use the change from https://github.com/cosmos/cosmjs/issues/1117 once the next release is released.

Regarding your build issues - can you list ALL the steps you take?

**Comment by zwht** [comment]
npm run build

➤ YN0000: [@cosmjs/utils]:     at Function.moduleExports.runMain (/Users/weizhao/zw/projects/bigData/cosmos/cosmjs/.pnp.cjs:23600:31)
➤ YN0000: [@cosmjs/utils]:     at internal/main/run_main_module.js:17:47
➤ YN0000: [@cosmjs/utils]: Process exited (exit code 1), completed in 4s 255ms
➤ YN0000: The command failed for workspaces that are depended upon by other workspaces; can't satisfy the dependency graph
➤ YN0000: Failed with errors in 16s 636ms`
`

**Comment by zwht** [comment]
> 是的，我也理解这个问题，这就是为什么你也可以在下一个版本发布后使用[7d62e8f的更改。](https://github.com/cosmos/cosmjs/commit/7d62e8fc0d1c79e2ff5268d77584153256d4f769)
> 
> 关于您的问题 - 您可以提出您的所有步骤吗？

When will the version be released?

**Comment by zwht** [comment]
> Yes I understand the problem too, that's why you can also use the change from [7d62e8f](https://github.com/cosmos/cosmjs/commit/7d62e8fc0d1c79e2ff5268d77584153256d4f769) once the next release is released.
> 
> Regarding your build issues - can you list ALL the steps you take?

When will the version be released?

**Comment by zwht** [comment]
> If I set the proxy, an error will be reported： `proxy: { // 配置跨域 '/rest': { target: 'https://lcd-cosmoshub.keplr.app',//后端接口地址 ws: true, changOrigin: true, pathRewrite: { '^/rest': '' } } }` asyncToGenerator.js?1da1:6 Uncaught (in promise) Error: Bad status on response: 404

This is intended for everyone, there should be no cross-domain issues, hopefully this will be resolved

**Comment by zwht** [comment]
``

**Comment by msteiner96** [comment]
@zwht You can simple fix the building problem by: 

- `Install yarn`
- `cd your/path/cosmjs`
- `rm -R node_modules/`
- `yarn`
- `yarn build`

**Comment by msteiner96** [comment]
Try `yarn cache clean` before.

**Comment by zwht** [comment]
Starport url: https://docs.starport.com/guide/
Open to : https://docs.ignite.com/guide/

The update was so sudden, I didn't even realize it

**Comment by zwht** [comment]
> Try `yarn cache clean` before.

Ok  thank you

**Comment by Venkatesh0625** [comment]
Hi @zwht, the same error occurred for me, can you help me solve ?

**Comment by msteiner96** [comment]
To sum this issue up (and keep it closed):

- If you have building issues, re-clone the project and use yarn instead of npm. npm isn't supporting the workspaces like we set it up here. (at least I don't know how)
- In the initial issue the author described how he wanted to connect to a LCD/"Rest"-Server. This isn't supported by CosmJS. You always have to connect to a RPC Host.

If you have any further issues please keep this one closed and consider to open a new one.
