### ISSUE TITLE
Int53 does not match golang int64 type size

### ISSUE THREAD

**Issue by zhcppy** [cosmos/cosmjs#1133]
Hi!

In the Tendermint34 package, there is an overflow of Int53 type when decoding the data returned on the blockchain, such as block height and voting power, the int64 type used by tendermint, the range is: -2^63-1 to 2^63 but Int53 only has - (2^53 - 1) to 2^53 - 1.

[cosmjs tendermint34 reponses types](https://github.com/cosmos/cosmjs/blob/main/packages/tendermint-rpc/src/tendermint34/adaptor/responses.ts#L379)

[tendermint rpc responses types](https://github.com/tendermint/tendermint/blob/master/rpc/coretypes/responses.go#L30)

[Integer parse error](https://github.com/cosmos/cosmjs/blob/main/packages/tendermint-rpc/src/tendermint34/adaptor/responses.ts#L385)

**Comment by webmaster128** [comment]
Right. This is intentional in order to be able to use JavaScript `number`s. For which use case do you run into this problem? Do you have a height > 2^53?

**Comment by zhcppy** [comment]
[validator voting power](https://github.com/cosmos/cosmjs/blob/e9d678aa8fb74b858c5ecec9ac8fb7e931ac9bc4/packages/tendermint-rpc/src/tendermint34/adaptor/responses.ts#L542)

**Comment by webmaster128** [comment]
Arg, we fixed this before when we hit the limit of the 32 bit range (https://github.com/confio/ts-relayer/issues/204). Now you exceed the 53 bit range? How is that possible? Using some crazy Ethereum tokens for staking?

**Comment by zakir-code** [comment]
This is because the precision of the staking token I use is 18. If the number of delegations is 10^20 and the power reduce is 100, then the voting power is 10^18 which is greater than 2^53-1

**Comment by zakir-code** [comment]
In more extreme cases, set [DefaultPowerReduction](https://github.com/cosmos/cosmos-sdk/blob/3e3c114af562063b822084d2e4cbc4c19c8414e3/types/staking.go#L22) to 100

**Comment by webmaster128** [comment]
For the Tendermint 0.35 client we can use BigInt for the voting powers. Then we are safe. It would be the first usage of bigint in CosmJS API. Hope it would not cause trouble for devs.

**Comment by webmaster128** [comment]
Do you know the expected value range in the `proposer_priority` field, especially in your scenario? This seems to be Int64 in Go (signed), which means we cannot use the Uint64 type client side. Curious if this can remain `number` as now.

**Comment by webmaster128** [comment]
Given that Cosmos SDK 0.46 will use Tendermint 0.34 (https://github.com/cosmos/cosmjs/issues/1093#issuecomment-1162686074), I think we'll make the change for both Tendermint 0.34 and 0.35 client from CosmJS 0.29 on.

**Comment by zakir-code** [comment]
> Do you know the expected value range in the `proposer_priority` field, especially in your scenario? This seems to be Int64 in Go (signed), which means we cannot use the Uint64 type client side. Curious if this can remain `number` as now.

The `proposer_priority` field exists with a negative number. In fact, the case of exceeding int64 is very special and generally does not appear, so now you can continue to use `number`

**Comment by webmaster128** [comment]
Thanks.

https://github.com/cosmos/cosmjs/pull/1187 is ready for review now.
