### ISSUE TITLE
Error: Broadcasting transaction failed with code 4 (codespace: sdk). Log: signature verification failed; please verify account number (697101) and chain-id (theta-testnet-001): unauthorized as an error please ping me.

### ISSUE THREAD

**Issue by dimitardanailov** [cosmos/cosmjs#1140]
Greetings, 

I've been working to integrate Cosmosjs in my current job as a Staff Engineer in https://propine.com. Our crypto solution uses external provider (IBM hyper protect crypto services using the enterprise pkcs11(ep11)) to store all private keys. Each transaction should be signed manually. Unfortunately each transaction fails. The error message is:
 `Error: Broadcasting transaction failed with code 4 (codespace: sdk). Log: signature verification failed; please verify account number (697101) and chain-id (theta-testnet-001): unauthorized as an error please ping me.`

**Comment by srph** [comment]
Sorry for bumping this, bow were you able to fix this?

**Comment by mzndako** [comment]
I had the same error but realised I was using the keypair (privateKey + publicKey) for signing the transaction instead of the privateKey alone (32 bytes). Using the privateKey alone resolved the error from my end.
