### ISSUE TITLE
DirectSecp256k1HdWallet.fromMnemonic in Cosmos SDK (Golang)

### ISSUE THREAD

**Issue by solitarysp** [cosmos/cosmjs#1145]
I am using `DirectSecp256k1HdWallet.fromMnemonic` in cosmosjd.
I need to use it in Cosmos SDK.
Help me please.

**Comment by nooomski** [comment]
Can you please be a bit more specific about your problem? It's unclear what you need help with.

**Comment by thangld322** [comment]
I think he wants some example of this [classes DirectSecp256k1HdWallet](https://cosmos.github.io/cosmjs/latest/proto-signing/classes/DirectSecp256k1HdWallet.html#constructor) to generate account address from mnemonic.
I need that too. Can you give me some? Thank a lot!

**Comment by solitarysp** [comment]
Thanks, my problem is solved.
