### ISSUE TITLE
How do I simulate a transaction?

### ISSUE THREAD

**Issue by joost-quro** [cosmos/cosmjs#1148]
I want to know how many tokens I would get when I do a swap, basically simulating the transaction without actually singing and broadcasting it. In the same way how a DEX shows the result before you do a  swap. I tried the `simulate` function, but that just returns a number value.

**Comment by nooomski** [comment]
CosmJS doesn't support this. You would have to check if the dex in question (osmosis?) has this functionality, but my theory is that you would have to calculate this manually.

Transaction simulation is meant to check if a transaction is valid and to see how much gas is returned. Closing this because it's out of scope for CosmJS. I would suggest asking in the Osmosis Discord :)

**Comment by webmaster128** [comment]
In https://github.com/cosmos/cosmjs/blob/v0.28.4/packages/stargate/src/signingstargateclient.ts#L175 we throw away a lot if transaction simulation information for the sage of simplicity. The full information you can have there is

```
/**
 * SimulateResponse is the response type for the
 * Service.SimulateRPC method.
 */
export interface SimulateResponse {
  /** gas_info is the information about gas used in the simulation. */
  gasInfo?: GasInfo;
  /** result is the result of the simulation. */
  result?: Result;
}

/** Result is the union of ResponseFormat and ResponseCheckTx. */
export interface Result {
  /**
   * Data is any data returned from message or handler execution. It MUST be
   * length prefixed in order to separate data from multiple message executions.
   */
  data: Uint8Array;
  /** Log contains the log information from message or handler execution. */
  log: string;
  /**
   * Events contains a slice of Event objects that were emitted during message
   * or handler execution.
   */
  events: Event[];
}
```

So it is well possible that the info you look for in the the tx execution data or events. To get that, you'd need a custom re-implementation of `SigningStargateClient.simulate`.

**Comment by shang-chi-7** [comment]
You can use this cosm js function to simulate a transaction using a POST method /cosmos/tx/v1beta1/simulate.
The docs are available in [cosmjs](https://v1.cosmos.network/rpc/v0.41.4)

**Comment by apollo-sturdy** [comment]
@webmaster128 I just had the same issue and was wondering if you think it would make sense to add this functionality as part of cosmjs? As you mention it is mostly there already in the `SigningStargateClient.simulate`. Perhaps we can re-use this code and have one function that gets the message responses and one that just gives the gas used?

Out of curiosity, do you know how people are currently handling this? Are they all re-implementing the code from `SigningStargateClient.simulate`? Seems like a very common use-case to want to simulate transactions for slippage control or just to show the user the some output of their action before they execute. I would have thought a majority of dapp frontends would need this in some capacity.
