### ISSUE TITLE
Is it possible to get gas_used, gas_wanted, status code etc. of a transaction directly from Block response?

### ISSUE THREAD

**Issue by oblak1** [cosmos/cosmjs#1149]
When calling `Tendermint34Client.block() ` I'm able to decode tx hashes with `decodeTxRaw`. Below is the DecodedTxRaw definition:
```
interface DecodedTxRaw {
    readonly authInfo: AuthInfo;
    readonly body: TxBody;
    readonly signatures: readonly Uint8Array[];
}
```

My question is if it's possible to get other important information about transactions, such as gas_used, gas_wanted status code etc. similar to `TxResponse` without losing the information above? I know there is a stargate query client extension for tx and another blockResults tendermint call but I would like to get the info of block and all of its txs in one call. If I understand correctly the block should contain the necessary data by itself.

**Comment by webmaster128** [comment]
Seems like you have to use the blockResults call to get this data. But decoding the response of this is currently broken (see https://github.com/cosmos/cosmjs/issues/1142).
