### ISSUE TITLE
How to get TxHash from block.messages ?

### ISSUE THREAD

**Issue by bytesmix** [cosmos/cosmjs#1153]
1. get block info using height., "/blocks/" + height
2. block.data.txs array values are transactions right?
3. but there no txHash value. only exists encoded value.
4. and i decoded that value to 
        const CosmSigning =  require("@cosmjs/proto-signing");       
        const decoded = Buffer.from(tx, 'base64');
        const raw = CosmSigning.decodeTxRaw(decoded);
        
        {
  authInfo: {
    signerInfos: [ [Object] ],
    fee: { gasLimit: [Long], payer: '', granter: '', amount: [Array] }
  },
  body: {
    memo: '',
    timeoutHeight: Long { low: 0, high: 0, unsigned: true },
    messages: [ [Object] ],
    extensionOptions: [],
    nonCriticalExtensionOptions: []
  },
  signatures: [
    <Buffer 67 e4 c5 57 f3 81 53 9a 69 57 c6 58 55 7a 76 38 d1 1c 89 bf e1 1d 02 93 00 25 2e 67 f6 76 a7 66 70 6e da d7 c0 ac 0a 47 86 ee 6f 12 32 b9 c0 38 45 c8 ... 14 more bytes>
  ]
}

5. but there are no transaction Hash ( txHash )
How can i calculate txHash from that?

**Comment by webmaster128** [comment]
`decoded` is the full transaction bytes I guess. Then `toHex(decoded).toUpperCase()` should do the job.

By thew way, we have `toBase64`/`fromBase64`/`toHex`/`fromHex` in `@cosmjs/encoding` which gives you nice Uint8Array instead of node.js specific Buffer types.

**Comment by bytesmix** [comment]
@webmaster128 oh thanks!!! i solved :)
