### ISSUE TITLE
How to send ATOM using cosmjs? ( can't find sample )

### ISSUE THREAD

**Issue by bytesmix** [cosmos/cosmjs#1157]
i  checked, 
1. create wallet, deposit ATOM, get balance.

But there are no sample or code to make send transaction and send.

Anyone who can help? or any docs?

**Comment by bytesmix** [comment]
const rpcEndpoint = "~~~";
const client = await SigningStargateClient.connectWithSigner(rpcEndpoint, wallet);
const result = await client.sendTokens(firstAccount.address, firstAccount.address, [coin], 11111, "Have fun with your star coins");
assertIsBroadcastTxSuccess(result);

i found this. but always error.

Maybe wrong rpcEndpoint or sendTokens error

an how to calculate gasFee for transaction?

**Comment by bytesmix** [comment]
and other solution is using https://v1.cosmos.network/rpc/v0.41.4

but i don't know how to make transaction object.

sample:

const value = {
    "tx": {
      "msg": ["string"],
      "fee": {
        "gas": "1",
        "amount": [
          {
            "denom": "uatom",
            "amount": "50"
          }
        ]
      },
      "memo": "string",
      "signature": {
        "signature": "MEUCIQD02fsDPra8MtbRsyB1w7bqTM55Wu138zQbFcWx4+CFyAIge5WNPfKIuvzBZ69MyqHsqD8S1IwiEp+iUb6VSdtlpgY=",
        "pub_key": {
          "type": "tendermint/PubKeySecp256k1",
          "value": "Avz04VhtKJh8ACCVzlI8aTosGy0ikFXKIVHQ3jKMrosH"
        },
        "account_number": "0",
        "sequence": "0"
      }
    },
    "mode": "block"
  }

**Comment by bytesmix** [comment]
@webmaster128 Hi. You are professional about cosmjs ^^;

Can you guide me how to withdraw using 

https://v1.cosmos.network/rpc/v0.41.4

this REST API ?

POST ​/cosmos​/tx​/v1beta1​/txs

I can't understand how can i make body data.

i also read your article.
https://gist.github.com/webmaster128/8444d42a7eceeda2544c8a59fbd7e1d9

but there are errors when call sendTokens.

const result = await client.sendTokens(firstAccount.address, recipient, [amount], "Have fun with your star coins");
assertIsBroadcastTxSuccess(result);

**Comment by bytesmix** [comment]
this is my final code. ( finally success )

1. what is proper gasPrice ? ( i just fixed 0.002 )
    let gasprice = GasPrice.fromString("0.002uatom"); 
    
2. when i use  v1.cosmos.network how to add 'tx_bytes' value to REST API?
    const txBytes = TxRaw.encode(txRaw).finish();
    txBytes are Uint8Array.


```

    const wallet = await Sinign.DirectSecp256k1HdWallet.fromMnemonic(mnemonic);
    const [firstAccount] = await wallet.getAccounts();
    const coin = await cosmos.getBalance(firstAccount.address);
    const rpcEndpoint = "https://~~~";
    const client = await SigningStargateClient.connectWithSigner(rpcEndpoint, wallet);    
    
    const amt = Coins.coin(8000, coin.denom);
    const sendMsg = {
        typeUrl: "/cosmos.bank.v1beta1.MsgSend",
        value: {
          fromAddress: firstAccount.address,
          toAddress: firstAccount.address,
          amount: [amt],
        }
    };

    const gasEstimation = await client.simulate(firstAccount.address, [sendMsg], "MSG");
    const multiplier = 1.3;
    let gasprice = GasPrice.fromString("0.002uatom");
    let usedFee = calculateFee(Math.round(gasEstimation * multiplier), gasprice);
    const txRaw = await client.sign(firstAccount.address, [sendMsg], usedFee, "MSG");
    const txBytes = TxRaw.encode(txRaw).finish();
    
```

**Comment by nooomski** [comment]
Hey @bytesmix , we have a new tutorial online that shows you how to do a token transfer using CosmJS, it also includes some info about gas and how to encode/decode. You can find it here: 
You can also find working RPC endpoints in the [Chain Registry](https://github.com/cosmos/chain-registry/blob/master/cosmoshub/chain.json) that you can use for testing & development purposes.

This should probably help you, so I'm closing this issue for now, but please re-open if you're running into further obstacles that might be related to problems in CosmJS.

**Comment by ranlavanet** [comment]
link "here" is broken :)

**Comment by nooomski** [comment]
Ah yes, that changed, [here you go](https://tutorials.cosmos.network/tutorials/6-cosmjs/) @ranlavanet :)

**Comment by Tocard** [comment]
link still broken @nooomski

**Comment by nooomski** [comment]
@Tocard , updated link is [here](https://tutorials.cosmos.network/tutorials/7-cosmjs/): 
For future reference, just go to https://developers.cosmos.network, you'll find all CosmJS tutorials there :)
