### ISSUE TITLE
Unable to Instantiate CW3 Contract on Osmosis Chain

### ISSUE THREAD

**Issue by swizzmagik** [cosmos/cosmjs#1158]
I am using the SigningCosmWasmClient and attempting to instantiate a simple CW3 on Osmosis, but I am running into the following error message:

`Uncaught (in promise) Error: Broadcasting transaction failed with code 2 (codespace: sdk). Log: unable to resolve type URL /cosmwasm.wasm.v1beta1.MsgInstantiateContract: tx parse error
    at SigningCosmWasmClient.broadcastTx (cosmwasmclient.ts:256:1)
    at async SigningCosmWasmClient.instantiate (signingcosmwasmclient.ts:252:1)
    at async onSubmit (CreateNewWalletForm.tsx:287:1)`

Everything seems to be correct and I am wondering if there is an issue with the signing client not being able to find the type URL. 

I am using 
`"@cosmjs/cosmwasm-stargate": "^0.25.6",`

and here is the relavent code
`    const client: SigningCosmWasmClient =
      await SigningCosmWasmClient.connectWithSigner(
        'https://testnet-rpc.osmosis.zone/',
        offlineSigner
      );`

    const msg: any = {
      voters: [
        {
          addr: 'osmo1XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
          weight: 50
        },
        {
          addr: 'osmo1XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
          weight: 50
        }
      ],
      threshold: 51,
      max_voting_period: {
        time: 604800
      }
    };

    const result = await client.instantiate(
      'osmo1XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
      CODE_ID_TESTNET,
      msg,
      'my-fun-cw3'
    );

Could this be a bug with the signing client?

**Comment by swizzmagik** [comment]
This was user error.

**Comment by kevinroleke** [comment]
@swizzmagik Do you happen to recall what the solution for this was?

**Comment by swizzmagik** [comment]
@kevinroleke the threshold message was incorrectly formatted and instead of how I had it above it needed to be:

```
const msg: any = {
  voters: [
    {
      addr: 'osmo1XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
      weight: 50
    },
    {
      addr: 'osmo1XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
      weight: 50
    }
  ],
  threshold: {
    absolute_count: {
      weight: 51
    }
  },
  max_voting_period: {
    time: 604800
  }
};

```

**Comment by ratankaliani** [comment]
@swizzmagik How did you initialize your offline signer? Seem to be running into some issues with setting that up

**Comment by swizzmagik** [comment]
@ratankaliani This is essentially how we did it. I hope this helps!

`
  const getOfflineSigner = async () => {
    if (!window.keplr || !window.getOfflineSigner) {
      throw new Error('Error connecting to wallet or keplr');
    }
    await window.keplr!.enable(network.chainInfo.chainId);
    return await window.getOfflineSigner(network.chainInfo.chainId);
  };

  const getSigningClient = async (): Promise<
    SigningCosmWasmClient | undefined
  > => {
    const offlineSigner = await getOfflineSigner();

    return await SigningCosmWasmClient.connectWithSigner(
      network.chainInfo.rpc,
      offlineSigner,
      {
        gasPrice: {
          amount: Decimal.fromUserInput(network.fee.gas, 4) as any,
          denom: network.fee.amount[0].denom
        }
      }
    );
  };`
