### ISSUE TITLE
Is decoding of cosmoshub-3 transactions supported? 

### ISSUE THREAD

**Issue by mdyring** [cosmos/cosmjs#1169]
Thanks for the great library/work 👍 

I am trying to decode some "legacy" (2021ish) transactions that originated on cosmoshub-3.

I have the base64 data from the /block RPC, decoded into a Buffer.

Since this is before protobuf I am struggling a bit with the next step. decodeTxRaw obviously fails when given an Amino buffer, but is there any support for this in cosmjs?

I have tried using @tendermint/amino-js as well, but unfortunately it seems abandoned and does not decode the transactions either. It does, however seem to work for the majority of cosmoshub-1/2 messages.

**Comment by mdyring** [comment]
Closing as I got it working with the [v0.7.0-alpha.1](https://github.com/cosmos/amino-js/releases/tag/v0.7.0-alpha.1) release of amino-js.

**Comment by webmaster128** [comment]
CosmJS never had a full Amino encoder/decoder. We just do a bit of manual byte concatenation where we can't avoid it (e.g. pubkeys). Before Stargare (which brought protobuf encoded transactions), we connected to the LCD API, which decoded transactions in the backend and returned decoded JSON.

Glad you found a solution!
