### ISSUE TITLE
add ''(empty string) type to `BondStatusString` to support query all validators

### ISSUE THREAD

**Issue by fantasticist** [cosmos/cosmjs#1170]

**Comment by webmaster128** [comment]
Isn't that the same as "UNRECOGNIZED"? I.e. the default value of the enum.

**Comment by fantasticist** [comment]
It will throw an error, when I use 'UNRECOGNIZED'.

**Comment by fantasticist** [comment]
I mean I want get all validators, and it works when I use empty string, but `BondStatusString` not include empty string.

**Comment by webmaster128** [comment]
Okay, not it makes sense. The comment in https://github.com/cosmos/cosmjs/pull/1171 explains the strangeness.

**Comment by fantasticist** [comment]
Nice

**Comment by webmaster128** [comment]
Released as part of 0.28.7.
