### ISSUE TITLE
No bundler / CDN usage example

### ISSUE THREAD

**Issue by dakom** [cosmos/cosmjs#1189]
Would be helpful to have something like this, for projects that are not able to follow the webpack example in the readme

**Comment by dakom** [comment]
I see... yeah, all I really need afaik is SigningCosmWasmClient so, yeah, I should be able to grab it from there.

fwiw the _real_ issue I'm running into is trying to import `@cosmjs/cosmwasm-stargate` in a rollup-based project, and my rollup-fu isn't very strong

**Comment by solitarysp** [comment]
@webmaster128 I still haven't solved it, can you help us?

**Comment by dakom** [comment]
this works for me:

```html
<script crossorigin src="https://unpkg.com/cosmwasm/dist/bundle.js" ></script>
```

```javascript
const {SigningCosmWasmClient, calculateFee, coin, GasPrice} = window.CosmWasmJS;
```

**Comment by webmaster128** [comment]
> I still think the issue should be open

Due to the lack of a single entry point, I doubt CosmJS is suiteable for this sort of deployment. If you include multiple packages in a website, all dependencies are bundled and shipped multiple times.

Will keep this open but don't see a good way to solve it.

**Comment by solitarysp** [comment]
> this works for me:
> 
> ```
> <script crossorigin src="https://unpkg.com/cosmwasm/dist/bundle.js" ></script>
> ```
> 
> ```js
> const {SigningCosmWasmClient, calculateFee, coin, GasPrice} = window.CosmWasmJS;
> ```
> 
> I still think the issue should be open since the above is at the mercy of `cosmwasmjs` re-exporting everything, and it'd be nicer to just use rollup or a direct CDN include for the individual packages directly, but it's a solid "workaround" at least for now

Thanks, now solved my problem.
