### ISSUE TITLE
Why using async in secp256k1? 

### ISSUE THREAD

**Issue by kailingding** [cosmos/cosmjs#1194]
There's no await in [`Secp256k1. makeKeypair()`](https://github.com/cosmos/cosmjs/blob/9ab064e5d8c92ae59e96e79f50dce495a85c13c1/packages/crypto/src/secp256k1.ts#L31), why using async here?

**Comment by kailingding** [comment]
Thx for the answer. it's not a super big issue. just curious because keypairs in ethereum and solana is using sync and just wondering why cosmjs uses async. We are building a cross-chain wallet that interacts with multiple blockchains. essentially doing a mnemonic convertor to keypairs in each blockchain.

**Comment by webmaster128** [comment]
Okay, cool. Keeping it async keeps us flexible with the implementation. So I'd keep it like this for now.
