### ISSUE TITLE
Get file build js of cosmwasm-stargate

### ISSUE THREAD

**Issue by solitarysp** [cosmos/cosmjs#1197]
I need to use `cosmwasm-stargate`, but my application uses `thymeleaf` how do I use it?
Does it have a js build file?

**Comment by webmaster128** [comment]
Does this answer help? https://github.com/cosmos/cosmjs/issues/1189#issuecomment-1163130219

**Comment by webmaster128** [comment]
Closing as duplicate of https://github.com/cosmos/cosmjs/issues/1189
