### ISSUE TITLE
Error parsing tx result: Invalid string. Length must be a multiple of 4

### ISSUE THREAD

**Issue by Redm4x** [cosmos/cosmjs#1201]
Hi, after successfully broadcasting a transaction with the `SigningStargateClient` I get the following error:
![image](https://user-images.githubusercontent.com/2829180/176274476-a4b18242-3009-4939-b583-2b9363165887.png)

Someone else had the same issue [here](https://github.com/cosmos/cosmos-sdk/issues/11997) and it looks like it happens because cosmjs is using a tendermint `0.34` client instead of `0.35`.

I see that a pull request to add `Tendermint35Client` was merged two weeks ago (#1173), but when I try using the latest npm version (`v0.28.9` released 7 days ago) I still get the same error and I only see `Tendermint34Client` in the code.

Is it supposed to work or do I need to wait for a future version still?

**Comment by webmaster128** [comment]
Which network is that? The upcoming Cosmos SDK 0.46 will be using Tendermint 0.34.x (see https://github.com/cosmos/cosmjs/issues/1093#issuecomment-1162686074).

CosmJS 0.29 will ship a Tendermint 0.35 client bit that will not be used by higher level clients such as StargateClient.

**Comment by Redm4x** [comment]
It's a new network still in development. Thanks for the insight about the upcoming Cosmos SDK v0.46 I wasn't aware it would be staying on Tendermint 0.34.x.
