### ISSUE TITLE
Invalid Bech32 prefix ; expected cosmos, got osmo (HTTP 500)

### ISSUE THREAD

**Issue by sera-korbit** [cosmos/cosmjs#1207]
what is the fundamental problem of this error?
and how can i solve this?

It occurs when the recipent address starts with osmo~, using sendTokens method in signingcosmosclient.
but even if i change the address to other one starting with cosmo~, i got this error.

please check this error and your SDK.

**Comment by webmaster128** [comment]
The chain says "expected cosmos", not "cosmo".

Which blockchain are you connecting to?

**Comment by sera-korbit** [comment]
I have used https://api.cosmos.network.

My code is here.

    const URL='https://api.cosmos.network';
    const prefix = 'osmo';
    const faucet ={
        mnemonic :' own mnemonic',
        address0: 'own address starting with prefix osmo',
    }


    const wallet = await DirectSecp256k1HdWallet.fromMnemonic(faucet.mnemonic, {prefix : prefix});

    //Random recipient
    const recipient = toBech32(prefix, Random.getBytes(20));

    const amount = coins(226644, 'ucosm');

    const fee = calculateFee(200000, '0025ucosm');

    const memo ='ensure chain has my pubkey';

    const signingClient = new SigningCosmosClient(URL, faucet.address0,wallet);

    const result = await signingClient.sendTokens(recipient, amount);

**Comment by webmaster128** [comment]
api.cosmos.network is an endpoint for the Cosmos Hub, not Osmosis. Those are different blockchains.
