### ISSUE TITLE
cosmJS.searchTx not returning all transactions when passing in no filters ... 

### ISSUE THREAD

**Issue by Goochie** [cosmos/cosmjs#1208]
Last week this worked fine but this morning older transactions are now not being returned.

Up until this morning we have been using cosmJS.searchTx({ sentFromOrTo: 'aPublicKey' });

..... which means the min height and max height gets defaulted to the following..

    const minHeight = filter.minHeight || 0;
    const maxHeight = filter.maxHeight || Number.MAX_SAFE_INTEGER;

... but this morning no transaction are being returned, with the latest transaction being 14 days ago.

1. So i created a new transaction on our test account and hit the api and only that transaction is returned.

I tried setting the filter config to { minHeight: 0, maxHeight: 1111133539 } but again only the transaction made today is showing.

What has changed, since last week ?

**Comment by Goochie** [comment]
ok, so this helps me understand the stack more, as a developer i am building a Dapp i want to use  comsJS - to use comsJS you have to create a cosmClient instance by instantiating with a RPC node.  

For the cosmoshub we have the following rpc nodes ...

 "apis": {
                "rpc": [
                    {
                        "address": "https://rpc-cosmoshub.blockapsis.com",
                        "provider": "chainapsis"
                    },
                    {
                        "address": "https://cosmoshub.validator.network/",
                        "provider": "validatornetwork"
                    },
                    {
                        "address": "https://cosmoshub-4.technofractal.com:443",
                        "provider": "strangelove-ventures"
                    },
                    {
                        "address": "https://rpc.cosmos.network:443",
                        "provider": "tendermint-inc"
                    },
                    {
                        "address": "https://rpc-cosmoshub.ecostake.com",
                        "provider": "ecostake"
                    },
                    {
                        "address": "https://rpc.cosmoshub.pupmos.network",
                        "provider": "pupmos"
                    },
                    {
                        "address": "https://cosmos-rpc.polkachu.com",
                        "provider": "Polkachu"
                    },
                    {
                        "address": "https://rpc.cosmos.ezstaking.io",
                        "provider": "EZStaking.io"
                    },
                    {
                        "address": "https://rpc-cosmoshub-ia.notional.ventures/",
                        "provider": "Notional"
                    }
                ],

Apart from Notional and pupmos they all return CORS errors when using comsJS and now Notional and pupmos on the surface with current knowledge only have less than 14 days worth of transactions.

Therefore whats the expectations here ....

1. Are there other RPC nodes that aren't publicly available
2. To build a dapp you have to create a node yourself

**Comment by webmaster128** [comment]
Most node operators don't understand web tech well and don't understand CORS. It would be good to talk to them and convince them that there is nothing wrong with opening up CORS to all origins is not unsafe. The same applied for pruning. Maybe you can encourage them to run nodes that keep all transactions.

But if you need full control over the node's behaviour, you probably have to spawn your own or pay someone to do that for you.

**Comment by Goochie** [comment]
Thank you, very insightful as always :) .... and yes i have already reached out to one and posted some questions on the infrastructure thread of the comos hub discord .. whilst your online do you have any feedback on this query ...

https://github.com/cosmos/cosmjs/issues/1205

**Comment by nooomski** [comment]
Hey @goochie and @webmaster128 , just wanted to chime in here and clarify that it is definitely recommended practice for dapp developers to either maintain a node themselves or get a node through a service otherwise.

The public nodes that are available are for development and testing purposes only. No dapp should rely on them as quality of service cannot be guaranteed.

Closing this unless there are any other questions :)
