### ISSUE TITLE
Convert one bech32 to another bech32 in different network, but with different coinType 

### ISSUE THREAD

**Issue by RuslanGlaznyov** [cosmos/cosmjs#1220]
As mentioned here https://github.com/confio/cosmos-hd-key-derivation-spec#bip44
If coin Type: 118 we can convert from one address to another and they will be corresponding to the same privateKey/mnemonic
Is it possible to convert for example Cosmos address to Persistence in the same way but Persistence has different coinType?

**Comment by webmaster128** [comment]
If a different coint type is used (and more general, if any component in the HD derivation part is different), you get a different private and public key. You cannot convert between the two. Only the owner of the mnemonic can derive both paths and get both keypairs.

**Comment by RuslanGlaznyov** [comment]
Great explanation and fast response!
