### ISSUE TITLE
EVM compatiabilty with cosmjs

### ISSUE THREAD

**Issue by Abhishek-1857** [cosmos/cosmjs#1233]
Hey guys.. I am facing a problem that is when i use cosmjs library and getting private and public key with the mnemonics i am getting balance of the account for example 50 and when i am doing same with web3 or ether.js my private key is coming same as it was with cosmjs library and a different public key which is ofcourse evm type but im getting balance 0. I have integrated evm in my wasm chain but im facing this issue.. If anyone can help and have any ideas please help...

**Comment by webmaster128** [comment]
See https://github.com/cosmos/cosmjs/issues/1351
