### ISSUE TITLE
RAW signing via fireblocks API

### ISSUE THREAD

**Issue by nooxx** [cosmos/cosmjs#1243]
Hello, I'm trying to sign a delegate transaction via the fireblocks RAW signing API.

Their method takes the transaction serialized in hexadecimal. 

Here is my code on how to build the transaction:

```javascript
import { FireblocksSDK, PeerType, TransactionOperation } from 'fireblocks-sdk';
import { coin } from "@cosmjs/proto-signing";
import { MsgDelegate } from "cosmjs-types/cosmos/staking/v1beta1/tx";
import { toHex } from "@cosmjs/encoding";
import { makeSignDoc, serializeSignDoc } from "@cosmjs/amino";

const fs = require('fs');

const apiSecret = fs.readFileSync('./fireblocks_secret.key', 'utf8');
const apiKey = 'xxx';
const fireblocks = new FireblocksSDK(apiSecret, apiKey);

(async () => {
  const vault = await fireblocks.getVaultAccountsWithPageInfo({
    namePrefix: 'account name',
  });

  const vaultId = vault.accounts[0].id;

  try {
    const msg = MsgDelegate.fromPartial({
      delegatorAddress: 'cosmos19c9fdh488vqjclltwp68jm50ydwyh36jqeatev',
      validatorAddress: 'cosmosvaloper178h4s6at5v9cd8m9n7ew3hg7k9eh0s6wptxpcn',
      amount: coin('5000', "uatom"),
    });

    const memo = "Use your power wisely";
    const feeAmount = coin(5193, "uatom");
    const sendMsg = {
      type: "/cosmos.staking.v1beta1.MsgDelegate",
      value: msg,
    };

    const fee = {
      amount: [feeAmount],
      gas: '300000',
    };

    const accountNumber = 698081;
    const sequence = 0;

    const doc = makeSignDoc(
      [sendMsg],
      fee,
      'theta-testnet-001',
      memo,
      accountNumber,
      sequence,
    );

    const encoded = toHex(serializeSignDoc(doc));

    const res = await fireblocks.createTransaction({
      assetId: 'ATOM_COS_TEST',
      note: 'Automated ATOM staking transaction',
      source: {
        type: PeerType.VAULT_ACCOUNT,
        id: vaultId,
      },
      operation: TransactionOperation.RAW,
      extraParameters: {
        rawMessageData: {
          messages: [
            {
              content: encoded,
            },
          ],
        },
      },
    });
    console.log('success:', res);
  } catch (err) {
    console.log(err);
  }
})();
```

Do you see any issue with this code? When submitting this, the transaction is "submitted" for signing but marked as "failed" in fireblocks.

**Comment by webmaster128** [comment]
I don't know fireblocks at all. `makeSignDoc, serializeSignDoc } from "@cosmjs/amino"` is used for sign mode Amino JSON. Is this what you want?

**Comment by nooxx** [comment]
I got it working eventually. Solution is to use a SigningStargateClient. This can be closed thanks!

**Comment by webmaster128** [comment]
Did you manage using SigningStargateClient with a fireblocks signing interface? That would be pretty amazing. Do you have a repo you can share?

**Comment by nooxx** [comment]
Yeah I did, we are keeping our repo private for the moment unfortunately.

**Comment by webmaster128** [comment]
Nice!

And congratz to ourself for designing this great interface :D

**Comment by jonathantyar** [comment]
@nooxx hi, can u give an example of use for ``SigningStargateClient`` in this issue? it will be helpful for those who also want to delegate using fireblocks

**Comment by jonathantyar** [comment]
@webmaster128 i already completed the raw signing via fireblocks API and it may be useful for other custodian user that need partial signing from their custodian, can i put the documentation for it? if yes, where?

**Comment by anthonyjoeseph** [comment]
We were able to achieve this - [gist](https://gist.github.com/anthonyjoeseph/d46327a0a76cb6ad011148100419417c) if you want to follow our steps
