### ISSUE TITLE
queryUnverified does not thread desiredHeight

### ISSUE THREAD

**Issue by kriskowal** [cosmos/cosmjs#1250]
In the Stargate QueryClient, the method `queryUnverified` does not thread an optional third argument for the height of the query. This is inconsistent with `queryVerified`. Is this omission intentional?

https://github.com/cosmos/cosmjs/blob/155ed33dd6d2df4f786047fd2e06848912cd0b07/packages/stargate/src/queryclient/queryclient.ts#L573-L585

**Comment by webmaster128** [comment]
I think it was just never needed for our use cases. The height in `queryVerified` is needed for some proof stuff.

**Comment by webmaster128** [comment]
Can you have a look at #1255?

**Comment by webmaster128** [comment]
Shipped as part of CosmJS 0.29.0
