### ISSUE TITLE
Rune Transfers are currently disabled

### ISSUE THREAD

**Issue by sera-korbit** [cosmos/cosmjs#1252]
Hi Cosmos Team!

I have problem broadcasting Tx, transferring THOR.RUNE , which is going to be based on COSMOS SDK.
When I broadcasted Tx, I got Error  like " **Failed to exceute message; message index :0 : rune transfers are currently disabled : send transaction are disabled**'
What is the cause of this error? Or is it temporarily not allowed?
My code is below.

Thanks.

**Comment by webmaster128** [comment]
The error message

> rune transfers are currently disabled : send transaction are disabled

is coming from the chain (the node you connect to). So this is something Thorchain specific that I don't know about.
