### ISSUE TITLE
things are missing in stargate/index.ts and stargate/modules/index.ts

### ISSUE THREAD

**Issue by loin3** [cosmos/cosmjs#1258]
* `createVestingAminoConverters`, `createSlashingAminoConverters` are omitted in stargate/index.ts while other amino converters are exist. (In commit `5534493` createVestingAminoConverters are add to createDefaultTypes, but createVestingAminoConverters is not added to stargate/index.ts.)
* `setupAuthzExtension`, `setupSlashingExtension` are ommited in stargate/index.ts and stargate/modules/index.ts
* `createFreegrantAminoConverters` is typo in stargate/src/modules/feegrant/aminomessages.ts

**Comment by webmaster128** [comment]
Thank you for the detailed list, very helpful. This should be fixed in https://github.com/cosmos/cosmjs/pull/1261. Can you have a look?

**Comment by webmaster128** [comment]
Shipped as part of CosmJS 0.29.0
