### ISSUE TITLE
Unsuccessful connection always returns unhandled error

### ISSUE THREAD

**Issue by oblak1** [cosmos/cosmjs#1264]
I'm using cosmjs version 0.28.11.

If I try to connect to to tendermint node, like this:

```
try {
    this.tmClient = await Tendermint34Client.connect(chainConfig.wss);
  } catch (error) {
    throw new Error(error + '');
  }

```

I always get the unhandled rejection promise, which is weird since I'm using try catch here. Maybe I'm missing something but could it also be a bug?

```
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Connection attempt timed out after 10016 ms".] {
code: 'ERR_UNHANDLED_REJECTION'
}
```

**Comment by webmaster128** [comment]
Right, this should not happen. It might be this promise which does not have a reject handler: https://github.com/cosmos/cosmjs/blob/v0.29.0-rc.1/packages/socket/src/queueingstreamingsocket.ts#L80-L84

However, given that websocket connections never have been stable enough for most users and given that Tendermint > 0.34 removes the websocket connection, I would not put much effort into this anymore.

**Comment by oblak1** [comment]
Thanks, do you maybe know how the event streaming will be handled after 0.35? Tried googling it but cannot find a straight answer.

**Comment by webmaster128** [comment]
See https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-075-rpc-subscription.md for all information about the change.
