### ISSUE TITLE
Get Contracts by Creator Address

### ISSUE THREAD

**Issue by JakeHartnell** [cosmos/cosmjs#1266]
Would be useful for building out a number of features. For example, listing the contracts instantiated by a DAO or NFT contracts instantiated by an artist.

Thinking:
```
getContractsByCreator(address: string): Promise<Contract[]>
```

**Comment by webmaster128** [comment]
Good idea. But we have to implement that in wasmd first: https://github.com/CosmWasm/wasmd/issues/998
