### ISSUE TITLE
Getting pubkey while using a newly created cosmos wallet

### ISSUE THREAD

**Issue by SusheendharVijay** [cosmos/cosmjs#1301]
For my use case I need to generate a random new wallet and sign an broadcast a txn using it, but I need to get some account info for it, `accountNumber` `sequence` , `pubkey` etc. To get this info this account must be used in some txn right? (I believe it's used to perfom state pruning). 

So I sending some money to the account, now I get `accountNumber` and `sequence` but `pubkey` is empty. I tried to then sign a txn using `accountNumber` `sequence` and then `pubkey` from the wallet instead of from on-chain account info. But I get this error: ```'pubKey does not match signer address evmos1kdhpt8q5vl3wg8myv680l0k0uwwvdcs25wx67a with signer index: 0: invalid pubkey'```. I'm doing this on evmos but sharing here because it's probably a general cosmos q and also evmos github is not active all that much. Really appreciate any help. Thanks!

**Comment by webmaster128** [comment]
CosmJS does not support Evmo's public keys. Evmos uses Ethereum pubkeys, not Cosmos pubkeys. They use a different representation (uncompressed vs. compressed).
