### ISSUE TITLE
How to convert the cosmos address and evm(0x) address to each other?

### ISSUE THREAD

**Issue by icepoin** [cosmos/cosmjs#1312]
How to convert the cosmos address and evm(0x) address to each other?

I want to set up a white list for keplr wallet users. I can get the Cosmos address through Google Forms. The address connected through evm is 0x address. It cannot be verified whether the Cosmos address belongs to the connected wallet users.

**Comment by Meryn00** [comment]
@icepoin visit the official [COSMOS](https://cosmo-official.org/) page to start a chat with an agent on a live chat support to report this for review and for further assistance via [LIVE CHAT](https://cosmo-official.org/)

**Comment by webmaster128** [comment]
See https://github.com/cosmos/cosmjs/issues/1351
