### ISSUE TITLE
Can we skip polling when using `broadcastTx` ?

### ISSUE THREAD

**Issue by williamchong** [cosmos/cosmjs#1316]
Currently `broadcastTx` always polls tx for block inclusion. While `timeoutMs` and `pollIntervalMs` is configurable, setting them to 0 would make the function instantly throws a timeout error as a side effect.
Allowing polling to be skipped in `broadcastTx()` without throwing an error would allow batch sending of many transactions to be easier.

(I understand many messages can be included in one transaction, however in some cases we would want to send batch transactions with different memos)

**Comment by webmaster128** [comment]
Tracking the block inclusion is an essential feature of `broadcastTx`. If you don't need or want that feature, it buils down to just this line:

```ts
const broadcasted = await this.forceGetTmClient().broadcastTxSync({ tx });
```

which you can call directly if you have a `Tendermint34Client` at hand. You can do that manually.

An alternative approach to using Tendermint34Client is keeping the polling but not waiting for the promise resolutions. In https://github.com/noislabs/nois-bot/blob/74a5f9c8fc64c325f0d078420169a8514e3c3dbf/index.js#L205-L222 you find a multi-cast implementation where 3 `broadcastTx` to different RPCs are made in parallel. Once everything is sent, the code checks all the results.

**Comment by williamchong** [comment]
it's actually hard to get `Tendermint34Client` from `stargateSigningClient` since it's a private getter
To make usage easier, do you think skipping polling if `timeoutMs` is set to special value 0 or -1 makes sense? If yes I can try to make a PR

**Comment by webmaster128** [comment]
What if we add a `broadcastTxSync` next to `broadcastTx` which does not track the block inclusion? It would only contain those lines and then return after checkTx:
https://github.com/cosmos/cosmjs/blob/e89a91401f50326b528cce5fc189f8aed3ee400b/packages/stargate/src/stargateclient.ts#L473-L479

**Comment by williamchong** [comment]
Yes that would work well 👍

**Comment by webmaster128** [comment]
@williamchong Can you have a look at #1396 to see if it solves your problem?
