### ISSUE TITLE
Getting account sequence mismatch while broadcasting txns (parallelly)

### ISSUE THREAD

**Issue by Pratap2018** [cosmos/cosmjs#1317]
## Getting account sequence mismatch while broadcasting txns (parallelly) from same account (cosmjs  SigningStargateClient)

![image](https://user-images.githubusercontent.com/39677673/199715025-2c81aef5-3267-4463-9e95-2fb60078c271.png)

Account sequence mismatch while trying to broadcast txns (parallelly)

The provided link is how we have implemented cosmjs SigningStargateClient

https://github.com/hypersign-protocol/hid-ssi-js-sdk/blob/fc7f656edeb05c797130673ca1f9ac98d6eb1909/src/credential/credRPC.ts#L40

Code Snippet : 
```JAVASCRIPT
 const txMessage = {
      typeUrl, // Same as above
      value: generatedProto[HIDRpcEnums.MsgRegisterCredentialStatus].fromPartial({
        credentialStatus,
        proof,
        creator: HIDClient.getHidWalletAddress(),
      }),
    };

    const fee = 'auto';
    const hidClient: SigningStargateClient = HIDClient.getHidClient();
    const txResult: DeliverTxResponse = await hidClient.signAndBroadcast(
      HIDClient.getHidWalletAddress(),
      [txMessage],
      fee
    );
```

**Comment by webmaster128** [comment]
This is unfortunate but expected behaviour. For this reason we have multiple distributor accounts in the faucet application. There is very little we can do about it other than work around the problem, e.g. by using multiple accounts or batching multiple messages in one transaction.

**Comment by Pratap2018** [comment]
we want to achieve 100 txn from the same account per second (I know block production will take some seconds). Should we go with the batching?

**Comment by webmaster128** [comment]
Could you bring up this issue in the cosmossdk repo and link it here? I do not have a great idea how to do that given that all transactions with a sepence number > than the current one will be rejected at signature verification time until a new transaction is in a block.

**Comment by gh-zhangpeng** [comment]
> Could you bring up this issue in the cosmossdk repo and link it here? I do not have a great idea how to do that given that all transactions with a sepence number > than the current one will be rejected at signature verification time until a new transaction is in a block.

Is there a solution at the end? I have the same problem.
