### ISSUE TITLE
Remove deprecated QueryClient.queryUnverified and QueryClient.queryVerified

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#1332]
Deprecated in #1328 and #1337

**Comment by noelukwa** [comment]
@webmaster128 I would like to take care of this.

**Comment by webmaster128** [comment]
Thank you @noelukwa! But please note that this is for CosmJS 0.31. We first have to release 0.30.0 and probably a few patch releases before this should be merged.
