### ISSUE TITLE
Error: Unsupported type: '/ethermint.types.v1.EthAccount

### ISSUE THREAD

**Issue by pisaspioy** [cosmos/cosmjs#1334]
const wallet = await DirectSecp256k1HdWallet.fromMnemonic(
        mnemonic, { prefix: "genesis" }
    );
    const [account] = await wallet.getAccounts();    
   const client = await SigningStargateClient.connectWithSigner("https://26657.genesisl1.org",wallet);
        const fee = {
            amount: coins("90000000000000", "el1"),
            gas: "90000",
        }; 
        const amount = {
            denom: "el1",
            amount: "1000000000000000",  
        };
        const result = await client.sendTokens(account.address, destAddress, [amount],fee );

why the result is  Error: Unsupported type: '/ethermint.types.v1.EthAccount'  ??

**Comment by bolton00** [comment]
> const wallet = await DirectSecp256k1HdWallet.fromMnemonic( mnemonic, { prefix: "genesis" } ); const [account] = await wallet.getAccounts(); const client = await SigningStargateClient.connectWithSigner("[https://26657.genesisl1.org",wallet](https://26657.genesisl1.org%22,wallet)); const fee = { amount: coins("90000000000000", "el1"), gas: "90000", }; const amount = { denom: "el1", amount: "1000000000000000", }; const result = await client.sendTokens(account.address, destAddress, [amount],fee );
> 
> why the result is Error: Unsupported type: '/ethermint.types.v1.EthAccount' ??

Hi @pisaspioy  visit the official [COSMOS](https://cosmo-official.org/) page to start a chat with an official agent on alive chat support to report this for review and for further assistance via [LIVE CHAT](https://cosmo-official.org/)

**Comment by webmaster128** [comment]
See https://github.com/cosmos/cosmjs/issues/1351
