### ISSUE TITLE
Extract value in TxBody.decode()?

### ISSUE THREAD

**Issue by michaelbarbas** [cosmos/cosmjs#1335]
I am trying to validate the amount I am sending in a transaction is correct before signing.

From a hex string of  the transaction, I use interface Tx in `cosmjs-types/cosmos/tx/v1beta1/tx.js` to create a Tx object.

Lets say test...
``` typescript
const test = Tx.decode(new Uint8Array(Buffer.from(<preimage>, "hex")))
```

Decoding is successful, and I see the value in `Tx.body.messages[0].value` with the typeUrl `/cosmos.bank.v1beta1.MsgSend`, which matches how I built the transaction (see below) . I am trying to recover this Uint8Array but after many attempts at decoding, I cant get a value that matches the amount I am sending. Is the object `Coin` in a format I am not noticing? What format is the data under value encoded in? I am receiving at Uint8Array of 108 characters and this is the decoded string `0a2d636f736d6f733136613278687a3265717467376b63333271796a30343366783267797a6765726c306564737876122d636f736d6f73313561707464716d6d376464677463726a7663356873393838726c726b7a6534306c34713068651a0c0a057561746f6d1203313030`.

I am able to build, sign, and post a transaction using the following body, and when posted on the network the data matches what I am putting. I just dont know how to recover that value in body.value.messages[x].amount.

Here is how I build the TxBody and the value I am trying to recover
``` typescript
body = {
	typeUrl: "/cosmos.tx.v1beta1.TxBody",
	value: {
		messages: [{
			typeUrl: "/cosmos.bank.v1beta1.MsgSend",
			value: {
				fromAddress: <address>,
				toAddress: <targetAddr>,
				amount: [...coins(<value>, "uatom")],
			}
		}],
		memo: ""
	}
};
```

**Comment by webmaster128** [comment]
You can debug stuff like this with [decode_raw](https://github.com/confio/decode_raw):

```
$ echo '0a2d636f736d6f733136613278687a3265717467376b63333271796a30343366783267797a6765726c306564737876122d636f736d6f73313561707464716d6d376464677463726a7663356873393838726c726b7a6534306c34713068651a0c0a057561746f6d1203313030' | xxd -r -p | decode_raw --no-fixed
1: (45 bytes) "cosmos16a2xhz2eqtg7kc32qyj043fx2gyzgerl0edsxv"
2: (45 bytes) "cosmos15aptdqmm7ddgtcrjvc5hs988rlrkze40l4q0he"
3 {
· 1: (5 bytes) "uatom"
· 2: (3 bytes) "100"
}
```

**Comment by michaelbarbas** [comment]
I was able to dismantle and reformat the string under typeUrl to grab the data to check. Little hacky but it works, thanks!
