### ISSUE TITLE
Can't Resolve 'utf-8-validate' or 'butterutil' in ws Library

### ISSUE THREAD

**Issue by hackinhikikomori** [cosmos/cosmjs#1350]
Hi, my team recently upgraded our NextJS version to 13.

Since the upgrade, we started getting an error that the `bufferutil` and `utf-8-validate` packages in `ws` cannot resolve. After some investigation, we noticed that the `ws` package is being brought in by `cosmjs/socket`, a dependency of `cosmwasm/stargate`. This seems to have been a problem with [other teams](https://github.com/netlify/netlify-lambda/issues/179) who have used `ws` in the past. As suggested in the aforementioned issue, our team attempted to add the problematic packages to the `externals` in our next config, but to no avail.

Do you have any suggestions on how to fix it, or what may have caused it? I can post some code snippets on request, but I'm not sure what code would be relevant here.

Thanks!

**Comment by webmaster128** [comment]
Both bufferutil and utf-8-validate are optional. So they are not added as dependencies of ws. See https://github.com/websockets/ws/blob/becf237cef8924a765075ecbd45599bc10fb6d18/README.md#opt-in-for-performance. Maybe setting the WS_NO_BUFFER_UTIL and WS_NO_UTF_8_VALIDATE env variables work.

But it is safe to exclude them and make this line throw: https://github.com/websockets/ws/blob/9e0fd77799a0fcf16b8eb2f767358ef8bb834ec8/lib/buffer-util.js#L113

**Comment by hackinhikikomori** [comment]
Thanks @webmaster128 ! So here's the error I'm getting: 
```
Module not found: Can't resolve 'bufferutil' in '/home/user/project/frontend/project-fe/node_modules/ws/lib'
./node_modules/ws/lib/validation.js
Module not found: Can't resolve 'utf-8-validate' in '/home/user/project/frontend/project-fe/node_modules/ws/lib'
```

I attempted to add the environment variables that you suggested, but in the process I realized that my client wasn't able to see the publicRuntimeConfig.  I don't think that your suggestion would work until I remediate that issue. So I'll keep working at it :)

**Comment by webmaster128** [comment]
If you find a way to disable `ws` entirely, that would be easier and probably better. It is only needed for Node.js support. We use `isomorphic-ws` which should give you native WebSocket support in browsers.

**Comment by ahmamedhat** [comment]
I'm getting the same error on Nextjs 13 when trying to install socket-io-client package.

**Comment by ekendra-nz** [comment]
same error with surrealdb_js library

**Comment by romanusname** [comment]
I have this same problem. Were you able to fix it?

**Comment by webmaster128** [comment]
I have no idea. I also use CosmJS in a Next.js 13 project without issue. Feel free to debug the limitations of their various bundler solutions.
