### ISSUE TITLE
Event changes in TM v0.37

### ISSUE THREAD

**Issue by julienrbrt** [cosmos/cosmjs#1353]
The SDK v0.47 upgrades TM to v0.37, which re-surface https://github.com/cosmos/cosmos-sdk/issues/11997.
According to https://github.com/cosmos/cosmos-sdk/issues/11997#issuecomment-1356910154, there is already a TM v0.35 client.

It would be helpful if there is a cosmjs version supporting the event changes in v0.37 (ref: https://github.com/tendermint/tendermint/blob/main/UPGRADING.md#unreleased)

**Comment by garrettparris** [comment]
I am getting the same error with the following stack. same versions as above, using @cosmjs 0.29.5
```
Error: Invalid string. Length must be a multiple of 4
    at getLens (index.js?602a:26:1)
    at Object.toByteArray (index.js?602a:55:1)
    at fromBase64 (base64.js?9836:36:1)
    at decodeAttribute (responses.js?a8ef:45:1)
    at Array.map (<anonymous>)
    at decodeAttributes (responses.js?a8ef:50:1)
    at decodeEvent (responses.js?a8ef:55:1)
    at Array.map (<anonymous>)
    at decodeEvents (responses.js?a8ef:60:1)
    at decodeTxData (responses.js?a8ef:69:1)
    at decodeTxResponse (responses.js?a8ef:319:1)
    at Array.map (<anonymous>)
    at decodeTxSearch (responses.js?a8ef:329:1)
    at decodeTxSearch (responses.js?a8ef:437:1)
    at Tendermint34Client.doCall (tendermint34client.js?7cf7:310:1)
    at async Tendermint34Client.txSearchAll (tendermint34client.js?7cf7:257:1)
    at async StargateClient.txsQuery (stargateclient.js?c525:279:1)
    at async StargateClient.getTx (stargateclient.js?c525:191:1)
    at async pollForTx (stargateclient.js?c525:252:1)
```

**Comment by julienrbrt** [comment]
cc @@pyramation

**Comment by tac0turtle** [comment]
Should we do this ourself, its a blocker for a variety of things

**Comment by webmaster128** [comment]
This particular change was already implemented in the Tendermint 0.35 client last summer. If I understand things correctly, only 0.34 and 0.37 are needed now. So we can rename the 0.35 client to 0.37 and test it against a 0.37 backend.

**Comment by webmaster128** [comment]
Is there a better source for Tendermint 0.37 docker images than `v0.37.0-rc2` from https://hub.docker.com/r/tendermint/tendermint/tags/ that we should use for testing the client?

**Comment by julienrbrt** [comment]
> Is there a better source for Tendermint 0.37 docker images than `v0.37.0-rc2` from [hub.docker.com/r/tendermint/tendermint/tags](https://hub.docker.com/r/tendermint/tendermint/tags/) that we should use for testing the client?

I believe it's there https://hub.docker.com/r/cometbft/cometbft/tags/

**Comment by webmaster128** [comment]
What do you currently need this client for? I think think the standalone client is ready and I can create a StargateClient/CosmWasmClient constructor where you pass an explicit tendermint client (either 34 or 37). The auto-detection would be a bigger thing as the functionality was removed at some point. I don't want to block the client on the auto-detection. Does this make sense?

**Comment by webmaster128** [comment]
#1376 is ready for anyone wants to review it

**Comment by Anmol1696** [comment]
@webmaster128 maybe I am missing something here, but i am running
```
# cosmos-sdk simd
simd version
# 0.47.3
```
CometBFT version `github.com/cometbft/cometbft@v0.37.1`

With @cosmjs/faucet at `v0.30.0` and `v0.30.1`, but still seem to be getting this error:
```
Sending 10000000000 stake from cosmos1dxacpfsesc3h3gznuq4ldtpa0jskdzf7c6z9uy to cosmos1cglefserrv6l3rct7ruuyedm3cxe3ul2nnx4cs ...
Error: Invalid string. Length must be a multiple of 4
    at c (/app/packages/faucet/dist/node/cli.js:2:159563)
    at Object.t.toByteArray (/app/packages/faucet/dist/node/cli.js:2:158637)
    at t.fromBase64 (/app/packages/faucet/dist/node/cli.js:2:2100856)
    at l (/app/packages/faucet/dist/node/cli.js:2:2255810)
    at Array.map (<anonymous>)
    at p (/app/packages/faucet/dist/node/cli.js:2:2255991)
    at Array.map (<anonymous>)
    at A (/app/packages/faucet/dist/node/cli.js:2:2256050)
    at f (/app/packages/faucet/dist/node/cli.js:2:2256218)
    at O (/app/packages/faucet/dist/node/cli.js:2:2261060)
```

My issue is even though there is an error and server returns 500, some of the times the txn seems to go through and the faucet seems to transfer the tokens.

Am I missing something?

**Comment by Anmol1696** [comment]
Actually you can see this in the gist of the logs during initialization itself... Error statement during refil, but refil actually happens

https://gist.github.com/Anmol1696/60b3e851b66fe6d45674dea9b4f92081#file-logs-txt

Maybe it is still some old validatation of address?

**Comment by webmaster128** [comment]
@Anmol1696 you need a pre-release of 0.31 to get the Tendermint 0.37 client by default

**Comment by Anmol1696** [comment]
Ahh yes worked like a charm.
I got confused cuz the changelog mention `v0.30` should have this PR. `v0.31.0-alpha.2` works with `simd v0.47.3`

**Comment by webmaster128** [comment]
0.30 ships a standalone Tendermint 0.37 client that you can use manually. From 0.31 onwards we have auto-detection in higher level clients and use it by default under the hood. Fianal release very very soon.

**Comment by Anmol1696** [comment]
Error re-occurs for cosmos-sdk version 50 as well. Does support for TM 0.38 also need some changes? 
@webmaster128 Is there a way in which adding TM support is easier?

I am using cosmjs-facuet for running simd nodes with Starship. It would be nice if cosmos-sdk can be tested with cosmjs (but hard to do if there are too many breaking changes).

**Comment by webmaster128** [comment]
> It would be nice if cosmos-sdk can be tested with cosmjs (but hard to do if there are too many breaking changes).

This idea has been around for a while but CosmJS does not have the necessary development resources to keep up with Cosmos SDK development. Trying to test Cosmos SDK with an independent re-implementation creates dependency cycles that are very hard to maintain.
