### ISSUE TITLE
Export default aminoConverters

### ISSUE THREAD

**Issue by xpt1x** [cosmos/cosmjs#1362]
Suggestion to export default `aminoConverters` object similar to `defaultRegistryTypes` as a `const`
https://github.com/cosmos/cosmjs/blob/33271bc51cdc865cadb647a1b7ab55d873637f39/packages/stargate/src/signingstargateclient.ts#L96-L105

**Comment by webmaster128** [comment]
I see. The individual entries are public already. But we could export the whole thing.

Do you want to create a PR? Rename to `createDefaultAminoConverters` and make it public?

**Comment by xpt1x** [comment]
Sure, will create a PR for this
It is required when someone wants to support custom converters along with cosmos's default. Directly passing custom converters in `SigningStargateClientOptions` will override default converters

**Comment by webmaster128** [comment]
This was done in https://github.com/cosmos/cosmjs/pull/1385 and released as part of 0.30.0.
