### ISSUE TITLE
ParameterChangeProposal

### ISSUE THREAD

**Issue by PFC-developer** [cosmos/cosmjs#1366]
hi!.
so I am trying to create a proposal (on osmo-test-4), and have struct an issue.
when I try to submit a change 

[{"subspace":"staking","key":"UnbondingTime","value":"172800000000000"}]

it responds with
`
queryclient.js?0f47:135 Uncaught (in promise) Error: Query failed with (18): failed to execute message; message index: 0: key: UnbondingTime, value: 172800000000000, err: invalid character -- Amino:JSON int/int64/uint/uint64 expects quoted values for javascript numeric support, got: 172800000000000.: failed to set parameter: invalid proposal content: invalid request`

I am creating the field ala
    value = ParameterChangeProposal.encode(
        ParameterChangeProposal.fromPartial(p)
      ).finish();

now strangely.. if I add the value to "172800000000000"
the system accepts it,
but results in a weird proposal - https://testnet.mintscan.io/osmosis-testnet/proposals/57040

**Comment by webmaster128** [comment]
What exactly do you try to do? Only the Amino JSON representation uses JSON as far as I can tell. But in CosmJS no Amino JSON for this proposal type is implemented:
https://github.com/cosmos/cosmjs/blob/94d6583f3bba83f270a022d273dee5335947bedc/packages/stargate/src/modules/gov/aminomessages.ts#L168-L195

**Comment by PFC-developer** [comment]
I'm closing this, as it could just be that It is expecting a UInt128 (string), not a number for this parameter.

a successful one looks fine here 

TX - https://validator.tools/tx/osmo-test-4/A88F10992E979E1CBF50AC0DCBF58D16D28D2BD7AB3C3E48E07D2975FD75BBE3
