### ISSUE TITLE
Amino encode not support some special char(<, >, $).

### ISSUE THREAD

**Issue by loin3** [cosmos/cosmjs#1367]
When Tx memo contain special characters (<, >, $), Amino sign does not working

Step1. Write Tx with memo within special char. ex) "Tx & Send"
Step2. Sign with Secp256k1HdWallet

`signature verification failed; please verify account number (1), sequence (7) and chain-id (simd-testing): unauthorized`

**Comment by loin3** [comment]
keplr-wallet already dealt with this problem, but did not contributed to cosmjs.
https://github.com/chainapsis/keplr-wallet/blob/master/packages/common/src/escape/index.ts#L8

**Comment by webmaster128** [comment]
Very interesting, thank you for bringing this up. This is indeed not yet implemented.

The Keplr reference is great and helpful.

https://go.dev/play/p/p3RNTpm2LED shows the escaping bahaviour in Go.
