### ISSUE TITLE
How to sign tx with Metamask

### ISSUE THREAD

**Issue by ybgbob** [cosmos/cosmjs#1368]
I'm developing a DApp on Cosmos. 

I find all of api in `cosmjs` must use wallet by mnemonic or private key. But DApp runs on browser, how to use this SDK?

MetaMask can't get private key or mnemonic.

**Comment by xpt1x** [comment]
If u want to sign cosmos txs, u can't do it with metamask, you need to sign them with cosmos wallet or wallet providers (ex. keplr, cosmostation, leap) 

`Cosmjs` provide creation of a `signer wallet` from mnemonic using:
```ts
DirectSecp256k1HdWallet.fromMnemonic(mnemonic)
```
With this, u get a `signer` that can be connected to `cosmj's SigningStargateClient` and can be used then.. to sign transactions with this `signer` that we created above

Or you need to get `signer` from providers like keplr/cosmostation as they already take care of creating signer from your mnemonic, so they provide u with `signer` if u call their api for getting one and then connect it similarly to `SigningStargateClient` and use it

Example 1: https://gist.github.com/webmaster128/8444d42a7eceeda2544c8a59fbd7e1d9#send-your-first-stargate-transaction-from-javascript

Example 2 (keplr): https://docs.keplr.app/api/cosmjs.html#connecting-with-cosmjs

And as i don't know what you are doing but if your app somehow wants to sign tx with metamask, then it should be metamask supported transaction (Cosmos is not EVM compatible, so not supported on metamask) and hence this library can't help u with that, try finding ur choice here: https://docs.metamask.io/guide/getting-started.html#choosing-a-convenience-library

**Comment by ybgbob** [comment]
@xpt1x Thank you.
