### ISSUE TITLE
SearchTx timeouts

### ISSUE THREAD

**Issue by dimiandre** [cosmos/cosmjs#1415]
I'm trying to search a CreateValidator Tx

With the current code, the HTTP request always timeout or get socket hang up
```javascript
        let client = await StargateClient.connect("https://rpc-juno.mib.tech")

        let txs = await client.searchTx({
            tags: [{ key: "create_validator.validator", value: "junovaloper1hvhyunq7qvykzvrcnhjj4xnkcla58xusk6r60g" }],
        });
```
errors

cloudflare proxy
```
(node:11661) UnhandledPromiseRejectionWarning: Error: Request failed with status code 502
```

direct tcp
```
(node:11835) UnhandledPromiseRejectionWarning: Error: socket hang up
```

Using Juno CLI to query instead is always almost instant 
``` junod q txs --events create_validator.validator=junovaloper1hvhyunq7qvykzvrcnhjj4xnkcla58xusk6r60g```

that made me wonder why, so I did some logs and I notice some differences between the RPC call made by cosmjs and the one made from CLI

CosmJS:
```
{
  jsonrpc: '2.0',
  id: 483169536733,
  method: 'tx_search',
  params: {
    query: "create_validator.validator='junovaloper1hvhyunq7qvykzvrcnhjj4xnkcla58xusk6r60g' AND tx.height>=0 AND tx.height<=9007199254740991",
    page: '1'
  }
}
```

CLI:
```
{
  jsonrpc: '2.0',
  id: 0,
  method: 'tx_search',
  params: {
    order_by: '',
    page: '1',
    per_page: '30',
    prove: true,
    query: "create_validator.validator='junovaloper1hvhyunq7qvykzvrcnhjj4xnkcla58xusk6r60g'"
  }
}
```

The default value for max tx.height is too high! By manually setting it in fact the 502 error is gone

```javascript
       let client = await StargateClient.connect("https://rpc-juno.mib.tech")

        let txs = await client.searchTx({
            tags: [{ key: "create_validator.validator", value: "junovaloper1hvhyunq7qvykzvrcnhjj4xnkcla58xusk6r60g" }],
        }, { maxHeight: 8027955})
        
        // all good 
```
        
        
I think we should entirely remove height filters if not specified

**Comment by dimiandre** [comment]
Additional note, this example code is super quick (<100 ms per query)


```javascript

let response = await axios.post("https://rpc-juno.mib.tech/", {
            jsonrpc: "2.0",
            id: 0,
            method: 'tx_search',
            params: {
                query: `create_validator.validator='${val.operator_address}'`,
                page: "1"
            }
        })
        ```

**Comment by webmaster128** [comment]
Thank you for debugging this. This sounds like a Tendermint bug to me then. Why should an additional numeric filter cause such a behaviour?

**Comment by dimiandre** [comment]
> Thank you for debugging this. This sounds like a Tendermint bug to me then. Why should an additional numeric filter cause such a behaviour?

that's a good question, I'll try to dig more into this

**Comment by webmaster128** [comment]
I think the current abstraction level of searchTx is unsustainable anyways. I am considering to replace it with a much lower level version that avoids this sort of magic.
