### ISSUE TITLE
Golang for cosmjs

### ISSUE THREAD

**Issue by mhstom** [cosmos/cosmjs#1422]
Hello!

I am building a golang app and trying to parse the TxRaw from cosmos transaction and found this post 
https://github.com/cosmos/cosmjs/issues/879

I am wondering if there's any Golang support for it?

Thanks in advance!

**Comment by webmaster128** [comment]
There should be code in cosmos-sdk to decode `TxRaw`. But I don't know to what degree this is exposed. In any case, nothing CosmJS can do.
