### ISSUE TITLE
Missing earliest block in RPC sync info

### ISSUE THREAD

**Issue by livthomas** [cosmos/cosmjs#1448]
Cosmjs only parses the following fields from `sync_info` record returned by `/status` RPC method:

- catching_up
- latest_app_hash
- latest_block_hash
- latest_block_height
- latest_block_time

But there are also other fields present in `sync_info` which are not processed by cosmjs:

- earliest_app_hash
- earliest_block_hash
- earliest_block_height
- earliest_block_time

# Steps to Reproduce

1. Try to hit `/status` endpoint on any public RPC node (e.g. https://cosmos-rpc.rockrpc.net/status).
2. See what fields are returned within `result.sync_info`.
3. Look at `RpcSyncInfo` interface in both [tendermint34](https://github.com/cosmos/cosmjs/blob/21d150e7a101db5ae2e4542acc94ff5382f7f7c1/packages/tendermint-rpc/src/tendermint34/adaptor/responses.ts#L621-L629) and [tendermint37](https://github.com/cosmos/cosmjs/blob/21d150e7a101db5ae2e4542acc94ff5382f7f7c1/packages/tendermint-rpc/src/tendermint37/adaptor/responses.ts#L622-L630) adaptors.

**Comment by livthomas** [comment]
Yes, I'm already working on it.

**Comment by webmaster128** [comment]
Done in #1449
