### ISSUE TITLE
`cosmwasm-stargate` does not support parsing of `tx` data for the latest `wasmd`.

### ISSUE THREAD

**Issue by 99Kies** [cosmos/cosmjs#1452]
![image](https://github.com/cosmos/cosmjs/assets/45918704/f427e246-8b83-4412-9656-55ee24a9bef4)

https://github.com/cosmos/cosmjs/tree/main/packages/cosmwasm-stargate
https://github.com/CosmWasm/wasmd

**Comment by Unique-Divine** [comment]
The latest version of wasmd uses Cosmos SDK v0.47 and thus cometbft v0.37 (replacement for the Tendermint dependency). 

Based on the error above, you may be using the `Tendermint34Client`. I recommend trying out the `Tendermint37Client` instead.  It passes the e2e tests for cosmjs, which run against wasmd, so it should fix the problem.

**Comment by 99Kies** [comment]
@Unique-Divine Transactions can be successfully sent and processed by the chain. But the processing result of the transaction is not returned.

**Comment by webmaster128** [comment]
The high level clients have Tendermint 0.34/0.37 auto-detection in CosmJS 0.31+ which solve the issue
