### ISSUE TITLE
AminoMsgTransfer is not supporting Memo of the message

### ISSUE THREAD

**Issue by csplr** [cosmos/cosmjs#1461]
Can it be that the AminoMsgTransfer is not supporting the Memo field of the message?

https://github.com/cosmos/cosmjs/blob/358260bff71c9d3e7ad6644fcf64dc00325cdfb9/packages/stargate/src/modules/ibc/aminomessages.ts#L18

When the OfflineAminoSigner is used for example with a Ledger device, where in the Transfer Msg we also want to send a memo field, the memo gets discarded

**Comment by webmaster128** [comment]
Right, thanks for brining this up. The fix is here: https://github.com/cosmos/cosmjs/pull/1456

**Comment by M-Picco** [comment]
@webmaster128 Any chance of getting the mentioned fix merged? I've run into some issues with Ledger on both Keplr and Leap and I think this missing field in the encoding may be the root cause.

I noticed the PR has been inactive for some time. Need it be I can fork it and open a new PR.

**Comment by webmaster128** [comment]
Right, let's wait a day or two for Shane. Otherwise I can create a new branch and merge it.
