### ISSUE TITLE
Support for cosmos-sdk v0.50, TM 0.38

### ISSUE THREAD

**Issue by Anmol1696** [cosmos/cosmjs#1464]
## Overview
Pre-release out for [cosmos-sdk version v0.50](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.50.0-beta.0), it would be really helpful if we can start adding support for TM 0.38 which will be used.

**Comment by webmaster128** [comment]
In https://github.com/cosmos/cosmjs/pull/1466 I tried using the Tendermint 0.37 client for Comet BFT 0.38. But this does not seem to work. We need a separate 0.38 client. Once we have that, we can easily adapt the auto-detection.

**Comment by Anmol1696** [comment]
Would it be similar to #1376?

**Comment by webmaster128** [comment]
What needs to be done is this:
1. Copy and commit the `tendermint37` folder and `Tendermint37Client` into `tendermint38` and `Tendermint38Client`. The diff should only be renamings here.
2. Test the new client against the 0.38 backend (set up in #1466)
3. Make all changes required to make tests pass
4. Adapt the auto-selection in the higher level clients
