### ISSUE TITLE
Error: Invalid string. Length must be a multiple of 4

### ISSUE THREAD

**Issue by dillu24** [cosmos/cosmjs#1482]
Hi,

I am currently using telescope version `v0.102.0` to generate a client with an underlying `v0.31.1` of CosmJS for a custom chain running on Cosmos SDK version for a v0.47. At the moment, when I am submitting a custom TX I am getting the following error returned by `signAndBroadcast`:

`Error: Invalid string. Length must be a multiple of 4`, however, the TX is still going through.`

code generating the error:

```
const broadcast = await this._client.signAndBroadcast(
        depositor,
        [msg],
        1.5 // To use fee on auto mode: prefix and gas price needs to be defined before
      );
```

Any idea of what might be the issue?

**Comment by dillu24** [comment]
Actually I think I found the issue. Tendermint version is hidden inside the node RPC, so, it cannot connect with `Tendermint37Client`

**Comment by webmaster128** [comment]
Why/how is the version hidden?

You can create the Tendermint37Client client manually and pass it to SigningStargateClient/SigningCosmWasmClient to bypass auto-detection if needed.
