### ISSUE TITLE
Does recieving Transaction result means tx block is mined?

### ISSUE THREAD

**Issue by dovigod** [cosmos/cosmjs#1485]
I'm currently developing on SEI network which is based on cosmos.

While developing , I found some difference with ethereum, that after sending coin, It gives response like below,

`code
: 
0
events
: 
(10) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
gasUsed
: 
81544
gasWanted
: 
100000
height
: 
40186186
rawLog
: 
"[{\"events\":[{\"type\":\"coin_received\",\"attributes\":[{\"key\":\"receiver\",\"value\":\"sei1svp0rxm0nwsesmf8ydec5h3g52feqx8lzkksvx\"},{\"key\":\"amount\",\"value\":\"100000usei\"}]},{\"type\":\"coin_spent\",\"attributes\":[{\"key\":\"spender\",\"value\":\"sei1tez8km0fmk72g4urr4jg20p7jv8ulnz056r2a8\"},{\"key\":\"amount\",\"value\":\"100000usei\"}]},{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"/cosmos.bank.v1beta1.MsgSend\"},{\"key\":\"sender\",\"value\":\"sei1tez8km0fmk72g4urr4jg20p7jv8ulnz056r2a8\"},{\"key\":\"module\",\"value\":\"bank\"}]},{\"type\":\"transfer\",\"attributes\":[{\"key\":\"recipient\",\"value\":\"sei1svp0rxm0nwsesmf8ydec5h3g52feqx8lzkksvx\"},{\"key\":\"sender\",\"value\":\"sei1tez8km0fmk72g4urr4jg20p7jv8ulnz056r2a8\"},{\"key\":\"amount\",\"value\":\"100000usei\"}]}]}]"
transactionHash
: 
"98C5D72519DCE30D9853AAC43BA1B98A5899EC6BC07BB166FB51C42E4584D5D4"`

I found that property 'height' is the block number which this transaction is in.

Just to induce, since response throws 'block number which tx is held', can I assert that 'transaction response will only returned when transaction is mined?

**Comment by webmaster128** [comment]
I don't know exactly what you do and don't know what _block number which tx is held_ is. But in general there are two thinks to look for: If the transaction result has a height, then it is included in a block. If code == 0, then the transaction was successful. If code != 0, then the transaction was unsuccessful and is reverted.

**Comment by dovigod** [comment]
@webmaster128 Ah exactly what I was questioning! Thanks! Sorry for the ethereum friendly terms :(
