### ISSUE TITLE
@cosmjs/tendermint-rpc - Suddenly getting error after broadcastTx->decodeTx "Error: Invalid string. Length must be a multiple of 4"

### ISSUE THREAD

**Issue by chasevoorhees** [cosmos/cosmjs#1517]
![image](https://github.com/cosmos/cosmjs/assets/26911704/870d913e-ea0f-47ca-a67a-e4449c5ab1c8)
"@cosmjs/tendermint-rpc": "^0.31.3",
"@cosmjs/tendermint-rpc": "^0.32.1",

This just started happening a couple days ago. Have tested with a few versions now.

The transaction signs/broadcasts successfully, then this happens when the TX is parsed back in
Going through the events:
fromBase64('spender')
ends up getting called with the event key 'spender' for some reason.

This is the offending file:
node_modules/osmojs/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptor/responses.js

![image](https://github.com/cosmos/cosmjs/assets/26911704/b0379549-6698-488e-8814-096ae69e4ec9)
![image](https://github.com/cosmos/cosmjs/assets/26911704/9c9358ec-3b5e-410b-9b55-5746ea56f716)

I'll look into this more tomorrow but hope someone else has encountered this/might have an idea.

**Comment by webmaster128** [comment]
Osmosis testnet was upgraded to Cosmos SDK 0.47 as far as I can tell. In that case, using the Tendermint34Client won't work anymore. You need the Tendermint37Client. Can you report this to osmojs where those things are defined?

**Comment by chasevoorhees** [comment]
> Osmosis testnet was upgraded to Cosmos SDK 0.47 as far as I can tell. In that case, using the Tendermint34Client won't work anymore. You need the Tendermint37Client. Can you report this to osmojs where those things are defined?

Thanks for this. 
Does this also apply to Osmosis mainnet, or is there a date set for that? 

I've opened an [issue](https://github.com/osmosis-labs/osmojs/issues/71) with their repo

**Comment by webmaster128** [comment]
Let's further discuss this on the Osmosis repo. Cheers!
