### ISSUE TITLE
rawLog is deprecated

### ISSUE THREAD

**Issue by pynixwang** [cosmos/cosmjs#1562]
https://github.com/cosmos/cosmjs/blob/11ce1223f0fb4ccb6f50f52bccec673e36adca52/packages/cosmwasm-stargate/src/signingcosmwasmclient.ts#L291C1-L292C1

this not works when sdk >= v50

**Comment by webmaster128** [comment]
Yeah, right, thanks. In this file all usages of `.rawLog` need to be replaces with looking into `.events` instead. Want to create a PR for the fix?

**Comment by pynixwang** [comment]
#1563
