### ISSUE TITLE
@cosmjs/encoding/build/utf8.d.ts:1:1 - error TS1490: File appears to be binary.

### ISSUE THREAD

**Issue by burtonator** [cosmos/cosmjs#1573]
I'm getting this error building with Typescript > 5.0.

I don't always get it which is weird but it just happened when I upgraded some packages. Not sure why.

Note that this file does appear to have an invalid character and once I remove it then it works fine.

**Comment by webmaster128** [comment]
This was fixed here and deployed in the last patch release: https://github.com/cosmos/cosmjs/pull/1570

Could you check if that solves it for you?

**Comment by HS-Joe** [comment]
Hey @webmaster128 i can confirm the issue is fixed using `"@cosmjs/encoding": "0.32.3"`

**Comment by webmaster128** [comment]
Thanks
