### ISSUE TITLE
I can’t write a script for the evm-cosmos network (for example Evmos)

### ISSUE THREAD

**Issue by SatoshiMota** [cosmos/cosmjs#1576]
I’ve been trying to write for 5 days and it’s not working, can someone tell me how to delegate tokens to a validator from a seed phrase? "/ethermint.types.v1.EthAccount"

send your wallet along with the code (I’ll throw off $100 if the code helps)

**Comment by webmaster128** [comment]
Not supported in CosmJS (https://github.com/cosmos/cosmjs/issues/1351)
