### ISSUE TITLE
Is `MultiSend` method  suppored?

### ISSUE THREAD

**Issue by ikeda-minden** [cosmos/cosmjs#1605]
Is `MultiSend` method  suppored?
Or do I need to create some custom interface for `MultiSend`?

**Comment by DavideSegullo** [comment]
Seems like it's supported: https://github.com/cosmos/cosmjs/blob/main/packages/stargate/src/modules/bank/messages.ts#L4

You can use `cosmjs-types` to build a msg:

```ts
import { MsgMultiSend, MsgSend } from "cosmjs-types/cosmos/bank/v1beta1/tx";

MsgMultiSend.fromPartial({
  ...
})
```

Or you can also use other lib like `osmojs`:

```ts
import { cosmos } from "osmojs";

cosmos.bank.v1beta1.MessageComposer.withTypeUrl.multiSend({
  ...
})
```

**Comment by DavideSegullo** [comment]
@ikeda-minden If it's fine, can you close this issue?
