### ISSUE TITLE
Make message class more concrete

### ISSUE THREAD

**Issue by Thunnini** [cosmos/cosmjs#283]
It seems that the current implementation of cosmjs is using an interface to define message type of cosmos-sdk and the interface is based on JSON structure. https://github.com/CosmWasm/cosmjs/blob/master/packages/sdk38/src/msgs.ts#L9

And, it mixes the snake case coding style and also camel case at the same time.

I suggest using an abstract class for messages such as
```
export abstract class Msg {
  /**
   * ValidateBasic does a simple validation check that
   * doesn't require access to any other information.
   * You can throw error in this when msg is invalid.
   */
  public abstract validateBasic(): void;
  /**
   * Get the canonical byte representation of the Msg.
   * @return Return sorted by alphabetically amino encoded json by default.
   */
  public getSignBytes(codec: Codec): Uint8Array {
    return Buffer.from(sortJSON(codec.marshalJson(this)), "utf8");
  }
  public getSigners(): AccAddress[] {
    throw new Error("You should implement getSigners()");
  }
}
```
https://github.com/chainapsis/cosmosjs/blob/master/src/core/tx.ts#L17
And, messages can be validated before broadcasting tx by using validateBasic().

A custom message can be defined as https://github.com/chainapsis/cosmosjs/blob/master/src/x/bank/msgs.ts#L8.

[CosmosJS](https://github.com/chainapsis/cosmosjs) uses tendermint rpc to broadcast tx by encoding tx to raw bytes.
Since cosmJS uses rest api and tx should be encoded to JSON, I think encoding the object to JSON using ts-amino should work, although more testing needs to be done in this area.

Additionally, I would suggest making a modular tx builder which receives tx interface rather than stdTx. In the cosmos ecosystem, chains can use different tx structure. So, I think that we should be able to handle such cases.

So, I think it would be optimal that CosmosClient class accepts custom tx builder. Rather than using stdTx for tx related API like [this](https://github.com/CosmWasm/cosmjs/blob/master/packages/sdk38/src/cosmosclient.ts#L292), it will be better to receive the tx interface and use the tx builder to create a defined transaction.

**Comment by webmaster128** [comment]
We have most of what you suggest working for the upcoming protobuf transaction encoding in @cosmjs/sdk39.

All Cosmos SDK 0.38 code talks to the [LCD API](https://cosmos.network/rpc/v0.38.3), which takes JSON transactions and encodes them to Amino for us. This is the only reason why there are snake_case property names in messages. It is the original Amino-JSON representation. This is far from ideal, but writing an production ready Amino encoder/decoder at this point seems to be a waste of resources.

**Comment by webmaster128** [comment]
For the Launchpad/Amino backends we'll stick to JSON structures that use the casing of the backend. This is not beautiful but practical. The overhead of creating annotated classes is something we want to avoid for soon-legazy code.

For protobuf we can rename the fields locally without breaking compatibility to the backend (but then legazy Amino signing comes in and is the party pooper).
