### ISSUE TITLE
Upgrade to yarn2

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#301]
I never tried it but it seems like yarn1 is more or less unmaintained and all development effort goes into yarn2.

**Comment by willclarktech** [comment]
Migration guide here: https://yarnpkg.com/advanced/migration

**Comment by willclarktech** [comment]
We might be able to use the JS API to skip installing the unused dev dependencies of the `launchpad-ledger` package on CI. C.f. https://github.com/CosmWasm/cosmjs/commit/27e0273390956e4362b64c7d6c48214f99f959fd

**Comment by webmaster128** [comment]
Yarn v1 is practically unmaintained. I think it is time to leave the sinking ship.

**Comment by ethanfrey** [comment]
When you do migrate, please leave a helpful guide for dApps, ts-relayer and more.
Maybe you could even try it on a simpler repo with fewer workspaces first?
