### ISSUE TITLE
Figure out how to use proto.Any registry

### ISSUE THREAD

**Issue by ethanfrey** [cosmos/cosmjs#393]
See https://github.com/cosmos/cosmos-sdk/pull/6722

We need to:

1. Figure out how to set up an registry of type names <-> classes lookup (I think some of this is done with decorators)
2. See if this endpoint let's us properly decode the Any items.

**Comment by willclarktech** [comment]
@webmaster128 I believe this is already done. Is there anything else that's needed for this issue?

**Comment by ethanfrey** [comment]
@willclarktech Simon is off today. If you link me to the usage of the code, I can confirm if it is done or ask any follow up questions.

This is about parsing something that comes wrapped in Any - allowing us to no longer hard-code BaseAccount when parsing the proto.Any that stores an account. You can link me to that parse code and I can give feedback there.

**Comment by ethanfrey** [comment]
Ah, I see the #354 issue on the above. I would not close this issue until that works with a general solution.
(You can solve that issue with a much simpler solution than a general registry)

**Comment by willclarktech** [comment]
@ethanfrey I was thinking of this: https://github.com/cosmos/cosmjs/blob/master/packages/proto-signing/src/magic.spec.ts

**Comment by ethanfrey** [comment]
Interesting.

So, this allows us to use a registry to explicitly encode some fields with an any type (to proto.Any) and later decode that proto.Any into the original type: https://github.com/cosmos/cosmjs/blob/master/packages/proto-signing/src/magic.spec.ts#L62-L70

So the `Registry` object is required for all `proto.Any` encoding/decoding, but not needed when we encode/decoded concrete types without `proto.Any`. Correct? (The SDK also has a semi-global registry of all types to handle Any encoding/decoding).

**Comment by ethanfrey** [comment]
I think we can close this as well. Thanks for linking me the solution

**Comment by willclarktech** [comment]
> So the Registry object is required for all proto.Any encoding/decoding, but not needed when we encode/decoded concrete types without proto.Any. Correct?
@ethanfrey Yep!
