### ISSUE TITLE
Add Support for Staking Related Queries

### ISSUE THREAD

**Issue by ethanfrey** [cosmos/cosmjs#419]
`@cosmjs/launchpad/CosmosClient` and `@cosmjs/cosmwasm/CosmWasmClient` expose auth and bank by default. With the cw20 wallet https://github.com/CosmWasm/dApps/issues/34 we will need to query the state of validators from the UI. The code is all there, just not exposes in the client.

* Please expose the StakingQueries in the high-level clients
* See if there are other common packages that make sense to expose as well.

@webmaster128 I would love this in a 0.23 release in the next 1-2 weeks (so the cw20 wallet can be finished in 3 weeks)

**Comment by webmaster128** [comment]
Can you use the `LcdClient` instead?

```ts
import { LcdClient, StakingExtension, setupStakingExtension } from "@cosmjs/launchpad";

function makeStakingClient(apiUrl: string): LcdClient & StakingExtension {
  return LcdClient.withExtensions({ apiUrl }, setupStakingExtension);
}

const lcdClient = makeStakingClient(wasmd.endpoint);
const response = await lcdClient.staking.validators();
```

Otherwise we'd blow up `CosmosClient`/`CosmWasmClient` by adding more and more and more which does not do anything else than passing calls to the `LcdClient`.

**Comment by ethanfrey** [comment]
@abefernan Can you try the above code when you come to it. If it ends up unergonomic to have a `SigningCosmWasmClient` and an `LcdClient` or some code is too verbose, try to make some helpers for it and suggestions on the API. For now, this seems like the simplest solution.
