### ISSUE TITLE
Convert cosmwasm client responses to camelcase

### ISSUE THREAD

**Issue by willclarktech** [cosmos/cosmjs#469]
See eg https://github.com/CosmWasm/dApps/pull/45/files#diff-12cbe2959028baa478997eba8f3570fbee88941a61e68027898ca70b660c0183

It would be nicer to give the front end a consistent naming style.

**Comment by ethanfrey** [comment]
Wait, you want to modify the json that the contract returned?
The same would apply with the messages sent to contracts.

We can change cases of stuff in some fixed rpc - like tendermint - but should not change anything dynamically (app format).

If this is desired, we change the contract formats (which may be different in every contract - defined in wasm). You can raise an issue on cosmwasm to use [serde camelCase encoding](https://serde.rs/attr-rename.html). But please do not modify the return value between the contract and the caller - that can get weird when you write the contract and the ui and it just changes on you.
