### ISSUE TITLE
Use tagged version of simapp docker image

### ISSUE THREAD

**Issue by willclarktech** [cosmos/cosmjs#475]
Currently we use nightly builds but when tagged releases are available we should use them.

See https://discord.com/channels/669268347736686612/669274997264613376/765926942674911233

**Comment by ethanfrey** [comment]
Docker images for all tags, and nightly builds off the 0.40.x branch are coming: https://github.com/cosmos/cosmos-sdk/pull/7617

**Comment by ethanfrey** [comment]
This one will take a while.

For now, please use [`confio/simapp:v0.40.0-rc1`](https://hub.docker.com/r/confio/simapp/tags) and ensure it works (same commit we use in wasmd). There should be a bigger rc2 release later this week and I will make an update issue for that when ready. But I have much more faith building on a tagged rc than a nightly build

**Comment by willclarktech** [comment]
@ethanfrey How confident are you the rc2 release will happen this week? I'm not sure there's any value in updating now if we're just going to update again in a few days.

**Comment by ethanfrey** [comment]
This should be a hopefully minimal/noop update. But ensures the current master works with any deployed network. If this update can happen with < 1 hour dev time, I would like to see it done so we can feel better publishing this repo (all stargate work is using this).

We can do rc2 within a wek or it's release. And watching progress and more and more added, I am doubtful it will fit this week
