### ISSUE TITLE
Add support for x/wasm messages in stargate

### ISSUE THREAD

**Issue by ethanfrey** [cosmos/cosmjs#491]
Requires: tagged version of wasmd (https://github.com/CosmWasm/wasmd/pull/293)

Helpful: Test against `simapp` `v0.40.0-rc1` first (https://github.com/cosmos/cosmjs/issues/475)

Let's provide the same support as we have in launchpad. This may switch cosmwasm package to only support starport (wasmd 0.12) or it may add a second cosmwasm package with starport (wasmd 0.12) support while maintaining the launchpad version.

**Comment by webmaster128** [comment]
Let's create a private `@cosmjs/cosmwasm-stargate` package that we develop to the point where we are happy with it. Then we can rename `cosmwasm` -> `cosmwasm-launchpad` and `cosmwasm-stargate` to `cosmwasm` and decide if and how long we want to maintain the old one.

**Comment by ethanfrey** [comment]
cosmwasm/wasmd:v0.12.0-alpha1` is now published and available with `docker pull` .

This should be drop-in compatible with `confio/simapp:v0.40.0-rc1` for bank/staking/ibc modules (please test this if we need to bugfix on the wasmd side). It also exposes a number of new protobuf message types and grpc queries for `x/wasm`. 

Adding these would not only be great for actually providing us dApp clients on 0.12, but also to help define a workflow that allows us to add non-simapp (cosmos-sdk repo) messages and queries for a client.

**Comment by webmaster128** [comment]
#515 should be done first

**Comment by webmaster128** [comment]
https://github.com/cosmos/cosmjs/issues/524 should be done first

**Comment by willclarktech** [comment]
To-do list:

- [x] Prepare `cosmwasm` package
- [x] Prepare `stargate` package
- [x] Prepare `wasmd` scripts
- [ ] Add basic `cosmwasm-stargate` package eg `CosmWasmClient` and `SigningCosmWasmClient` #571 
- [ ] Add full `searchTx` functionality and tests
- [ ] Add verified queries?

**Comment by webmaster128** [comment]
What about this:
1. Rename @cosmjs/cosmwasm to @cosmjs/cosmwasm-launchpad
1. Create a new wrapper @cosmjs/cosmwasm around @cosmjs/cosmwasm-launchpad, which re-exports everything
1. Publish @cosmjs/cosmwasm with a deprecation warning "This package has been renamed to @cosmjs/cosmwasm-launchpad"
1. Wait a release or two
1. Remove all symbols from @cosmjs/cosmwasm to break user's applications
1. Wait a release or two
1. Rename @cosmjs/cosmwasm-stargate to @cosmjs/cosmwasm

**Comment by willclarktech** [comment]
@webmaster128 Re point 7: do we actually want to rename it, or just re-export everything so we don't have to go through the entire process again with whatever comes after Stargate?

**Comment by webmaster128** [comment]
@willclarktech Not sure. I think everything after point 5 is open for discussion along the way.

**Comment by willclarktech** [comment]
@webmaster128 OK to close this and use other issues for the rest of the package renaming/verified queries? I already added this one: https://github.com/cosmos/cosmjs/issues/583

**Comment by webmaster128** [comment]
Sure, great job!
