### ISSUE TITLE
Review IBC queries, create test data and improve testing

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#494]
In `packages/stargate/src/queries/ibc.spec.ts` we test Stargate IBC queries. However, the testing is very minimal because when we wrote them, we were not able to generate proper test fixtures.

The 6 `expect(response).toBeTruthy(); // TODO: implement checks` should be replaced with tests that check the data.

There was work from Alex and Ethan to generate test data (https://github.com/cosmos/cosmjs/pull/405 and https://github.com/cosmos/cosmjs/pull/406). Let's try to update this work.

Once we have the [IbcExtension](https://github.com/cosmos/cosmjs/blob/master/packages/stargate/src/queries/ibc.ts) tested, I assume we have everything we need for an IBC visualizer data source.

**Comment by ethanfrey** [comment]
Let's not use those linked prs. Data format is also changing we need simapp v0.40.0-rc2

We can provide test vectors when that is ready

**Comment by ethanfrey** [comment]
@willclarktech @webmaster128 

Here is my brief into as to what concepts are needed for the relayer:

`Client/connection` - are almost always 1:1 and refer to headers of another chain (to probe that something came from there). Let's list connections and each can "show details" for full client (in theory there can be multiple connections per client but I have not heard 1 example when this would be in reality, still listing connections means we would support it)

`Port` - each module/contract can bind onto a port. This is similar to TCP, but the same port is used for both sending and receiving.

`Channel` -  this is where information is sent. It involves a handshake between (connection, port) pair (one on each chain) and the channel gets it's own ID. (these ids are unique per connection)

`Packet` - this is a message sent over a channel and will be processed by an app on the other side. For ICS20 this packets says "move x tokens from me to you". There is an ack, which contains a result (success) or error, so the sender know if the money should be refunded locally when it fails

----

I have created https://github.com/CosmWasm/dApps/issues/61 to show the general workflow (3-4 pages we need to show). Here are the key queries (from the protobuf files) that we need working:

Connections:

`rpc Connections(QueryConnectionsRequest) returns (QueryConnectionsResponse)` - includes connection_id, client_id, state

Clients:

`rpc ClientState(QueryClientStateRequest) returns (QueryClientStateResponse)` - includes `google.protobuf.Any client_state`, which we should be able to parse. Currently defined client types are "tendermint", "localhost" and "solo_machine" (not sure where these are defined in code)

`rpc ConsensusStates(QueryConsensusStatesRequest) returns (QueryConsensusStatesResponse)` - returns all "consensus states" for this client - this is like a tendermint header or a solo machine pubkey. We need to figure out the concrete versions and parse them.

Channels:

`rpc ConnectionChannels(QueryConnectionChannelsRequest) returns (QueryConnectionChannelsResponse)`- given a connection, returns all `(channel_id, port_id)` pairs (local id) along with their counterparties and state

`rpc PacketCommitments(QueryPacketCommitmentsRequest) returns (QueryPacketCommitmentsResponse)` - lists all packet commitments for this channel

**Comment by ethanfrey** [comment]
Here is the go relayer: https://github.com/cosmos/relayer 

There are some scripts to set up a multiple chains for testing: https://github.com/cosmos/relayer/blob/master/scripts/two-chainz (this uses gaia, which we can replace with simapp) and just prepares the chains, not the connections. You can try these scripts out, but I woud not use them in our CI, just use them for design reference.

This will set up a relayer for 2chainz: https://github.com/cosmos/relayer/blob/master/scripts/config-relayer

And this is the demo setup scripts they run: https://github.com/cosmos/relayer#demoing-the-relayer

Please do try to get those to work out of the box (using their scripts and binaries) and when that works, we can see what we can pull out into our CI.

**Comment by willclarktech** [comment]
Closed in #510 
Relayer functionality will be covered in #499 and #500
