### ISSUE TITLE
"Tx already exists in cache" not transparent to user

### ISSUE THREAD

**Issue by faboweb** [cosmos/cosmjs#502]
`lcdClient.js`
```
        const responseData = await this.post("/txs", params);
        if (!responseData.txhash) {
            throw new Error("Unexpected response data format");
        }
```

In this case, the response "broadcast_tx_commit: response error: RPC error -32603 - Internal error: Error on broadcastTxCommit: Tx already exists in cache" is not forwarded to user. this is an important error message

**Comment by webmaster128** [comment]
The LCD client is deperacted and will be removed in 0.28.0. Also instead of `broadcast_tx_commit` we now use `broadcast_tx_sync`.
