### ISSUE TITLE
Handle sequence correctly

### ISSUE THREAD

**Issue by faboweb** [cosmos/cosmjs#503]
https://github.com/cosmos/cosmjs/blob/7d4809c13dd0855c439eb337ad7dfad8e4040713/packages/launchpad/src/cosmosclient.ts#L221

The address can be "" if you haven't send a tx yet.

Example:
http://lcd.akash-testnet.forbole.com/auth/accounts/akash1an5yf945kgdgjlhcv45revqngutt5qauux3tv2
http://lcd.akash-testnet.forbole.com/bank/balances/akash1an5yf945kgdgjlhcv45revqngutt5qauux3tv2

**Comment by webmaster128** [comment]
The sequence can be 0, this is correct.

But if your account is not known to the chain, you cannot send a transaction with sequence `0`, right (tested this at some point manually)? So what would be the use case for returning 0 instead of the error here?

**Comment by webmaster128** [comment]
Ah, I now understand the example. This account got tokens in genesis, right?

Isn't this a bug in the `/auth/accounts/` implementation? The address and the coins should be listed in there.

**Comment by faboweb** [comment]
Thinking about it, I guess you are right. And this is a bug in the implementation. Will close for now. Thanks man.

**Comment by webmaster128** [comment]
We can adapt the client implementation trivially if this is a known limitation we need to live with.

We can skip `CosmosClient.getAccount` and return the server's response directly. I just wonder if the accountNumber 0 is correct. Do you have a genesis file or Tendermint RPC link for that network?

**Comment by faboweb** [comment]
No no, I confirmed the response was wrong and I pinged the Akash team to fix the issue.
