### ISSUE TITLE
cosmos-sdk/BaseAccount not supported

### ISSUE THREAD

**Issue by Enflow-io** [cosmos/cosmjs#511]
I use cosmos sdk v0.40.0-rc0.
In browser: 

```
  const cosmJS = new SigningCosmosClient(
                        "http://0.0.0.0:1317",
                        accounts[0].address,
                        offlineSigner,
                    );
             
                    const result = await cosmJS.sendTokens("cosmos1c297nt22qwtceatd0mts4uxqftchpcez649nr0", [{
                        denom: "cmb",
                        amount: "10",
                    }]);
```

Error: 
`Unexpected response data format`

Error raised from auth.js
```

function setupAuthExtension(base) {
    return {
        auth: {
            account: async (address) => {
                const path = `/auth/accounts/${address}`;
                const responseData = await base.get(path);
                if (responseData.result.type !== "cosmos-sdk/Account") {
                    throw new Error("Unexpected response data format");
                }
                return responseData;
            },
        },
    };
}
```

whats the best way to get  SigningCosmosClient working?

**Comment by webmaster128** [comment]
In constrast to the client in `@cosmjs/launchpad`, ` SigningCosmosClient` connects to Tendermint RPC (either via HTTP or WebSockets). So you need to use your Tendermint base URL there, e.g. `"localhost:26657"` (defaults to WS), `ws://localhost:26657` or `http://localhost:26657`.

**Comment by webmaster128** [comment]
Oh wait, there is another confusion: `SigningCosmosClient` from `@cosmjs/launchpad` cannot connect to Cosmos SDK 0.40.x (Stargate). You need to look into the `@cosmjs/stargate` package.

**Comment by Enflow-io** [comment]
Thx a lot!

I've tried to sign transaction with Keplr signer but it uses @cosmjs/launchpad (https://github.com/chainapsis/keplr-extension/blob/master/src/content-scripts/inject/cosmjs-offline-signer.ts)

So I think its not possible right now.

**Comment by webmaster128** [comment]
The combination stargate+Keplr+CosmJS is indeed not supported at the moment. This will require us to release a final 0.24.0 and coordinate with the Keplr team.

**Comment by webmaster128** [comment]
Can this be closed?

**Comment by Enflow-io** [comment]
Yes, thx!
