### ISSUE TITLE
Update development chain setup

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#515]
Right now we use wasmd for all launchpad testing. When we upgrade it, we loose basic launchpad testing. Let's upgrade the local chain setup to something like this:

- [x] Rename chain `wasmd` to `launchpad`, including all testing code referring to it (ports 1317/26657)
- [x] Keep simapp but change ports (ports 1318/26658, i.e. default+1)
- [ ] Add new chain stargate based `wasmd` (ports 1319/26659, i.e. default+2)
- [ ] Update ports table in HACKING.md

**Comment by willclarktech** [comment]
Blocked by https://github.com/CosmWasm/wasmd/pull/307

**Comment by webmaster128** [comment]
wasmd v0.12.0 is now available on DockerHub
