### ISSUE TITLE
Upgrade simapp from 0.40.0-rc2 to 0.40.0-rc3

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#524]
and adapt Stargate client
~Depends on #515~

**Comment by webmaster128** [comment]
@willclarktech why do you think this depends on #515? We can just update the simapp backend as we use it right now from rc2 to rc3.

**Comment by willclarktech** [comment]
@webmaster128 I guess it doesn't really, I just wasn't sure at the time what exactly was going to be involved in upgrading our development chain setup.

**Comment by webmaster128** [comment]
Blocked by https://github.com/cosmos/cosmos-sdk/issues/7963
