### ISSUE TITLE
Error: Unknown query type

### ISSUE THREAD

**Issue by JakeHartnell** [cosmos/cosmjs#529]
Searching transactions by `sentFromOrTo` or `tags` throws an `Unknown query type` error.

Example code:
```
const searchResult = await client.searchTx({ sentFromOrTo: address });
```

Result:
```
Error: Unknown query type
    at StargateClient.searchTx (stargateclient.ts:213)
```

Looking at the code in `stargateclient.ts`, it seems querying by `sentFromOrTo` or `tags` has not been implemented (they are included in the `SearchTxQuery` type):
```
    if (isSearchByIdQuery(query)) {
      txs = await this.txsQuery(`tx.hash='${query.id}'`);
    } else if (isSearchByHeightQuery(query)) {
      txs =
        query.height >= minHeight && query.height <= maxHeight
          ? await this.txsQuery(`tx.height=${query.height}`)
          : [];
    } else {
      throw new Error("Unknown query type");
    }
```

**Comment by webmaster128** [comment]
Yeah, the error message is misleading. The query type is known, but not implemented for stargate.
