### ISSUE TITLE
Proto signing fails when accountNumber = 0

### ISSUE THREAD

**Issue by jordansexton** [cosmos/cosmjs#549]
All the tests for proto signing use `1` as the `accountNumber`:

https://github.com/cosmos/cosmjs/blob/c0b714bc5fb527dddf36e7f579a26e281268a7ab/packages/proto-signing/src/signing.spec.ts#L94

https://github.com/cosmos/cosmjs/blob/c0b714bc5fb527dddf36e7f579a26e281268a7ab/packages/proto-signing/src/directsecp256k1hdwallet.spec.ts#L71

https://github.com/cosmos/cosmjs/blob/c0b714bc5fb527dddf36e7f579a26e281268a7ab/packages/proto-signing/src/directsecp256k1wallet.spec.ts#L47

We had a situation where we tried to send tokens from `accountNumber: 0`, which gets converted to a `Long` of `{low: 0, high: null, unsigned: null}` here:

https://github.com/cosmos/cosmjs/blob/c0b714bc5fb527dddf36e7f579a26e281268a7ab/packages/proto-signing/src/signing.ts#L44

`omitDefaults` then recursively converts this to a plain JS object of `{low: null, high: null, unsigned: null}` here:

https://github.com/cosmos/cosmjs/blob/c0b714bc5fb527dddf36e7f579a26e281268a7ab/packages/proto-signing/src/adr27.ts#L43

This leads to an invalid signature (ref: https://github.com/tendermint/vue/issues/39)

@webmaster128 @jgimeno @vince19972 @fadeev

**Comment by webmaster128** [comment]
Nice catch! Thank you for the detailed report. In #549 you find a fix for this.

Testing this higher level is not trivial but possible. It would require us to use the private key for the account number 0 (i.e. the validator account), which we don't have a mnemonic for. However, in this case the bug is well understood, so it should work with the PR merged.

**Comment by webmaster128** [comment]
The fix was released yesterday as part of 0.24.0-alpha.10

**Comment by clockworkgr** [comment]
This seems to have crept up again, I'm not entirely sure what's going on but it was fixed...then with the switch to ts-proto it broke again but I'm guessing at https://github.com/cosmos/cosmjs/pull/683/commits/122bb2b8c7d94bcb0e7d7aafeb51e4f5516cf4f1 (which is not published yet) it will be fixed again? (Judging by thttps://github.com/cosmos/cosmjs/pull/683/commits/122bb2b8c7d94bcb0e7d7aafeb51e4f5516cf4f1#diff-5a8a8281a582e07fbab43135198c6ada6d119ba3468e4c195465ee95112fa116L69-R80) 

@webmaster128 Can you confirm this is the case? (if so, when are you publishing next ? :D)

**Comment by webmaster128** [comment]
Right. With the ts-proto migration PR the adr27 module containing the fix got unused, which is a bug. [It was fixed](https://github.com/cosmos/cosmjs/pull/683) with a ts-proto update, which [omits all default values](https://github.com/stephenh/ts-proto/pull/215).

I'll publish an update by the end of the day.

**Comment by clockworkgr** [comment]
Awesome!

**Comment by webmaster128** [comment]
0.24.0-alpha.26 is released, which should fix this again since we regenerated internal types with a version of ts-proto that does not serialize default values like accountNumber = 0.

**Comment by angelorc** [comment]
At the moment I'm using 0.26.0 version and it seems that the problem has returned.

I launched a new chain with 2 accounts (accounts 0 and 1), if I try to make a transaction with account 0 I always receive the incorrect signature error. If I try to carry out the same operations with Account 1 I'm not getting any errors.

I performed the same test from Command Line and all two accounts work properly.

Do you have any idea on how can I solve this?

**Comment by webmaster128** [comment]
@angelorc could you open a new ticket for you issue to be able to track it? It's probably a different issue. Could you also include Cosmos SDK version, sign mode, @cosmjs/ package you use, wallet type and message type?

**Comment by angelorc** [comment]
@webmaster128 done https://github.com/cosmos/cosmjs/issues/961
