### ISSUE TITLE
signAndBroadcast: Invalid sender address (empty address string is not allowed): invalid address

### ISSUE THREAD

**Issue by fadeev** [cosmos/cosmjs#559]
Trying to send tokens on `v0.40.0-rc3` using `0.24.0-alpha.10`.

```js
import { Secp256k1HdWallet, coins } from '@cosmjs/launchpad'
import { SigningStargateClient } from '@cosmjs/stargate'
import { Registry, Coin } from '@cosmjs/proto-signing'

const wallet = await Secp256k1HdWallet.fromMnemonic(mnemonic)
const registry = new Registry()
registry.register('/cosmos.base.v1beta.Coin', Coin)
const options = { registry }
const client = await SigningStargateClient.connectWithWallet(
  'http://localhost:26657',
  wallet,
  options
)

const msg = {
  typeUrl: '/cosmos.bank.v1beta1.MsgSend',
  value: {
    amount: coins(10, "token"),
    from_address,
    to_address
  }
}

const fee = {
  amount: coins(0, denom),
  gas: '200000'
}

await client.signAndBroadcast(
  from_address,
  [msg],
  fee
)
```

Addresses are correct. I'm getting:

```
{
  "height": 0,
  "code": 7,
  "transactionHash": "3E6D51B7FFC72D858A665628A11364C23D8CCD9952ADCCAFD4395CC8F913C068",
  "rawLog": "Invalid sender address (empty address string is not allowed): invalid address",
  "data": undefined
}
```

This works, however, I had to change my denom to `ucosm` to pay for fees:

```
await client.sendTokens(
  'cosmos16f2fnp5z3c6437yvty9rv2yr4a4x0sqzvmsp68',
  'cosmos1gz8sadt4zq7568uqm9cjgvyus45z8rxhhtylq2',
  coins(2, 'ucosm')
)
```

**Comment by fadeev** [comment]
Okay, my mistake was in the `msg`, has to be:

```
const msg = {
  typeUrl: '/cosmos.bank.v1beta1.MsgSend',
  value: {
    amount: coins(10, "token"),
    fromAddress,
    toAddress
  }
}
```

In case someone else finds it useful 🙂

**Comment by fadeev** [comment]
Although I still don't understand why it's sometimes `from_address` and other times `fromAddress`.

**Comment by willclarktech** [comment]
Hi @fadeev, some clarity on why it's sometimes `from_address` and sometimes `fromAddress`:
- Our code style in CosmJS is generally to use camelCase for names.
- Amino encoding (ie the encoding used for all transactions before Stargate) involves stringifying a JSON object, and generally expects snake_case keys like `from_address`.
- With Protobuf encoding (available for the first time in Stargate) the fields are indexed and the key names aren't present - it's up to you how you display the keys when you do the deserialisation. We just use the default setting from protobufjs, which is camelCase, although they do provide a `--keep-case` option to preserve the case from the `.proto` definition files: https://github.com/protobufjs/protobuf.js#pbjs-for-javascript
