### ISSUE TITLE
Use rest server simulation query to estimate gas

### ISSUE THREAD

**Issue by ethanfrey** [cosmos/cosmjs#56]
There is some way for a query to do a dry run and return expected gas needed. This is used by the wasmdcli

Not high priority but it would be a nice feature

**Comment by faboweb** [comment]
From my experience, the gas simulation doesn't work and usually needs a high factor to not cause some txs to run out of gas.

**Comment by webmaster128** [comment]
> From my experience, the gas simulation doesn't work and usually needs a high factor to not cause some txs to run out of gas.

Thank you for sharing. What's Lunie's strategy to set gas values?

**Comment by faboweb** [comment]
We use high fixed values for the gas estimate and adjust the gas price to not cause mega high fees.

**Comment by ethanfrey** [comment]
Thanks for chiming in @faboweb This is indeed the experience with many other apps. Simulate doesn't really simulate it all too well :(

I made this comment, hoping to improve the case for launchpad https://github.com/cosmos/cosmos-sdk/issues/6522#issuecomment-652051823 but it looks like it was tentatively rejected https://github.com/cosmos/cosmos-sdk/issues/6522#issuecomment-652410557

That said, they did decide to make launchpad 0.39, so maybe there is the chance to get the improved simulation estimate inside the launchpad release so it makes sense

**Comment by ethanfrey** [comment]
This seems a key issue that would lead to better estimates: https://github.com/cosmos/cosmos-sdk/issues/4938

**Comment by webmaster128** [comment]
This is now tracked in #828
