### ISSUE TITLE
Typo? "/cosmos.base.v1beta.Coin"

### ISSUE THREAD

**Issue by fadeev** [cosmos/cosmjs#560]
`"/cosmos.base.v1beta1.Coin"` instead of `"/cosmos.base.v1beta.Coin"`.

https://github.com/cosmos/cosmjs/blob/master/packages/stargate/src/signingstargateclient.spec.ts#L166

**Comment by willclarktech** [comment]
Hi, thanks for the issue. The typo here is not really important as it's only used by the local registry to find the right codec, but it was intended to conform to the Cosmos SDK URLs.
