### ISSUE TITLE
Separate searchTx and searchTxById in launchpad and stargate

### ISSUE THREAD

**Issue by willclarktech** [cosmos/cosmjs#579]
Right now we include a "search by ID" query as one of the query types in the `searchTx` method of both the launchpad and stargate clients. But searching by ID is different to other kinds of searches because it should never return more than one transaction and search filters don't really make sense. We should separate this functionality out into a separate method in both packages.

**Comment by ethanfrey** [comment]
Makes sense to handle this cases separately
