### ISSUE TITLE
Deprecate packages on npm

### ISSUE THREAD

**Issue by willclarktech** [cosmos/cosmjs#583]
Right after the 0.24.0, we should deprecate those on npm:

- [ ] @cosmjs/cosmwasm: "This package has been renamed to @cosmjs/cosmwasm-launchpad"
- [ ] @cosmjs/launchpad-ledger: "This package has been renamed to @cosmjs/amino-ledger"

**Comment by webmaster128** [comment]
Adapted description to also include @cosmjs/launchpad-ledger

**Comment by webmaster128** [comment]
Done
- https://www.npmjs.com/package/@cosmjs/cosmwasm
- https://www.npmjs.com/package/@cosmjs/launchpad-ledger
