### ISSUE TITLE
Evaluate ts-proto for code generation

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#586]
After a talk with @okwme and @amaurymartiny it turned out that [ts-proto](https://github.com/stephenh/ts-proto) might be a better, more modern way to generate TypeScript definitions from .proto files than protobuf.js's .d.ts generator is. ts-proto is based on protobuf.js but provides a TS layer that produces more modern output.

Regen uses ts-proto in their client lib here: https://github.com/regen-network/regen-js

It would be nice if we find a common best practice for JS/TS code generation to improve the experience for developers working with CosmJS but have their own types.

**Comment by webmaster128** [comment]
Hi all subscribers, please see #616 for a spike of this. Ping @amaurymartiny

**Comment by webmaster128** [comment]
It was decided that CosmJS migrates to ts-proto before the final release of 0.24.0.

The following methods to generate customs types will be supported from now on:

1. **ts-proto**, i.e. the calling application runs a code generation step using ts-proto on the application specific .proto files. The resulting types will be compatible with the CosmJS interfaces.
2. **raw protobufjs**: since ts-proto is based on protobufjs, we can skip the TypeScript layer and inject protobufjs types directly. This works with pure JS as shown here: https://gist.github.com/fadeev/a4981eff1cf3a805ef10e25313d5f2b7/e598df97188b53a2872c93c1444bc73440ba0633#file-script-js-L22-L25. Those JS types can either be generated with custom code generation tooling (like Starport) or by hand written in the calling application itself.

The decorator system will not be maintained due to the lack of interest. It can be re-implemented later on.

**Comment by ethanfrey** [comment]
> The decorator system will not be maintained due to the lack of interest. It can be re-implemented later on.

A bit sad to see that. It worked very cool. That said, I only used it for some test code.
Anyway, whatever works best for the real consumers of the lib is best
