### ISSUE TITLE
SigningCosmWasmClient: test Amino signing mode with CosmWasm message types

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#594]
Right now, the CosmWasm types are missing in

```ts
export class SigningCosmWasmClient extends CosmWasmClient {
  // …
  private readonly aminoTypes = new AminoTypes();
```

**Comment by ethanfrey** [comment]
I think we can reopen this and try again with the wasmd 0.14.0 release, that should have legacy amino support working. It would be nice to have ledger working if it isn't a huge ask, and I am guessing that the code that failed tests before may work with the new wasmd.

**Comment by webmaster128** [comment]
> I am guessing that the code that failed tests before may work with the new wasmd

I don't see any point in untilizing any kind of auto-conversion code as we did before. If we want to have this, let's switch over message types and add support for some of them by creating the Amino representation manually.

Let's say we want to create a sign for of a `/cosmwasm.wasm.v1beta1.MsgExecuteContract` – how do we know what it's Amino JSON represenation looks like?

**Comment by ethanfrey** [comment]
I agree completely with manually adding these.

I would support bank, staking (most common used by wallets) and x/wasm (for cosmwasm testnet)

That should be sufficient bridge until ledger supports protobuf/Stargate.
