### ISSUE TITLE
Backport axios update to CosmJS 0.23

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#598]
Our CosmJS 0.23 users cannot update axios because a patch was released as a semver incompatible version bump.

E.g. 
<img width="934" alt="Bildschirmfoto 2021-01-06 um 00 16 16" src="https://user-images.githubusercontent.com/2603011/103710189-b556bc00-4fb4-11eb-9a69-6215ba3c3f67.png">

Let's backport #597 to 0.23. It could be done for 0.22 as well, but I would consider this unsupported unless there is urgent need for this.

**Comment by willclarktech** [comment]
Closed in #599 and with release [v0.23.2](https://github.com/cosmos/cosmjs/releases/tag/v0.23.2).
