### ISSUE TITLE
Remove Lerna dependencies

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#601]
Unfortunatly, [Lerna](https://github.com/lerna/lerna) [seems to be unmaintained](https://github.com/lerna/lerna/issues/2703) and we should remove it from our dependency tree.

One option [is proposed here](https://github.com/lerna/lerna/issues/2703#issuecomment-742107407): https://github.com/atlassian/changesets. I did not yet really look into this.

Another way would be to use plain [Yarn workspaces](https://classic.yarnpkg.com/en/docs/workspaces/), _the low-level primitives that tools like Lerna can (and do!) use_. Since we don't need much of Lerna's functionality, this might be sufficient for us.

**Comment by willclarktech** [comment]
Lerna v4.0.0 has been published: https://github.com/lerna/lerna/releases/tag/v4.0.0

**Comment by willclarktech** [comment]
@webmaster128 OK to close after #684 ?

**Comment by webmaster128** [comment]
Yeah, at least for now we're good. I'd keep the eyes open for alternatives, just in case lerna is not maintained long term.
