### ISSUE TITLE
Update wasmd to 0.14.0

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#602]
- [x] Update wasmd to 0.14.0-rc2
- [ ] Update wasmd to 0.14.0 (not yet released, see https://github.com/CosmWasm/wasmd/tags)
- [ ] Update code (if needed)

**Comment by webmaster128** [comment]
Re-opening, since we have 0.14.0-rc2 now, not 0.14.0

**Comment by ethanfrey** [comment]
Sure thing. They should the same code for the client, but you are right, we need to bump the reference in the startup scripts
