### ISSUE TITLE
Update launchpad-ledger dependencies

### ISSUE THREAD

**Issue by abefernan** [cosmos/cosmjs#624]
A Chrome update causes a "Unable to reset device" error when using the ledger to log into [dApps](https://github.com/CosmWasm/dApps).

It seems to be fixed in a newer version of hw-transport: https://github.com/polkadot-js/apps/issues/4049

**Comment by webmaster128** [comment]
The patch was released as @ledgerhq/hw-transport-webusb 5.34.1, which is in out version range ^5.25.0. So applications can update this in their project directly.

The yarn.lock here this is only relevant for ledger dev demo that we run manually.
