### ISSUE TITLE
Feature Request: Ability to register new message types on a previously instantiated signing client

### ISSUE THREAD

**Issue by clockworkgr** [cosmos/cosmjs#628]
Currently, a developer would have to load and register all Message Types used by his app prior to instantiating the client.

It would be preferable that we can instantiate the client and then register more message types as desired at runtime.

e.g. something like 
```
const registry=new Registry();
const wallet = await DirectSecp256k1HdWallet.fromMnemonic(mnemonic);
const client = await SigningStargateClient.connectWithWallet(api, wallet, { registry });
client.getRegistry().registerType(typeUrl,SomeMessageType);
```

**Comment by webmaster128** [comment]
I think there are 2 good ways to implement this:
1. Make `SigningStargateClient.registry` public (still readonly, but mutable)
2. Add `SigningStargateClient.registerType` to keep the rest of `Registry` internal.

As a temporary workaround you can maintain a reference to your `const registry=new Registry();`. This is the same reference used by the `client`. So when you add a type to it, it becomes available to the client.

**Comment by clockworkgr** [comment]
As long as there is no "magic" that happens internally using the registry passed on instantiation (I haven't looked at the client code) it should be straight-forward and temporary workaround will work fine. Was just unsure if there was magic or not :)

**Comment by webmaster128** [comment]
This is straight forward:

```ts
export class SigningStargateClient extends StargateClient {
  private readonly fees: CosmosFeeTable;
  private readonly registry: Registry;
  private readonly signer: OfflineSigner;
  private readonly aminoTypes: AminoTypes;

  public static async connectWithSigner(
    endpoint: string,
    signer: OfflineSigner,
    options: SigningStargateClientOptions = {},
  ): Promise<SigningStargateClient> {
    const tmClient = await TendermintClient.connect(endpoint, adaptor34);
    return new SigningStargateClient(tmClient, signer, options);
  }

  private constructor(
    tmClient: TendermintClient,
    signer: OfflineSigner,
    options: SigningStargateClientOptions,
  ) {
    super(tmClient);
    const {
      registry = createDefaultRegistry(),
      aminoTypes = new AminoTypes({ prefix: options.prefix }),
      gasPrice = defaultGasPrice,
      gasLimits = defaultGasLimits,
    } = options;
    this.fees = buildFeeTable<CosmosFeeTable>(gasPrice, defaultGasLimits, gasLimits);
    this.registry = registry;
    this.aminoTypes = aminoTypes;
    this.signer = signer;
  }
```

So for now it is safe to mutate the registry reference.

**Comment by willclarktech** [comment]
@clockworkgr `SigningStargateClient.registry` will be a public property in the next version.
