### ISSUE TITLE
Add functionality needed for relayer

### ISSUE THREAD

**Issue by ethanfrey** [cosmos/cosmjs#632]
A number of missing APIs that I found when sketching out the relayer. Most are available in lower-level, but it would be good to expose them.

Missing from `stargate/SigningStargateClient`:

- [ ] `getCommit` - Return header and all validator signatures. This is available as `this.tmClient.commit(height?: number)` PR #633 but likely not needed
- [x] `queryClient` doesn't include IBCExtension. (in `v0.24.0-alpha.19`)
- [ ] Helpers for creating IBC messages. Minimal set: CreateClient, UpdateClient, ConnOpenInit, ConnOpenTry, ConnOpenAck, ConnOpenConfirm, ChanOpenInit, ChanOpenTry, ChanOpenAck, ChanOpenConfirm, ReceivePacket, ReceiveAcknowledgement, ReceiveTImeout (see https://github.com/cosmos/cosmjs/issues/636)

(I will add more when I find them)

**Comment by willclarktech** [comment]
Default `StargateClient` includes the IBC extension as of https://github.com/cosmos/cosmjs/pull/630

**Comment by ethanfrey** [comment]
Awesome, I will pull in main and double-check

**Comment by webmaster128** [comment]
As far as I can tell those issues have been resolved. Let's create specific follow-ups when needed.

Wehn it comes to accessing lower level Tendermint it makes sense to create a Tendermint34Client directly. As of https://github.com/cosmos/cosmjs/pull/1376 you can stick your manually created TendermintClient in a SigningStargateClient or SigningCosmWasmClient.
