### ISSUE TITLE
Add x/gov messages to stargate.codec

### ISSUE THREAD

**Issue by ethanfrey** [cosmos/cosmjs#635]
Requested in discord by @shanev 

Currently protobuf types are generated for:

cosmos: auth, bank, distribution, staking
ibc: channel, client, commitment, connection

Both looking at [queries](https://github.com/cosmos/cosmjs/tree/main/packages/stargate/src/queries) and the [generated protobuf codec](https://github.com/cosmos/cosmjs/tree/main/packages/stargate/src/codec/generated)

Governance is a bit trickier, as we must register and define all the proposal types. This may require more updates to the protobuf generation, as well as registry and possibly a few more helper functions to enable this (protobug.Any inside protobuf.Any).

Note: as there is an ongoing proto-ts refactor #616, it may make sense to deal with this one all the other types are working with the new codec.

**Comment by shanev** [comment]
Here's a failing test based on our fork of cosmjs that generates gov:
```ts
import { cosmos } from '@stargazefi/proto-signing/build/codec';

const { TextProposal, MsgSubmitProposal } = cosmos.gov.v1beta1;

it('Encodes and decodes MsgSubmitProposal', () => {
    const textProposalMsg = TextProposal.create({
        title: 'title',
        description: 'decription'
    });

    const textProposalMsgAny = { 
        typeUrl: "/cosmos.gov.v1beta1.TextProposal",
        value: textProposalMsg,
    }

    const msg = MsgSubmitProposal.create({
        content: textProposalMsgAny,
        initialDeposit:[{
            denom: "uatom",
            amount: "100000000"
        }],
        proposer: "cosmos1qypqxpq9qcrsszg2pvxq6rs0zqg3yyc5lzv7xu"
    })

    const expected = MsgSubmitProposal.encode(msg).finish();
    const decoded = MsgSubmitProposal.decode(expected);

    expect(decoded).toEqual(msg);
});
```

**Comment by webmaster128** [comment]
@shanev could you add more context of what you try to do?

Ethan is right, we do not do the code generation for gov right now. But this can be done on the caller side, as you figured out already. Once you have the types, you need to register them, e.g. in a `SigningStargateClient` as done here: https://github.com/cosmos/cosmjs/blob/v0.24.0-alpha.20/packages/cosmwasm-stargate/src/queries/wasm.spec.ts#L40-L67.

**Comment by webmaster128** [comment]
Long term it is expected to only include the abolute minimum types in `@cosmjs/proto-signing` and a small sumset of common Cosmos SDK types in `@cosmjs/stargate`. In addition to that, we'll make it easier than right now to add your own types externally. [ts-proto will help us](https://github.com/cosmos/cosmjs/pull/616) make that much nicer than right now.

**Comment by shanev** [comment]
@webmaster128 Simply trying to sign and broadcast a `MsgSubmitProposal` to an SDK-based chain (v 0.40.1) that uses gov. Will try the registry and fallback to REST until the ts-proto migration is done. Thank you, this clears it up.

**Comment by willclarktech** [comment]
@shanev Cosmos-SDK v0.40 is pre-Stargate and does not support protobuf encodings.

**Comment by webmaster128** [comment]
> Cosmos-SDK v0.40 is pre-Stargate and does not support protobuf encodings.

Cosmos SDK v0.40 is the first protobuf-based release and the protobuf gov transactions should work here. It might not be the version released to the Hub and it is getting blury what "Stargate" actually means, but this is a different story.

**Comment by shanev** [comment]
> @shanev Cosmos-SDK v0.40 is pre-Stargate and does not support protobuf encodings.

This is incorrect. 

v0.40 = Stargate (https://github.com/cosmos/cosmos-sdk/releases/tag/v0.40.0)
v0.39 = Launchpad for previous chains

v0.41 was released today (https://github.com/cosmos/cosmos-sdk/releases/tag/v0.41.0) which I guess is the new new Stargate that'll be used for the upgrade :)

**Comment by webmaster128** [comment]
This ticket is mostly superseded by #799. Let's address this first. Then we'll be in a different sitiuation and have different follow-up discussions.
