### ISSUE TITLE
Add ibc messages to codec

### ISSUE THREAD

**Issue by ethanfrey** [cosmos/cosmjs#636]
I was trying to use stargate.codec to create IBC client messages, but I couldn't find the Msg types.

Looking at [the generation scripts](https://github.com/cosmos/cosmjs/blob/6182791cb82eb48466a6410ac970e5d37ba0f808/packages/stargate/scripts/predefine-proto.sh#L42-L47), I saw that `tx.proto` and in 2 cases `query.proto` were not compiles, although they are present in those directories: https://github.com/cosmos/cosmos-sdk/tree/master/proto/ibc/core/client/v1

Please add those generated codecs, so I can try to create messages.

Also, if it is not too much work, a query extension for client and connections would also be useful (although I guess I could do that outside of the package if the protobuf definitions are there?)

**Comment by ethanfrey** [comment]
Note I have `queryClient.ibc.unverified.clientConnections()`, but I do not have any way to list all clientIds or get the details of them. (much less create them).

**Comment by willclarktech** [comment]
> Also, if it is not too much work, a query extension for client and connections would also be useful (although I guess I could do that outside of the package if the protobuf definitions are there?)

@ethanfrey The query extensions have been implemented in the ts-relayer, correct? Do we still need them in CosmJS?

**Comment by webmaster128** [comment]
Maybe a reasonable strategy would be to bring https://github.com/confio/ts-relayer/blob/main/src/lib/queries/ibc.ts into CosmJS. Then it also makes sense to generate the IBC codes here.

I just wonder about the concept of verified/unverified queries. They seem to be mixed in the implementation.

**Comment by ethanfrey** [comment]
> I just wonder about the concept of verified/unverified queries. They seem to be mixed in the implementation.

We don't verify any of them. In some cases, we just make the rpc query to get the answer. In other cases, we make the raw query to get the proof. We don't verify the proof, but need it to pass along to the other blockchain.

In some future, we could do proper light client verification of these proofs. But for the relayer, we assume you have two trusted nodes to talk to, and the other chain will verify the proofs anyway (you just waste gas if they are invalid)

**Comment by ethanfrey** [comment]
The `proof` subset is only needed for IBC transactions, but may be nice to have if anyone else wants to relay besides using ts-relayer. For now, you can just drop those.

**Comment by webmaster128** [comment]
Good, then let's take the query extrension from the IBC relayer and the codec from #711. Then it can live here, make people happy and evolve over time.

**Comment by webmaster128** [comment]
If we don't do verified queries, can't we bypass this whole idea of the query extension and `QueryClient`? Just create the services via code generation and pass in a Tendermint client?

**Comment by ethanfrey** [comment]
> If we don't do verified queries, can't we bypass this whole idea of the query extension and QueryClient? Just create the services via code generation and pass in a Tendermint client?

In general sounds good for the default case.

For ts-relayer, we need to make some raw queries that needs some helpers around the Tendermint client.

I am happy to simplify the API and keep the full on lightclient on the "later" list, probably with a different API (let's keep that QueryClient code for it, just not use it by default).

**Comment by willclarktech** [comment]
Closed in #711
