### ISSUE TITLE
Mnemonic Length

### ISSUE THREAD

**Issue by gelinger777** [cosmos/cosmjs#680]
How can I force the lib to generate longer mnemonics? The  default  create wallet  undeneath generates very short mnemonic. 

```
import { Secp256k1HdWallet } from "@cosmjs/launchpad";

// …

const wallet = await Secp256k1HdWallet.generate();
console.log("Mnemonic:", wallet.mnemonic);

const [{ address }] = await wallet.getAccounts();
console.log("Address:", address);
```

**Comment by webmaster128** [comment]
Here you find the optional arguments to `.generate`. The first is the number of words, defaulting to 12.
https://cosmos.github.io/cosmjs/latest/launchpad/classes/secp256k1hdwallet.html#generate

But why do you think this is "very short"? 12 words is 128 bit of entropy. Do you have a specific reason to use more than that?

**Comment by gelinger777** [comment]
oh thank you.  I will check that. Starport serve by default generates Mnemonics which are of double size as I remember. That's why I felt the ones generated by this tool is shorter.  Anyway thank you very much.

**Comment by webmaster128** [comment]
> Starport serve by default generates Mnemonics which are of double size as I remember. That's why I felt the ones generated by this tool is shorter.

Right, most Cosmos SDK based tooling generates 24 words (256 bits). But nobody could ever tell me why this is required and justifies the additional UX pain for users.
