### ISSUE TITLE
Support for secp256k1 validator pubkeys

### ISSUE THREAD

**Issue by ethanfrey** [cosmos/cosmjs#681]
There is a comment here to only support ed25519: https://github.com/cosmos/cosmjs/blob/main/packages/tendermint-rpc/src/types.ts#L11-L15

This has been updated in tendermint and they also support secp256k1. Please update the type definitions and the validation in the parsing code to allow both types. (not urgent, just noted while working on the relayer)

**Comment by webmaster128** [comment]
See also https://github.com/cosmos/cosmjs/issues/753
