### ISSUE TITLE
Add support for staking operations on SigningComsosClient

### ISSUE THREAD

**Issue by ethanfrey** [cosmos/cosmjs#687]
And ideally on SigningCosmWasmClient.

Beyond sendTokens, there are 3 very common operations exposed on almost all wallets (and some block explorers):

* stake tokens
* unstake tokens
* withdraw rewards

We should support those 3 (and maybe re-delegate) inside CosmJS to make it as useful for basic use-cases without forcing them all to compile ts-proto from scratch (needed for any custom modules).

We have some code on the pre-`ts-proto` format that imports objects from the `codec` inside cosmjs. That approach seems to be deprecated and before adding all the ts-proto codegen, it would be nice to just see that inside CosmJS. I can share the equivalent code with protobufjs.

@abefernan maybe can add more

**Comment by ethanfrey** [comment]
There is react code that looks like:

```ts
const delegateTokens = useCallback(
    async function (validatorAddress: string, delegateAmount: Coin): Promise<void> {
      if (!address || !signingClient) return;

      const delegatorAddress = address;
      const delegateMsg: EncodeMsgDelegate = {
        typeUrl: "/cosmos.staking.v1beta1.MsgDelegate",
        value: { delegatorAddress, validatorAddress, amount: delegateAmount },
      };

      const response = await signingClient.signAndBroadcast(
        delegatorAddress,
        [delegateMsg],
        getDelegationFee(config),
      );
      if (isBroadcastTxFailure(response)) {
        throw new Error("Delegate failed");
      }
    },
    [address, config, signingClient],
  );
```

Most of the async function could ideally be replaced by an import. (Which will make wallet developers everywhere more likely to use CosmJS)

**Comment by willclarktech** [comment]
Covered in #733
