### ISSUE TITLE
Fix min/maxHeight format on tendermint-rpc txSearch

### ISSUE THREAD

**Issue by ethanfrey** [cosmos/cosmjs#688]
I tried doing `tx.minHeight=123` and it failed.

After reading https://docs.tendermint.com/master/rpc/#/Websocket/subscribe I managed to find the proper syntax. We also need to use `AND` in `buildQuery`.

Here is an example of a successful query with min and max height against tendermint 0.34 / cosmos-sdk 0.41.3:

`send_packet.packet_connection='connection-9' AND tx.height>=7669 AND tx.height<=7669`

**Comment by webmaster128** [comment]
`minHeight` is an invention of the LCD API, which only supports equality in its query requests. The deamon translated those to `>=`/`<=` before sending the request to Tendermint.

In @cosmjs/stargate and @cosmjs/cosmwasm-stargate we already use the correct query format before sending the Query to Tendemint: https://github.com/cosmos/cosmjs/blob/v0.24.0-alpha.25/packages/stargate/src/stargateclient.ts#L221-L223

`buildQuery` already concatenates the individual components via `AND`:

```ts
export function buildQuery(components: BuildQueryComponents): string {
  const tags = components.tags ? components.tags : [];
  const tagComponents = tags.map((tag) => `${tag.key}='${tag.value}'`);
  const rawComponents = components.raw ? [components.raw] : [];

  return [...tagComponents, ...rawComponents].join(" AND ");
}
```

So I am not sure what is left in this ticket.

**Comment by ethanfrey** [comment]
Ah, I guess I ended up in launchpad when looking for how to build queries. Guess this is done, and it was user error.

Thanks
