### ISSUE TITLE
pbjs generated types compatibility.

### ISSUE THREAD

**Issue by clockworkgr** [cosmos/cosmjs#692]
Hello and excuse me if the answer is obvious as I haven't looked heavily into the inner workings of pbsjs/ts-proto but what is the reason for the switch from `.fromJSON` to `.fromPartial` ?

The reason I'm asking is because generated types from pbjs only output the former function while ones from ts-proto output both functions. Thus keeping `.fromJSON` seems like would aid backwards compatibility.

As it stands we need to update our build pipeline to use ts-proto instead to generate types (which isn't as easy as it sounds) or cosmjs complains with a:
`TypeError: type.fromPartial is not a function`

**Comment by webmaster128** [comment]
Sorry for breaking your code and thanks for bringing this up. It seems like we need a few little case distiinctions on order to support ts-proto generated types and pbjs generated types. I'll create a test that ensures pbjs works.

**Comment by clockworkgr** [comment]
awesome, thanks!

**Comment by webmaster128** [comment]
@clockworkgr could you have a look at #693, especially `packages/proto-signing/src/registry.ts`?

**Comment by webmaster128** [comment]
Released as part of 0.24.0-alpha.26
