### ISSUE TITLE
Make it easier to extend in external apps

### ISSUE THREAD

**Issue by ethanfrey** [cosmos/cosmjs#696]
The use of `private` everywhere makes it easier for you to refactor and keep an API boundary, but does cause some annoyance while trying to customize usage in other packages. In particular, I wanted to make a custom Client in an external repo that supports some more message types, as https://github.com/cosmos/cosmjs/pull/690 is hanging, at it would be good to add such functionality without depending on the CosmJS core team (this is even more critical for all other wallet/app creators). I also wanted to adjust things like `getBalance` to use the unverified variant (so it didn't take so long to list tokens).

So, I tried to start doing it as follows: 

```ts
import { SigningCosmWasmClient } from "@cosmjs/cosmwasm-stargate";

// This wraps the singing client to support extra messages
// and allow us to customize things like query delay
export class SigningClient extends SigningCosmWasmClient {

}
```

But got the error:

```
Cannot extend a class '"/home/ethan/js/wallet/node_modules/@cosmjs/cosmwasm-stargate/build/signingcosmwasmclient".SigningCosmWasmClient'. Class constructor is marked as private.ts(2675)
```

I'd love your opinions here, or maybe a CosmJS dev could take a look at https://github.com/confio/wallet/pull/70 and see if they have an idea on how to approach this *without touching the cosmjs repo*. We should let app devs customize quite a bit, they will want to.

**Comment by willclarktech** [comment]
The easiest way to support what you want to do but maintain some level of control over which methods are for public use is to switch to `protected`: https://www.typescriptlang.org/docs/handbook/classes.html#understanding-protected

**Comment by webmaster128** [comment]
I'm happy with `protected` here. I think it is important that users use the public static instance makers. But subclassing should be fine.

You then probably also want access to some fields like e.g. the Tendermint client.

**Comment by ethanfrey** [comment]
> You then probably also want protected access to some fields like e.g. the Tendermint client.

That would be nice. If you want to support subclassing. If you have another approach for extending the signing client, I am open to that as well

**Comment by webmaster128** [comment]
Looking at the changes in https://github.com/cosmos/cosmjs/pull/726/files, I think we should keep the fields private and

1. Make contructor protected for StargateClient, SigningStargateClient, CosmWasmClient, SigningCosmWasmClient
1. Make Tendermint optional for CosmWasmClient, SigningCosmWasmClient and create an `offline` constructor for `SigningCosmWasmClient`
1. Add protected `getTmClient`/`getQueryClient` and protected `forceGetTmClient`/`forceGetQueryClient` to StargateClient and CosmWasmClient, where the first two return an optional value.
