### ISSUE TITLE
Remove Tendermint 0.33 client from @cosmjs/tendermint-rpc

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#709]
Follow-up of #708

This basically drops Tendermint 0.33 support from CosmJS. All out Launchpad code does not use the Tendermint PRC client under the hood. Instead we connect to the LCD API. But some users might be affected.

**Comment by jnaviask** [comment]
Hi, just wanted to chime in from Twitter with my use case: I manage a web app that connects to various chains, including some still running Tendermint 0.33, and I was intending to use the @tendermint-rpc package to maintain a websocket connection so I can listen to new blocks/headers, as we want to support a few real-time displays for chain height and incoming transactions.

In theory I could replace this with a polling RPC call using the LCD provider, but the simplicity of the stream subscribe is useful to me.

**Comment by webmaster128** [comment]
I am surprised and happy to hear that people actually use the Tendermint/WebSocket functionality.

One of the bbigger problems of the `Client` class is auto-detecting the backend version. This recently broke because Tendermint 0.34 version responses became unrelyable. Also abstracting the interface across different Tendermint versions has been challenging in the past. Do you need auto-detection? Or can we rename `Client` -> `Tendermint33Client` and remove all Tendermint 0.34 support from it? `Tendermint34Client` is the better Tendermint 0.34 client these days.

**Comment by jnaviask** [comment]
> can we rename Client -> Tendermint33Client and remove all Tendermint 0.34 support from it?

That would work perfectly for me, given my use case is so simple/straightforward. It should be easy for me to detect on my own.

**Comment by webmaster128** [comment]
Alright, thanks. Then we do https://github.com/cosmos/cosmjs/issues/789 as an intermediate step and keep Tendermint 0.33 support available for some time (not endless, but also no pressure to remove it).

In the meantime, have a look at `Tendermint34Client` for your 0.34 chains which is more actively maintained than `Client`.

**Comment by jnaviask** [comment]
Hi, after speaking with my team, we've decided instead to deprecate our usage of the Tendermint RPC endpoint, which means I retract my above request. Thanks for all your help!

**Comment by webmaster128** [comment]
Alright. If you change your mind, no problem. We'll take it easy with the removal and stick with #789 as an intermediate step. Let's see if other users care.

For Tendermint 0.34 the Tendermint RPC client is the way to go. We use it in all our higher level Stargate code. So the concept of Tendermint RPC client including subscriptions is first class citizen long term.
