### ISSUE TITLE
Harmonize getAccount inconsistency

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#713]
We started Starget development assuming you can get all data in a light-client-verified way. It turned out that this is not possible for all queries and even the simple ones where you can get a proof, you often do not want to wait for one more block in order to get the result.

So in some places, unverified `getAccount` queries were added. Right now, we have a wild mix.

1. `StargateClient` in `packages/stargate/src/stargateclient.ts` has `getAccount` and `getAccountUnverified`; `StargateClient.getSequence` still uses the verified version.
2. `SigningStargateClient` in `packages/stargate/src/signingstargateclient.ts` uses unverified `getAccountUnverified`.
3. `CosmWasmClient` in `packages/cosmwasm-stargate/src/cosmwasmclient.ts` only has the verified `getAccount`.
4. `SigningCosmWasmClient` in `packages/cosmwasm-stargate/src/signingcosmwasmclient.ts` uses verified `getAccount`.

Given @ethanfrey's changes, I think it makes most sense to make `getAccount` unverified in both cases and add an explicit `getAccountVerified` to both.

**Comment by ethanfrey** [comment]
I agree with the above.

In fact, I would also modify the queriers, such that `unverified` is the default (top-level) and there is a sub-nesting of `verified` for the ones we support there. We also need to get the full light-client header verification working for that and probably need a new API (eg. return `[Promise<T>, Promise<T>]` where the first resolved as the unverified answer, and the second one block later as the verified answer.

Until we have a bulletproof verified solution, let's not use it
