### ISSUE TITLE
Request for Bip 39 passphrase functionality

### ISSUE THREAD

**Issue by puneet2019** [cosmos/cosmjs#736]
DirectSecp256k1HdWallet.fromMnemonic should take a passphrase parameter as well, it is used in creating bip39.mnemonicToSeed.

**Comment by webmaster128** [comment]
Are you using this passphrase? It is not supported here because I never saw it being used in the wild. It would be quite some pain to design an API for that because the method already has two optional arguments.

**Comment by puneet2019** [comment]
yes, I was using  cosmosjs of cosmostaion, they give this option and I am thinking of migrating to cosmjs because I am already using stargate for offline signer. 
Will reduce an extra dependency.

**Comment by webmaster128** [comment]
Alright, let's see how this can be done.

In the meantime what you can do is using thr non-HD wallet `DirectSecp256k1Wallet`


```ts
async function myHelper(/* ... , */password: string): Promise<DirectSecp256k1Wallet> {
  const mnemonicChecked = new EnglishMnemonic(mnemonic);
  const seed = await Bip39.mnemonicToSeed(mnemonicChecked, password);
  const { privkey } = Slip10.derivePath(Slip10Curve.Secp256k1, seed, hdPath);
  return DirectSecp256k1Wallet.fromKey(privkey, prefix);
}
 ```

**Comment by puneet2019** [comment]
Yes, this works, Thank you.

**Comment by webmaster128** [comment]
@willclarktech What do you think about changing `DirectSecp256k1HdWallet.fromMnemonic` to only take the mnemonic as a positional argument and the test goes into and optional `options` object (path, prefix, password)? I would like to avoid an growing list of positional optional arguments.
