### ISSUE TITLE
Support to sign arbitrary message when using SigningStargateClient

### ISSUE THREAD

**Issue by Tore19** [cosmos/cosmjs#738]
For now, we have to call signDirect and input a signDoc struct.
Any idea to support to sign arbitrary message?

**Comment by willclarktech** [comment]
@Tore19 Could you elaborate on the use case(s)?

**Comment by Tore19** [comment]
> @Tore19 Could you elaborate on the use case(s)?

@willclarktech  Hi, our dapp is using Keplr + Cosmjs. And we need user to sign a message(For example, txHash) and then upload the signature and pubkey to our contract, which will use the pubkey to verfiy the signature with the message(txHash).

But it seems that the SigningStargateClient can only sign a cosmos transaction, right?

**Comment by willclarktech** [comment]
@Tore19 That's correct, the `SigningStargateClient` class is for interacting with Stargate chains. When you construct the client you pass an `OfflineSigner` instance, which is probably the appropriate place to expose this functionality.

@webmaster128 What do you think?

**Comment by Tore19** [comment]
> @Tore19 That's correct, the `SigningStargateClient` class is for interacting with Stargate chains. When you construct the client you pass an `OfflineSigner` instance, which is probably the appropriate place to expose this functionality.
> 
> @webmaster128 What do you think?

Looks like that. If `OfflineSigner` support to sign arbitrary message(signArbitraryMessage), we can use the code like this:

```
const offlineSigner = window.getOfflineSigner(chainId);
const signature = offlineSigner.signArbitraryMessage(anyMessage);
```

**Comment by webmaster128** [comment]
First of all I think we should avoid the term "message" in this context as it means everything and nothing. If I understand correctly, this is about signing and verifying arbitrary binary data for a custom application.

In Ethereum [there is this format](https://github.com/CosmWasm/cosmwasm/blob/main/contracts/crypto-verify/src/msg.rs#L20-L33). This is far from great and a bunch of alternatives are proposed, but at least a good number of tools agree on the same format. The difference to transaction signing is:
- No nonce/sequence
- No replay protection (chain ID)

As far as I know, something like this does not exist in Cosmos. Defining a standard for it is probably worth thinking about. As long as this does not exist, I would stay away from implementing it here.

A (hacky) workaround would be to wrap it into a fake transaction which can be verified but that would not be accepted by the chain.

**Comment by Tore19** [comment]
> First of all I think we should avoid the term "message" in this context as it means everything and nothing. If I understand correctly, this is about signing and verifying arbitrary binary data for a custom application.
> 
> In Ethereum [there is this format](https://github.com/CosmWasm/cosmwasm/blob/main/contracts/crypto-verify/src/msg.rs#L20-L33). This is far from great and a bunch of alternatives are proposed, but at least a good number of tools agree on the same format. The difference to transaction signing is:
> 
> * No nonce/sequence
> * No replay protection (chain ID)
> 
> As far as I know, something like this does not exist in Cosmos. Defining a standard for it is probably worth thinking about. As long as this does not exist, I would stay away from implementing it here.
> 
> A (hacky) workaround would be to wrap it into a fake transaction which can be verified but that would not be accepted by the chain.

@webmaster128 Hi, I understand what you mean. In fact, what I talked is not about cosmos chain transactions, just about public and private keys and signature algorithms. In our business, we want the user to sign something(arbitrary binary data) using user's private key through Keplr and then we can verify the signature using user's pubkey.

**Comment by webmaster128** [comment]
Nice, then we're on the same page.

Is Keplr willing to implement a UI for that? I mean this only makes sense if the users knows what they are signing.

**Comment by Tore19** [comment]
> Nice, then we're on the same page.
> 
> Is Keplr willing to implement a UI for that? I mean this only makes sense if the users knows what they are signing.

Yeah. It should be that Keplr supports the functions I described, including the ui and api. I submitted a issue to keplr-extension too, but no response yet.  Anyway, really thanks for your guys reply!

**Comment by webmaster128** [comment]
I think we need a standard more or less like https://eips.ethereum.org/EIPS/eip-712. There the limitations of `eth_sign` are well described. It's worth pursuing but not trivial. Without that I consider it very risky to provide access to the user's signing key for signing arbitrary data.

Maybe @okwme can provide insights if someone in Cosmos is working on off-chain signing.

**Comment by Tore19** [comment]
Make sense. It’s better to have a standard about the signing functions.

**Comment by Tore19** [comment]
@ethanfrey  Got it. Thanks!

**Comment by webmaster128** [comment]
I created a follow-up ticket here: https://github.com/cosmos/cosmjs/issues/844
