### ISSUE TITLE
Adapt CosmWasm client to use sync mode not block

### ISSUE THREAD

**Issue by orkunkl** [cosmos/cosmjs#739]
From discord: We need to adapt CosmWasm to use sync (not block) mode, and then subscribe/poll for the results. This will handle the case when it takes a few blocks to get in.

When the sentry accepts 0 gas, but no validator does, it will pass sync but never make it into a block, ever. An annoying UX issue with these subjective min gas prices.

**Comment by ethanfrey** [comment]
There are 2 issues there. block will often timeout, sometimes in one block, always if it takes 2-3 blocks to get in. Using sync and polling will let us reliably get the result. (Open question: do we do this inside the signing client, or require the caller to handle the waiting).

The other issue is timeout. If we add 0 gas and the tx never makes it in, such a polling loop would take literally forever. We need to add some client-side timeout (which we control, not when the server drops the rpc connection) to the SigningClient

**Comment by clockworkgr** [comment]
Ran into this problem while using the ts-relayer. Considering setting up a relayer is a process that takes quite a few transactions across 2 chains in order, a single one "failing" by virtue of the rpc timeout (although the tx was eventually committed) was halting the entire relayer setup process.

To solve it (for our case) we wrapped SigningClient specifically to implement the above.

Rough implementation can be found here: https://github.com/tendermint/vue/blob/develop/packages/vuex/src/modules/common/relayers/lib/starportSigningClient.js

The timeout could be made configurable as well (in our case it's 1 min, polled in 3 sec intervals)

**Comment by clockworkgr** [comment]
> The other issue is timeout. If we add 0 gas and the tx never makes it in, such a polling loop would take literally forever. We need to add some client-side timeout (which we control, not when the server drops the rpc connection) to the SigningClient

This is the advantage of the solution we implemented. For all intents and purposes it acts EXACTLY like the SigningClient does right now. For all applications utilising it, it simply looks as if the RPC server takes longer to timeout the tx (even returning the original error)

**Comment by ethanfrey** [comment]
Thanks for the comment and example @clockworkgr 
It would be great to have something like this (or maybe an improved variant of it) in CosmJS for all to use

**Comment by clockworkgr** [comment]
> Thanks for the comment and example @clockworkgr
> It would be great to have something like this (or maybe an improved variant of it) in CosmJS for all to use

agree on improved variant :) Am in fact currently refactoring stuff myself

**Comment by webmaster128** [comment]
I just found this nice little warning in the documentation of c[ommit broadcast:](https://docs.tendermint.com/master/rpc/#/Tx/broadcast_tx_commit)

> IMPORTANT: use only for testing and development. In production, use BroadcastTxSync or BroadcastTxAsync. You can subscribe for the transaction result using JSONRPC via a websocket. See https://docs.tendermint.com/master/app-dev/subscribing-to-events-via-websocket.html

This makes me think we should boradcast using "sync" and avoid hoping for the initial "commit" to succeed.
