### ISSUE TITLE
Request to add support for order_by param in tx_search

### ISSUE THREAD

**Issue by puneet2019** [cosmos/cosmjs#748]
Reference api-doc -> https://docs.tendermint.com/master/rpc/#/Info/tx_search
relevant tendermint doc -> https://docs.tendermint.com/master/app-dev/indexing-transactions.html#querying-transactions-events

Relevant - cosmos-sdk release doc - https://github.com/cosmos/cosmos-sdk/releases/tag/v0.42.2 
and the issue for it https://github.com/cosmos/cosmos-sdk/issues/8686 

tendermint -> rpcURL/tx_search?  , now supports `order_by` as query param.

example -> https://rpc.cosmos.network/tx_search?query="message.sender='cosmos1hfml4tzwlc3mvynsg6vtgywyx00wfkhrtpkx6t'"&prove=true&page=1&per_page=30&order_by="desc"

or https://rpc.cosmos.network/tx_search?query=%22message.sender=%27cosmos1hfml4tzwlc3mvynsg6vtgywyx00wfkhrtpkx6t%27%22&prove=true&page=1&per_page=30&order_by=%22desc%22

**Comment by willclarktech** [comment]
@puneet2019 Do you want this supported on the Tendermint client, or on the Stargate client too?

**Comment by puneet2019** [comment]
> @puneet2019 Do you want this supported on just the Tendermint client, or on the Stargate client too?

We have updated all queries to use Tendermint client, only leaving this behind, so using Tendermint client will be easier.

Right now we are directly using the rest url, so actually anyone will do it for me.

**Comment by willclarktech** [comment]
@webmaster128 OK to close then?

**Comment by webmaster128** [comment]
Yes. With #823 we have a solid foundation we can build on any time when needed.
