### ISSUE TITLE
Test SigningStargateClient.sendIbcTokens

### ISSUE THREAD

**Issue by willclarktech** [cosmos/cosmjs#751]
After https://github.com/cosmos/cosmjs/pull/750

**Comment by webmaster128** [comment]
This can be done in the ts-relayer by letting this function build on the CosmJS code: https://github.com/confio/ts-relayer/blob/v0.1.1/src/lib/ibcclient.ts#L1321-L1364

**Comment by webmaster128** [comment]
The implementation is released as part of 0.25.0-alpha.2 and can be tested.

**Comment by willclarktech** [comment]
@bartmacbartek Are you ok to take this issue?

**Comment by ethanfrey** [comment]
I think the first step is updating `ts-relayer` to 0.25-alpha.2 which seems to have a number of API-breaking changes. Maybe @willclarktech wants to do the API update (as he knows what the breaking changes are) and then the Bartek could take on using the new APIs. It would be more efficient than Bartek trying to update "in the dark"

**Comment by willclarktech** [comment]
@webmaster128 OK to close this after https://github.com/confio/ts-relayer/pull/150 ?

**Comment by ethanfrey** [comment]
I merged that PR, good to close from my end

**Comment by webmaster128** [comment]
You are too fast for me
