### ISSUE TITLE
Multisigs created with cosmjs do not have show pubkey info with client.getAccount()

### ISSUE THREAD

**Issue by samepant** [cosmos/cosmjs#767]
I'm working on the app mentioned in #673, and have run into this issue when getting all the info together for signing a transaction with cosmjs. To do this I query a node with `client.getAccount(multisigAddress)`. For multisigs created with cosmjs the response looks like:

```
{
  "address": "cosmos10nmdf6nt2qzvgn9q2nuwmmfc359yfesmu3gw22",
  "pubkey": null,
  "accountNumber": 244765,
  "sequence": 0
}
```

For reference a multisig created with the cli tool returns this:
```
{
  "address": "cosmos1unc788q8md2jymsns24eyhua58palg5kc7cstv",
  "pubkey": {
    "type": "tendermint/PubKeyMultisigThreshold",
    "value": {
      "threshold": "2",
      "pubkeys": [
        {
          "type": "tendermint/PubKeySecp256k1",
          "value": "A1KZtoF5y3sYBZLigf8T8XD+vJnnN84We+wexiwbN16T"
        },
        {
          "type": "tendermint/PubKeySecp256k1",
          "value": "A7FLBpslfQCE2ccXS8KEt6W2IiKd0jesWIqki+8xo/Mz"
        },
        {
          "type": "tendermint/PubKeySecp256k1",
          "value": "AgXQuN/GKcOuC74gPOQa5ldPF72z/BsuT0mpztTc1JUA"
        }
      ]
    }
  },
  "accountNumber": 22545,
  "sequence": 70
}
```

Do I need to somehow use `createMultisigThresholdPubkey` with a online client? 

Thanks!

**Comment by webmaster128** [comment]
What's the value of `multisigAddress`, i.e. are you sure the generated address is correct? Which version of CosmJS are you using?

**Comment by samepant** [comment]
The multisig address is `cosmos10nmdf6nt2qzvgn9q2nuwmmfc359yfesmu3gw22` and it was made with cosmjs version `^0.25.0-alpha.1` 

I believe the address is correct, i was able to [send funds to it](https://www.mintscan.io/cosmos/account/cosmos10nmdf6nt2qzvgn9q2nuwmmfc359yfesmu3gw22)

**Comment by webmaster128** [comment]
Why do you believe this address is correct if you want to generate the account `cosmos1unc788q8md2jymsns24eyhua58palg5kc7cstv`?

**Comment by samepant** [comment]
Oh sorry the info for `cosmos1unc788q8md2jymsns24eyhua58palg5kc7cstv` was just an example of what a multisig created with the cli returns from a `getAccount` call, unrelated to the address `cosmos10nmdf6nt2qzvgn9q2nuwmmfc359yfesmu3gw22`, which was made with cosmjs's `createMultisigThresholdPubkey`.

**Comment by samepant** [comment]
I generated `cosmos10nmdf6nt2qzvgn9q2nuwmmfc359yfesmu3gw22` with this call:

```
const pubkeys = [
  {
	type: "tendermint/PubKeySecp256k1", 
	value: "A8B5KVhRz1oQuV1dguzFdGBhHrIU/I+R/QfBZcbZFWVG"
  },
  {
	type: "tendermint/PubKeySecp256k1", 
	value: "Akd/qKMWdZXyiMnSu6aFLpQEGDO0ijyal9mXUIcVaPNX"
  }
]

const threshold = 2;

const multisig = createMultisigThresholdPubkey(pubkeys, threshold);
const multisigAddress = pubkeyToAddress(multisig, "cosmos");
```

**Comment by webmaster128** [comment]
Okay. So `cosmos10nmdf6nt2qzvgn9q2nuwmmfc359yfesmu3gw22` has no pubkey on the chain and has sequence 0 because it was never used to sign a transaction. I.e. the chain simply does not know of the address beelongs to a simple pubkey or a multisig. Once `cosmos10nmdf6nt2qzvgn9q2nuwmmfc359yfesmu3gw22` sends its first transaction, the pubkey becomes available.

**Comment by webmaster128** [comment]
[cosmos1unc788q8md2jymsns24eyhua58palg5kc7cstv](https://www.mintscan.io/cosmos/account/cosmos1unc788q8md2jymsns24eyhua58palg5kc7cstv) on the other hand has outgoing transactions, which is why you have a high sequence and a pubkey:


```ts
import { StargateClient } from "@cosmjs/stargate";

const client = await StargateClient.connect("https://rpc.cosmos.network");
const account = await client.getAccount("cosmos1unc788q8md2jymsns24eyhua58palg5kc7cstv");

console.log(account);
```

gives

```
{
  address: 'cosmos1unc788q8md2jymsns24eyhua58palg5kc7cstv',
  pubkey: {
    type: 'tendermint/PubKeyMultisigThreshold',
    value: { threshold: '2', pubkeys: [Array] }
  },
  accountNumber: 22545,
  sequence: 70
}
```

**Comment by samepant** [comment]
Ah ok, that makes a lot of sense. I was hoping for a way I wouldn't have to store pubkeys for newly created multisigs, but it sounds like I will have to until they broadcast their first transaction.

Thanks for the prompt answer!

**Comment by webmaster128** [comment]
Yeah, this is a bit tricky. The signers do not need the full multisig pubkey. However, the broadcaster that collects all the signatures and composes the signed transaction needs to get it. And it is not on chain before the first outgoing transaction.
