### ISSUE TITLE
Move Proto-Signing out of Stargate

### ISSUE THREAD

**Issue by jsockchain** [cosmos/cosmjs#768]
I just dont know why we need to keep proto-signing in stargate.

This ruins everything now.

![image](https://user-images.githubusercontent.com/54032883/115399632-6b39c500-a1b6-11eb-8b4e-38bc2debbcb4.png)

**Comment by webmaster128** [comment]
There is a god amount of places where it is used in `@cosmjs/stargate` and I don't think it is a good idea to give up the dependency:

```
src/accounts.ts:import { decodePubkey } from "@cosmjs/proto-signing";
src/aminotypes.spec.ts:import { coin, coins } from "@cosmjs/proto-signing";
src/aminotypes.ts:import { EncodeObject } from "@cosmjs/proto-signing";
src/fee.ts:import { coins } from "@cosmjs/proto-signing";
src/index.ts:export { Coin, coin, coins, parseCoins } from "@cosmjs/proto-signing";
src/multisignature.spec.ts:import { coins } from "@cosmjs/proto-signing";
src/multisignature.ts:import { encodePubkey } from "@cosmjs/proto-signing";
src/queries/auth.spec.ts:import { encodePubkey } from "@cosmjs/proto-signing";
src/queries/distribution.spec.ts:import { coin, coins, DirectSecp256k1HdWallet } from "@cosmjs/proto-signing";
src/queries/staking.spec.ts:import { coin, coins, DirectSecp256k1HdWallet } from "@cosmjs/proto-signing";
src/signingstargateclient.spec.ts:import { coin, coins, DirectSecp256k1HdWallet, Registry } from "@cosmjs/proto-signing";
src/signingstargateclient.ts:} from "@cosmjs/proto-signing";
src/stargateclient.searchtx.spec.ts:} from "@cosmjs/proto-signing";
src/stargateclient.spec.ts:} from "@cosmjs/proto-signing";
src/testutils.spec.ts:} from "@cosmjs/proto-signing";
```

Why is this a problem? What does this ruin?

**Comment by jsockchain** [comment]
Maybe this is just my case but it took hours to figure out the Register is moved.

Old code
```
import { Registry } from '@cosmjs/proto-signing';
```

New code
```
import {Registry} from '@cosmjs/stargate/node_modules/@cosmjs/proto-signing';
```

**Comment by webmaster128** [comment]
This definitely looks wrong: `import {Registry} from '@cosmjs/stargate/node_modules/@cosmjs/proto-signing';`. Maybe your IDE thought this is a good import path. Usually you should only import from the top level of the packages.

```js
import { Registry } from '@cosmjs/proto-signing';
```

is correct for 0.24 and 0.25 (pre-release).

**Comment by jsockchain** [comment]
I imported it manually. 
If I import Registry from `@cosmjs/proto-signing` like below
```
import {Registry} from '@cosmjs/proto-signing';
```

It gives me the following error.

![image](https://user-images.githubusercontent.com/54032883/115402522-793d1500-a1b9-11eb-987e-36b5ecce2f32.png)

**Comment by webmaster128** [comment]
Yeah, this is because you insrtalled two different versions of @cosmjs/proto-signing

**Comment by jsockchain** [comment]
Oh do I have to update proto-signing to v25 alpha?

**Comment by webmaster128** [comment]
What version of @cosmjs/stargate are you using? Can you show your package.json?

But ideally all `@cosmjs/*` use the same version.

**Comment by jsockchain** [comment]
```
    "@cosmjs/proto-signing": "^0.24.1",
    "@cosmjs/stargate": "0.25.0-alpha.2",
```
This is what I've got for now but I got the point.
I will update `proto-signing` to 0.25.0-alpha.2 now.

**Comment by webmaster128** [comment]
Yeah this causes your registry to have the 0.24 type which you cannot use with a 0.25 stargate.
