### ISSUE TITLE
Use gnused in all scripts

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#784]
Looking at `sed -i` compatibility between the GNU implementation and the BSD implementation it turns out there is no simple trick to get this right (see https://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux).

I wondered why `sed -ie 's/^cors_allowed_origins =.*$/cors_allowed_origins = ["*"]/' "${TMP_DIR}/config/config.toml"` works in the Tendermint start script. Turns out this is pure luck. The `e` is interpreted as a value to `-i` and creates a `config.tomle` in the same folder. And the expression is not working because it is a value to `-e` but a positional argument.

So in order to avoid unnecessary confusion, we should use gnu sed for all scripts that use in-place and should work on Mac and Linux: https://github.com/CosmWasm/cosmwasm/blob/v0.14.0-rc1/devtools/set_version.sh#L5

**Comment by ethanfrey** [comment]
Sound good to me
