### ISSUE TITLE
Remove package cosmwasm-launchpad

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#786]
Nobody seems to be using this.

- [x] Let cosmwasm-stargate not depend on cosmwasm-launchpad anymore (#848)
- [x] Merge `packages/cli/examples/coralnet.ts` and `packages/cli/examples/helpers.ts` into a new CosmWasm+Stargatre example (#849)
- [x] Delete cosmwasm-launchpad from repo (850)
- [x] Mark [@cosmjs/cosmwasm-launchpad](https://www.npmjs.com/package/@cosmjs/cosmwasm-launchpad) and [@cosmjs/cosmwasm](https://www.npmjs.com/package/@cosmjs/cosmwasm) as deprecated on npm

**Comment by ethanfrey** [comment]
I don't know if Terra or Secret are using this. Or they are maintaining their own forks?

@YunSuk-Yeo could you comment for Terra?
@reuvenpo could you comment for Secret?

We can also discuss this on Discord if you are using CosmJS and need this support still.
Everyone else should be on stargate already.

**Comment by reuvenpo** [comment]
We use a forked version of CosmJS so I don't think any changes to CosmJS will directly affect us, but I'll let @assafmo comment on this

**Comment by assafmo** [comment]
Yeah, we unfortunately have our own fork. A few months ago [I suggested extending CosmJS' API a bit](https://github.com/cosmos/cosmjs/issues/512) so that Secret Network would be able to use it directly and benefit from the progress you guys are making. Let me know what I can do to make this happen. :relaxed:

**Comment by ethanfrey** [comment]
@assafmo thanks for the answer. My memory was you were going to try to [wrap CosmWasmSigner](https://github.com/cosmos/cosmjs/issues/512#issuecomment-749034621) rather than the message transformed idea. 

Did you try that? Did it hit issues?

Also, are you planning to upgrade to stargate soon? In which case we can just close this and ensure there is a nice path for core reuse with `cosmwasm-stargate`

**Comment by assafmo** [comment]
No, I didn't try yet to wrap CosmWasmSigner. I should though...

Yes, we will upgrade to Stargate somewhere this year, but I'm not sure if we'll upgrade our CosmWasm version as well, to not break existing contacts. We'll probably just backport bug fixes you guys made in the past 9 months. Is this a problem with CosmJS?

**Comment by ethanfrey** [comment]
You will need to fork. Support is mainly with wasmd version.

If you will not be running exactly one of our wasmd versions, we will not guarantee support.

**Comment by assafmo** [comment]
Okay, thanks for the info. We'll try to figure out what's the best approach for us.

**Comment by ethanfrey** [comment]
Correction: `x/wasm` versions. Of course we expect you to embed it in your app (and I think you swap out with a custom `wasmvm` which is great for your use case). The main point is it is tested with a certain set of messages and queries and handlers and if those differ, the CosmJS code may not match. 

With stargate we put more effort into making it generic. Thus, you could import all the standard components and build `SigningSecretClient` on those same basic points, not wrapping `SigningCosmWasmClient` but at the same level as it. That means, just one package for you to maintain and the rest is upstream.

**Comment by webmaster128** [comment]
Given that Secret uses a fork of CosmJS anyways and there is [great potential to reuse latest upstream dependencies](https://github.com/enigmampc/SecretNetwork/issues/747), we'll remove the package now. I think replacing some of the higher level functionality with a fork while building on top of lower level CosmJS packages is a solid long term solution.

**Comment by webmaster128** [comment]
Done 🐎
