### ISSUE TITLE
Move generated types into dedicated repository

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#799]
Users of CosmJS currently need to generate their own types from proto files if they want to build something non-trivial. This is a burden we can reduce at least as long as common cosmos types are used.

Some of those projects are:
- ts-relayer: https://github.com/confio/ts-relayer/tree/main/src/codec
- interchain-accounts-client: https://github.com/Ryan-Gordon/interchain-accounts-client/tree/master/src/codec
- CosmJS itself

Those types are generated the same way we show and I think it is safe to assume that whatever code generation options we suggest good for the majority of our users. We should make clear that the code generation is opinionated and CosmJS specific.

The types should be compiled from .proto to .ts and from .ts to .d.ts/.js. This makes them much easier to access from JavaScript-only users because they do not need a TypeScript compiler on their end (see also https://github.com/cosmos/cosmjs/issues/778).

I think we should create a monorepo that has different output folders and different npm packages for the namespaces. Typical folders are

```
$ ls src/codec 
confio     cosmos     google     ibc        intertx    tendermint
```

or

```
$ ls src/codec/
cosmos   cosmwasm google
```

which we can publish as `@typesnamespace/confio` etc. I would imagine an import to look like this:

```js
import { MsgSend } from "@typesnamespace/cosmos/bank/v1beta1/tx";

let msg = MsgSend.fromPartial({ /* ... */ });
```

This has a bunch of advantages for CosmJS development:
- No ts-proto installation needed here
- Faster builds by using pre-compiled types
- We can recommend to never import from sub-folder instead of seeing thinks like `import { MsgSend } from "@cosmjs/stargate/build/codec/cosmos/bank/v1beta1/tx";`

The same has been done in [cosmos_sdk_proto](https://docs.rs/cosmos-sdk-proto/0.5.0/cosmos_sdk_proto/index.html) for Rust. This is not generic Rust but code generation specific to [prost](https://crates.io/crates/prost). I like the use of git submodules as a .proto source in https://github.com/cosmos/cosmos-rust.

**Comment by seantking** [comment]
Great idea :+1: Let me know where I can help with this. 

Questions that come to mind:

1. Who maintains this and where does the repo live?
2. What is the process for someone adding a new type namespace?

In my experience in the past with having a shared library for types, things can get messy fast without strict rules. 

Every time a developer changes the model they will need to make a PR here also to keep things up to date for their `typenamespace`. I found this has its downsides also and likely won't happen all the time.

**Comment by webmaster128** [comment]
Thanks @seantking, good points.

My understanding is this would be fully owned by the CosmJS maintenance team and made to serve CosmJS and its users.

Regarding what to include: In the beginning I'd only include "common" types, i.e. types that are not chain specific. To me this includes tendermint, Cosmos SDK, well established externally maintained modules like x/wasm or x/evm and interchain standards.

> Every time a developer changes the model they will need to make a PR here also to keep things up to date for their typenamespace. I found this has its downsides and likely won't happen all the time.

At least all the types that are maintained in common repos can be udated by simply updating a git tag. This can be implemented like this: https://github.com/cosmos/cosmjs/blob/v0.25.2/packages/stargate/package.json#L40 or by using git submodules. Then all the type changes that happened in the reposotory between the two tags will automatically be updated for the type generation. So no need to keep track of every change individually.

**Comment by seantking** [comment]
```
My understanding is this would be fully owned by the CosmJS maintenance team and made to serve CosmJS and its users.
```
Sounds good! Are you thinking this lives on the cosmos github org or inside confio's? 

```
Regarding what to include: In the beginning I'd only include "common" types, i.e. types that are not chain specific. To me this includes tendermint, Cosmos SDK, well established externally maintained modules like x/wasm or x/evm and interchain standards.
```

Makes sense to me. 

```
At least all the types that are maintained in common repos can be udated by simply updating a git tag. This can be implemented like this: https://github.com/cosmos/cosmjs/blob/v0.25.2/packages/stargate/package.json#L40 or by using git submodules. Then all the type changes that happened in the reposotory between the two tags will automatically be updated for the type generation. So no need to keep track of every change individually.
```

Aha, this is a sleeker approach. I like it. :+1:

**Comment by webmaster128** [comment]
> Are you thinking this lives on the cosmos github org or inside confio's?

I don't mind and we can easily move the repo around. The npm namespace would stay the same. I suggest getting it started in confio and move it to cosmos once stable. But I'm open here.

**Comment by seantking** [comment]
> I don't mind and we can easily move the repo around. The npm namespace would stay the same. I suggest getting it started in confio and move it to cosmos once stable. But I'm open here.

Yep, this sounds like the best move.

**Comment by webmaster128** [comment]
Created the npm org cosmjs-types, which would be the prefix for the packages. E.g. `@cosmjs-types/cosmos`, `@cosmjs-types/ibc`, `@cosmjs-types/tendermint`. Does this work? Better ideas?

**Comment by seantking** [comment]
I think that's fine :+1:
