### ISSUE TITLE
bug: New broadcast logic hides errors

### ISSUE THREAD

**Issue by clockworkgr** [cosmos/cosmjs#800]
The latest implementation of broadcastTx that polls the chain for the tx result hides all pre-commit errors.

https://github.com/cosmos/cosmjs/blob/main/packages/stargate/src/stargateclient.ts#L329

This will return a timeout error for any kind of invalid transaction including insufficient fees. etc.

**Comment by webmaster128** [comment]
This would explain the bahaviour described in https://github.com/confio/ts-relayer/issues/180

**Comment by clockworkgr** [comment]
ah..never noticed that issue....same thing happened to us and I just worked back through the code and found it :)

fwiw, ibc-setup costs about 2.2m gas on each chain

**Comment by webmaster128** [comment]
Fix is in #805. Happy for any 👀 on it.

**Comment by webmaster128** [comment]
Released as 0.25.3
