### ISSUE TITLE
Hermes compatibility

### ISSUE THREAD

**Issue by AlexBHarley** [cosmos/cosmjs#801]
Just wanted to flag that something in the `@cosmjs/stargate` package breaks in [Hermes](https://hermesengine.dev/). Basically requiring the package yields undefined. 

If I find anything I'll update this issue.

**Comment by AlexBHarley** [comment]
I've nailed it down to this line

```
export const defaultGasPrice = GasPrice.fromString("0.025ucosm");
```

In `cosmjs/packages/stargate/src/signingstargateclient.ts`

**Comment by AlexBHarley** [comment]
This is the regex it doesn't like, `const matchResult = gasPrice.match(/^(?<amount>.+?)(?<denom>[a-z]+)$/);` because Hermes doesn't support Regex groups https://github.com/facebook/hermes/issues/89.

**Comment by webmaster128** [comment]
Thanks for bringing this up. I was not aware of any regex syntax change. I would have expected that TypeScript converts this or errors since our target is es2017. There is a TypeScript bug that describes this problem: https://github.com/microsoft/TypeScript/issues/36132.
