### ISSUE TITLE
Getblock

### ISSUE THREAD

**Issue by puffanddmx** [cosmos/cosmjs#812]
Hi
If i use block decoder for getting block, it shows the human readable type.
But inside the block, there are no transaction hash information of each txs inside block. How to get txs hash inside the block using block decoder? 
Also if i do the block decoder for the message txs, there are info but format is not this type(from,to,amount).
How to extract that type using block decoder?

**Comment by trien-tran** [comment]
i am stuck like you, have you solved that problem?

**Comment by puffanddmx** [comment]
Yep
Message me on telegram
gogojay1
