### ISSUE TITLE
for the transaction hash

### ISSUE THREAD

**Issue by puffanddmx** [cosmos/cosmjs#817]
hi 

i have a question!

before doing client.broadcastTx, can i get the transaction hash with the sdk when i do the signtransaction?

**Comment by willclarktech** [comment]
Hi @puffanddmx, for support questions like this these Discord channels are probably best:
- CosmJS on Cosmos Community: https://discord.com/channels/669268347736686612/720700683460018186
- CosmJS on CosmWasm: https://discord.com/channels/737637324434833438/737640557400293416
