### ISSUE TITLE
Feature Request: Add HD configurable path support for Faucet.

### ISSUE THREAD

**Issue by puneet2019** [cosmos/cosmjs#832]
Currently In package `faucet` the HD path Is hardcoded as `makeCosmoshubPath`. We can make it configurable.

**Comment by webmaster128** [comment]
We can make this configurable with an environment variable like `FAUCET_PATH_PATTERN="m/44'/118'/0'/0/a"` where `a` is then replaced with the account index.

**Comment by webmaster128** [comment]
Could you have a look at #852 to check if that fits your needs?

**Comment by puneet2019** [comment]
yes! that would work
