### ISSUE TITLE
Add gov module support for stargate (QueryClient + EncodeObjects)

### ISSUE THREAD

**Issue by jnaviask** [cosmos/cosmjs#841]
Hi all, I'm migrating our governance project from Launchpad to Stargate and the lack of gov types for Stargate is causing some trouble.

If we continue using Launchpad queries, we maintain a limited degree of support, likely through some backwards compatibility at the REST layer, but I'm effectively unable to make any transactions. Would love to see support for governance in the Stargate package. Thanks!

**Comment by webmaster128** [comment]
@cosmjs/stargate does indeed not ship a `GovExtension` for `QueryClient`. @cosmjs/launchpad has it.

Starting with CosmJS we'll do the code generation for the proto types externally. Could you try to build a `GovExtension` and message support using the types from [cosmjs-types](https://github.com/confio/cosmjs-types)? You can include them as follows:

```js
import { MsgVote } from "cosmjs-types/cosmos/gov/v1beta1/tx"

// and

import {
  QueryClientImpl,
  QueryProposalsRequest,
  QueryProposalsResponse,
} from "cosmjs-types/cosmos/gov/v1beta1/query";
```

**Comment by webmaster128** [comment]
Could you check if #856 is what you are looking for?

**Comment by jnaviask** [comment]
Yes, that's exactly what we need!

**Comment by webmaster128** [comment]
Great. It should be straight forward to copy over the port to your app and make it CosmJS 0.25 compatible. Otherwiese you need to wait for a 0.26 pre-release which will happen at some point this week or early August.

**Comment by jnaviask** [comment]
Excellent, I'll wait for 0.26 and then it should be a fairly straightforward set of changes. Thank you so much for this!
