### ISSUE TITLE
cw20_base::msg::QueryMsg: missing field `address`: query wasm contract failed: invalid request

### ISSUE THREAD

**Issue by randomshinichi** [cosmos/cosmjs#858]
cosmjs 0.25.6

Executing this code
```
	const account = await getWalletAccount();
	const wallet = await getWalletData();
	const client = await SigningCosmWasmClient.connectWithSigner(RPC_ENDPOINT, wallet, options);

	var c = readContractsJson()
	const token = CW20(client).use(c.cw20.contractAddress);
	var balance = await token.balance(account.address)
	console.log(account.address, "balance in CW20", balance)

// Sending CW20 to DORCP contract instance
	var transfer = await client.execute(account.address, c.cw20.contractAddress, {transfer: {recipient: c.dorcp.contractAddress, amount: "1000"}});
	console.dir(transfer, {depth: null})
```
results in
```
Error: Query failed with (18): Error parsing into type cw20_base::msg::QueryMsg: missing field `address`: query wasm contract failed: invalid request
    at QueryClient.queryUnverified (/home/shinichi/source/work/cosmos/dorium-contracts/node_modules/@cosmjs/stargate/src/queries/queryclient.ts:582:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.queryContractSmart (/home/shinichi/source/work/cosmos/dorium-contracts/node_modules/@cosmjs/cosmwasm-stargate/src/queries/wasm.ts:116:26)
    at SigningCosmWasmClient.queryContractSmart (/home/shinichi/source/work/cosmos/dorium-contracts/node_modules/@cosmjs/cosmwasm-stargate/src/cosmwasmclient.ts:379:14)
```

**Comment by webmaster128** [comment]
You are getting an error in `SigningCosmWasmClient.queryContractSmart` (see stack trace). Could you provide the code where this is executed? Where do you get `CW` from?

**Comment by randomshinichi** [comment]
> Could you provide the code where this is executed?
I don't know what you mean, the stack trace indicates that this comes from @cosmjs/stargate/src/queries/queryclient.ts, i.e. your code. In my node_modules directories, I only have `build/`, not `src/`

CW20 comes from https://github.com/CosmWasm/cosmwasm-plus/blob/main/contracts/cw20-base/helpers.ts but I did not use its method. Instead, to troubleshoot, I did what its transfer method does directly, which is call `SigningCosmWasmClient.execute()`.

**Comment by ethanfrey** [comment]
The error is coming from 

> 	var balance = await token.balance(account.address)

I am not sure helpers.ts is properly tested, and until recently I know it was broken (I think it got fixed like 2-3 weeks ago). Maybe you could pull out the lines from that into your script (not use CW20 type, but inline what the method does)? That would make it clearer to debug.

**Comment by randomshinichi** [comment]
Seems like the error was in my code after all. I had to change it to

`const result = await client.queryContractSmart(c.cw20.contractAddress, {balance: { 'address': account.address }});`
