### ISSUE TITLE
Secure websocket connection

### ISSUE THREAD

**Issue by samepant** [cosmos/cosmjs#868]
I'm attempting to broadcast a transaction using a client created with  `await StargateClient.connect(nodeAddress)`. Chrome then complains:
```
Mixed Content: The page at 'https://cosmoshub-legacy-multisig.vercel.app/multi/cosmos10nmdf6nt2qzvgn9q2nuwmmfc359yfesmu3gw22/transaction/307135408288825924' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://143.198.6.14:26657/websocket'. This request has been blocked; this endpoint must be available over WSS.
```

If I modify the site settings to allow for insecure content loading, everything works great.

Is there a way to enable a wss connection when creating a client? 

Thanks

**Comment by webmaster128** [comment]
You need to configure the endpoint to support wss. In order to use it, your endpoint need to start with `wss://`. The rest happens automatically.
