### ISSUE TITLE
Not able to sign wasm messages with Keplr connected to Ledger

### ISSUE THREAD

**Issue by ben2x4** [cosmos/cosmjs#875]
I have been looking into this issue for a few days as I have experienced this issue on my own project. Ledger does not support the protobuf message type and needs to fall back on the amino encoding. 

This issue can be repeated on the example dApps running on https://dapps.juno.giansalex.dev/wallet/.  

Is there a way to force CosmJS and Keplr to use the amino message type? I have tried `window.getOfflineSignerOnlyAmino(chainId: string)` as recommended in https://docs.keplr.app/api/cosmjs.html, but that seems to break the Keplr integration. 

Would love to know if there is an existing workaround for this issue. Going to keep investigating and see if I can identify a fix.

**Comment by ethanfrey** [comment]
Please check in with the keplr team as well.

**Comment by ethanfrey** [comment]
BTW, I would love to see a PR on https://github.com/cosmwasm/dapps

The code there has an old configuration (musselnet) and I would be happy to point it to some live network (juno testnet?). Can you please contribute there? It would also help investigate the issue if you share the source code you deployed.

**Comment by ben2x4** [comment]
Thanks for the response! I will check in with Keplr and will look into updating the dApps.

**Comment by giansalex** [comment]
@ben2x4 you need to use `getOfflineSignerAuto`
> Also, window.getOfflineSignerAuto(chainId: string): Promise<OfflineSigner | OfflineDirectSigner> or window.getOfflineSignerAuto(chainId: string): Promise<OfflineSigner | OfflineDirectSigner> API is supported. Please note that the value returned is async. **This API automatically returns a signer that only supports Amino if the account is a Ledger-based account, and returns a signer that is compatible for both Amino and Protobuf if the account is a mnemonic/private key-based account.**

**Comment by assafmo** [comment]
I can confirm that @giansalex comment solved this for me too! Leger signing started working after I switched `getOfflineSigner` for `getOfflineSignerAuto` ([code reference](https://github.com/scrtlabs/wrap.scrt.network/commit/eac0dbdef08dc553176b98b1e3adc5ed5e69e983)). :tada:

**Comment by webmaster128** [comment]
Is this still relevant? Feels like there are tons of moving parts and it is unclear what problem exactly remains.

**Comment by interphased** [comment]
I can also confirm @giansalex's suggestion to use `getOfflineSignerAuto` fixed my issue as well.

This issue seems likely resolved.
