### ISSUE TITLE
Support pagination on stargate gov.proposals().

### ISSUE THREAD

**Issue by jnaviask** [cosmos/cosmjs#877]
The proposals call returns a Pagination parameter in its result, but there's no way to use it with the current API design. Ideally the call would include an optional pagination key / other parameters relevant to pagination to allow us to fetch all proposals on a chain with >100 available.

**Comment by webmaster128** [comment]
Thanks for bringing this up. It was alrady present in the implementation but missing in the types. https://github.com/cosmos/cosmjs/pull/881 should make it available.

**Comment by webmaster128** [comment]
Released as part of 0.26.1
