### ISSUE TITLE
Decoding/parsing transactions

### ISSUE THREAD

**Issue by romon267** [cosmos/cosmjs#879]
Hello, I'm looking for some way to decode/parse transactions data to readable format. For example I query txs from gov module, that are proposal submission txs, I get the tx data and somehow I need to decode it to get readable data, like "proposer", "title" and "description" of proposal etc. I looked through packages, but wasn't able to find the needed functions, are there any docs on parsing txs data?

**Comment by webmaster128** [comment]
Heyho and welcome!

Parsing transactions is a two step process.

## 1. Parse `TxRaw`

Serialized [TxRaw](https://github.com/cosmos/cosmos-sdk/blob/v0.44.0/proto/cosmos/tx/v1beta1/tx.proto#L27-L45) is the structure in which transactions are stored in Tendermint. Those are the bytes you get e.g. in `.data.txs` from https://rpc.cosmos-hub.app.beta.starport.cloud/block.

To deserialize those bytes, use `import { decodeTxRaw } from "@cosmjs/proto-signing"`. A tests that shows how to use it is available in https://github.com/cosmos/cosmjs/pull/880.

## 2. Parse messages

The field `.body.messages` from `DecodedTxRaw` is an array of `Any`. You need to loop through them, look at `typeUrl` and use a type-specific decoder for each message. `Registry` can do that for you. With `createDefaultRegistry()` you get a registry that knows many standard Cosmos SDK types. You can add more if you want.

```ts
import { createDefaultRegistry } from "@cosmjs/stargate";
import { decodeTxRaw } from "@cosmjs/proto-signing"

const decoded = decodeTxRaw(bytes);

const registry = createDefaultRegistry();
for (const message of decoded.body.messages) {
    const decodedMsg = registry.decode(message);
}
```

**Comment by romon267** [comment]
@webmaster128 Hi, thank you for your answer, I tried your method, but currently I'm getting an error when trying to decode tx - `Unhandled Rejection (Error): invalid wire type 4 at offset 430`.
I'm getting txs from `http://localhost:26657/tx_search?` endpoint. And I'm trying to decode `CqkBCqQBCiUvY29zbW9zLmdvdi52MWJldGExLk1zZ1N1Ym1pdFByb3Bvc2FsEnsKPAogL2Nvc21vcy5nb3YudjFiZXRhMS5UZXh0UHJvcG9zYWwSGAoFMTExMTESD3N0YWtpbmcgaXMgc3VzIRIMCgVzdGFrZRIDMTAwGi1jb3Ntb3MxdWFqNDgyeTJrYXVwbjJ3MGc5cGFkdDV6aGhyaDJ4ZDVmOTl2c2oSABJmCk4KRgofL2Nvc21vcy5jcnlwdG8uc2VjcDI1NmsxLlB1YktleRIjCiEDVyrUWWGZR0S9QhfndH47TGGC9nC1cw3kcSXwmx2yxckSBAoCCAESFAoOCgVzdGFrZRIFNTAwMDAQgIl6GkCQZIqDkFBlIKL0+wkaSsVm0L3NXdvvuOMB1YnRFTPykmGOOtyaFbnUyORJx4np2uVfkWeoPg2b++2zL0syamdl` tx data, is this some wrong data format?

**Comment by webmaster128** [comment]
Are you sure the error belongs to the data you posted? This has less than 430 bytes:

```
echo "CqkBCqQBCiUvY29zbW9zLmdvdi52MWJldGExLk1zZ1N1Ym1pdFByb3Bvc2FsEnsKPAogL2Nvc21vcy5nb3YudjFiZXRhMS5UZXh0UHJvcG9zYWwSGAoFMTExMTESD3N0YWtpbmcgaXMgc3VzIRIMCgVzdGFrZRIDMTAwGi1jb3Ntb3MxdWFqNDgyeTJrYXVwbjJ3MGc5cGFkdDV6aGhyaDJ4ZDVmOTl2c2oSABJmCk4KRgofL2Nvc21vcy5jcnlwdG8uc2VjcDI1NmsxLlB1YktleRIjCiEDVyrUWWGZR0S9QhfndH47TGGC9nC1cw3kcSXwmx2yxckSBAoCCAESFAoOCgVzdGFrZRIFNTAwMDAQgIl6GkCQZIqDkFBlIKL0+wkaSsVm0L3NXdvvuOMB1YnRFTPykmGOOtyaFbnUyORJx4np2uVfkWeoPg2b++2zL0syamdl" | base64 -D | wc  
      14      20     342
```

Also check the raw protobuf decoder:

```
echo "CqkBCqQBCiUvY29zbW9zLmdvdi52MWJldGExLk1zZ1N1Ym1pdFByb3Bvc2FsEnsKPAogL2Nvc21vcy5nb3YudjFiZXRhMS5UZXh0UHJvcG9zYWwSGAoFMTExMTESD3N0YWtpbmcgaXMgc3VzIRIMCgVzdGFrZRIDMTAwGi1jb3Ntb3MxdWFqNDgyeTJrYXVwbjJ3MGc5cGFkdDV6aGhyaDJ4ZDVmOTl2c2oSABJmCk4KRgofL2Nvc21vcy5jcnlwdG8uc2VjcDI1NmsxLlB1YktleRIjCiEDVyrUWWGZR0S9QhfndH47TGGC9nC1cw3kcSXwmx2yxckSBAoCCAESFAoOCgVzdGFrZRIFNTAwMDAQgIl6GkCQZIqDkFBlIKL0+wkaSsVm0L3NXdvvuOMB1YnRFTPykmGOOtyaFbnUyORJx4np2uVfkWeoPg2b++2zL0syamdl" | base64 -D | protoc --decode_raw
1 {
  1 {
    1: "/cosmos.gov.v1beta1.MsgSubmitProposal"
    2 {
      1 {
        1: "/cosmos.gov.v1beta1.TextProposal"
        2 {
          1: "11111"
          2: "staking is sus!"
        }
      }
      2 {
        1: "stake"
        2: "100"
      }
      3: "cosmos1uaj482y2kaupn2w0g9padt5zhhrh2xd5f99vsj"
    }
  }
  2: ""
}
2 {
  1 {
    1 {
      1: "/cosmos.crypto.secp256k1.PubKey"
      2 {
        1: "\003W*\324Ya\231GD\275B\027\347t~;La\202\366p\265s\r\344q%\360\233\035\262\305\311"
      }
    }
    2 {
      1 {
        1: 1
      }
    }
  }
  2 {
    1 {
      1: "stake"
      2 {
        6: 0x30303030
      }
    }
    2: 2000000
  }
}
3: "\220d\212\203\220Pe \242\364\373\t\032J\305f\320\275\315]\333\357\270\343\001\325\211\321\0253\362\222a\216:\334\232\025\271\324\310\344I\307\211\351\332\345_\221g\250>\r\233\373\355\263/K2jge"
```

**Comment by romon267** [comment]
@webmaster128 Yes, I pass exactly this `CqkBCqQBCiUvY29zbW9zLmdvdi52MWJldGExLk1zZ1N1Ym1pdFByb3Bvc2FsEnsKPAogL2Nvc21vcy5nb3YudjFiZXRhMS5UZXh0UHJvcG9zYWwSGAoFMTExMTESD3N0YWtpbmcgaXMgc3VzIRIMCgVzdGFrZRIDMTAwGi1jb3Ntb3MxdWFqNDgyeTJrYXVwbjJ3MGc5cGFkdDV6aGhyaDJ4ZDVmOTl2c2oSABJmCk4KRgofL2Nvc21vcy5jcnlwdG8uc2VjcDI1NmsxLlB1YktleRIjCiEDVyrUWWGZR0S9QhfndH47TGGC9nC1cw3kcSXwmx2yxckSBAoCCAESFAoOCgVzdGFrZRIFNTAwMDAQgIl6GkCQZIqDkFBlIKL0+wkaSsVm0L3NXdvvuOMB1YnRFTPykmGOOtyaFbnUyORJx4np2uVfkWeoPg2b++2zL0syamdl` to the `decodeTxRaw()` method from `"@cosmjs/proto-signing"` and it throws an error, I attach the screenshot. 
![image](https://user-images.githubusercontent.com/37986442/135095282-13abea46-821e-43f2-b3c3-d1f27e467278.png)

**Comment by webmaster128** [comment]
Did you forget to do base64 decoding (`const data = fromBase64("mybase64string")`)? Can you share the relevant code?

**Comment by romon267** [comment]
@webmaster128 Ah, yes I don't decode base64... Here is the code snippet 
```
export const getProposalsHistory = async (
    rpcEndpoint: string,
    registry: Registry
): Promise<any[]> => {
    const txs = await axios.get(
        `${rpcEndpoint}/tx_search?query="message.action='submit_proposal'"`
    );
    const parsedTxs = [];
    for (const tx of txs.data.result.txs) {
        parsedTxs.push(parseTx(tx.tx, registry));
    }

    return parsedTxs;
};

export const parseTx = (tx: any, registry: Registry) => {
    const decoded = decodeTxRaw(tx);
    const parsedData = [];

    for (const message of decoded.body.messages) {
        const decodedMsg = registry.decode(message);
        parsedData.push(decodedMsg);
    }

    return parsedData;
};
```
where should I add base64 decoding?

**Comment by webmaster128** [comment]
I suggest this way:

```ts
export const parseTx = (tx: string, registry: Registry) => {
    const decoded = decodeTxRaw(fromBase64(tx));
    const parsedData = [];

    for (const message of decoded.body.messages) {
        const decodedMsg = registry.decode(message);
        parsedData.push(decodedMsg);
    }

    return parsedData;
};
```

and then inspect what `tx` and `tx.tx` in the caller code is.

**Comment by romon267** [comment]
@webmaster128 This solved my error, now I can can properly parse txs, thank you!

**Comment by vedantzeb** [comment]
It seems like the createDefaultRegistry() function has been removed. 

I'm trying to create a new registry 
```
const registry = new Registry
```
and decode the transactions using the same code but getting this error:
```Error: Unregistered type url: /ibc.applications.transfer.v1.MsgTransfer```

**Comment by webmaster128** [comment]
@vedantzeb right! `createDefaultRegistry()` was never public.

What you can do instead is

```ts
import {
  defaultRegistryTypes as defaultStargateTypes,
  SigningStargateClient,
} from "@cosmjs/stargate";

const registry = new Registry(defaultStargateTypes /* this contains /ibc.applications.transfer.v1.MsgTransfer */);
// myRegistry.register("/my.custom.MsgXxx", MsgXxx);
```

**Comment by EugeneTeu** [comment]
hey @webmaster128, im trying to do the above (registry) but for `osmosis` chain. Getting an error with 
`Error: Unregistered type url: /osmosis.gamm.v1beta1.MsgSwapExactAmountIn` 

i dug into the source code and i believe i need the proto for this type to register with the `registry` right? any idea how i could find it ? https://github.com/osmosis-labs/osmosis/blob/main/proto/osmosis/gamm/v1beta1/tx.proto I  found this but wasnt too sure how to add it to the `registry`

**Comment by trien-tran** [comment]
how can i get transaction hash aflter decode tx raw?

**Comment by joost-quro** [comment]
> @vedantzeb right, my fault! `createDefaultRegistry()` was never public.
> 
> What you can do instead is
> 
> ```ts
> import {
>   defaultRegistryTypes as defaultStargateTypes,
>   SigningStargateClient,
> } from "@cosmjs/stargate";
> 
> const registry = new Registry(defaultStargateTypes /* this contains /ibc.applications.transfer.v1.MsgTransfer */);
> // myRegistry.register("/my.custom.MsgXxx", MsgXxx);
> ```

Did you ever get it right? I am having the same issue.

**Comment by cosmosman-jay** [comment]
have you solved it ,sir?

**Comment by alienHunterOnMars** [comment]
So the decoding txs is working for me but i also need emitted events against the txs for properly indexing the state. can anyone point me to where i can find the events emitted by these txs ?

**Comment by erba** [comment]
@webmaster128 Your not a solution.

```
import {
  defaultRegistryTypes as defaultStargateTypes,
  SigningStargateClient,
} from "@cosmjs/stargate";

const registry = new Registry(defaultStargateTypes /* this contains /ibc.applications.transfer.v1.MsgTransfer */);
// myRegistry.register("/my.custom.MsgXxx", MsgXxx);
```

Where did you find the Registry class? Could you guys document the stuff a bit better.
Using CosmJS is the same as the rest of the Cosmos SDK. No usable documentation whatsoever.

**Comment by FidelVe** [comment]
> @webmaster128 Your code is not a solution unfortunately.
> 
> ```
> import {
>   defaultRegistryTypes as defaultStargateTypes,
>   SigningStargateClient,
> } from "@cosmjs/stargate";
> 
> const registry = new Registry(defaultStargateTypes /* this contains /ibc.applications.transfer.v1.MsgTransfer */);
> // myRegistry.register("/my.custom.MsgXxx", MsgXxx);
> ```
> 
> Where did you find the Registry class? Could you guys document the stuff a bit better. Using CosmJS is the same as the rest of the Cosmos SDK. No usable documentation whatsoever.

I have the same question, where can I find the `Registry` class?

**Comment by cwilvx** [comment]
In case anyone is still wondering where the `Registry` class is:
```js
import { Registry } from '@cosmjs/proto-signing';
```

**Comment by david-zenx** [comment]
how to get the transaction status. whether transaction in the blocks is succeeded or failed by decoding 
 txraw or txhash,

**Comment by david-zenx** [comment]
i had transacation listener for get the new  transaction added in the node, i used tendermint websocket but some times the lsitener not listening some transactions.
