### ISSUE TITLE
Upgrade yarn to version 3

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#888]
See https://dev.to/arcanis/yarn-3-0-performances-esbuild-better-patches-e07

Should fix

```
### Maybe don’t use Node v15+ until you upgrade to Yarn v3(!!!)

It might not affect you but there’s an issue with the `fs` patch and `bigint`,
which is solved in v3, but won’t be backported to v2:
https://github.com/yarnpkg/berry/issues/2232#issuecomment-818514929
```

from https://github.com/cosmos/cosmjs/blob/v0.26.1/docs/YARN.md

**Comment by ethanfrey** [comment]
So.... v2 still has limited support and they move to v3 already? oof.

**Comment by webmaster128** [comment]
v3 is the better v2. No huge difference. If you are interested, see the blog artice. It's interesting and shows there was a huge change between v1 and v2 and now it gets smoother. The article also addresses some frustration of users.
