### ISSUE TITLE
Text Encoder/Decoder fallbacks

### ISSUE THREAD

**Issue by AlexBHarley** [cosmos/cosmjs#895]
A recent commit removing the TextEncoder/Decoder fallbacks broke our React Native application.

Why were these removed?

**Comment by webmaster128** [comment]
See https://github.com/cosmos/cosmjs/issues/811. The assumption there is

> Remove all Buffer fallbacks in packages/encoding/src/utf8.ts because TextEncoder and TextDecoder are now globally available in all supported environments

We could add them back. But on the other hand why does the JavaScriot environment not provide them for us in React Native?

**Comment by webmaster128** [comment]
Feel free to reopen if you think we should bring back the fallback. For missing JavaScript APIs it's not simple to tell who to blame as the available APIs are always different in different environments.
