### ISSUE TITLE
Broadcasting authz transactions

### ISSUE THREAD

**Issue by romon267** [cosmos/cosmjs#899]
I'm working on web interface for authz module and I'm trying to broadcast MsgGrant/MsgRevoke transactions. It's not working properly and I'm getting those errors: `"failed to execute message; message index: 0: doesn't exist.: invalid type"`, `"Broadcasting transaction failed with code 2 (codespace: sdk). Log: errUnknownField "*authz.GenericAuthorization": {TagNum: 4, WireType:"fixed64"}: tx parse error"`. The code is here: https://github.com/cosmos/admin-module/blob/versions-fixes/react/src/redux/action-creator/authz.ts
I'm passing to broadcast the following object:
![selection](https://user-images.githubusercontent.com/37986442/136914883-6cf56b3b-a35c-454a-8446-982bb572e8f6.png)
With the following data, and get the error, that is shown on screenshot:
![selection(1)](https://user-images.githubusercontent.com/37986442/136915158-402759aa-10f5-48ea-b5c8-296e864b97fe.png)

@webmaster128 Issue reopened

**Comment by webmaster128** [comment]
cosmjs-types 0.3 now shipts the authz and feegrant types. So if you want to use that instead of your own code generator, feel free to give it a try.

Please note that CosmJS still uses version 0.2 (#928), but you should be able to mix them for most use cases.
