### ISSUE TITLE
How I can verify signature?

### ISSUE THREAD

**Issue by berelton** [cosmos/cosmjs#912]
Hi, I am trying to make a login system using the keplr wallet.

```
const txMemo = "Hello World!"; // Here will be some salt from backend
        const signingClient = await SigningStargateClient.offline(
            offlineSigner
        );
        console.log("Address", accounts[0].address)
        const { bodyBytes, signatures } = await signingClient.sign(
            accounts[0].address,
            txMsgs,
            txFee,
            txMemo,
            signerData
          );
          console.log(bodyBytes, signatures);
          console.log(encode(bodyBytes));
          console.log(encode(signatures[0]));
```

Here is the consol.log output:
![image](https://user-images.githubusercontent.com/93058200/138868525-cce038cb-2b0e-4978-89e8-65af3e251419.png)

So I am getting the `encode(signatures[0])` as `e1GeuLoC9AssPiXKLhuX3TjCdVRDtbdFypd2ZXpeL5oJiJGihvwAlGyCl2BjBaeqq0W+EmcXtaMfF3PLiy7H7Q==`.

How I can verify this signature on the backend?
Backend is written on nodejs.

**Comment by webmaster128** [comment]
Pretty much how `experimentalAdr36Verify` is implemented in https://github.com/cosmos/cosmjs/pull/847
