### ISSUE TITLE
Why handling coin amount field using `Uint53`?

### ISSUE THREAD

**Issue by cdc-Hitesh** [cosmos/cosmjs#918]
Our team recently discovered an issue with using this coin amount with the approach as described in https://github.com/cosmos/cosmjs/blob/79396bfaa49831127ccbbbfdbb1185df14230c63/packages/amino/src/coins.ts#L12

What we can figure out was `Uint53` was unable to handle large values. 
What is the CosmJs team's rationale behind using Uint53? Any specific details?

Thanks

**Comment by webmaster128** [comment]
The `coin` helper function takes the amount as a `number`, which is more conveneient to write in most cases. However, the largest integer that the `number` type can hold without rounding is `Number.MAX_SAFE_INTEGER = 9007199254740991`, which is approx. 53 bits. The type `Uint53` ensures the input does not exceed `Number.MAX_SAFE_INTEGER`.

Could you describe your use case in which you need larger values? It can be done using strings directly and the `Uint64` class. However, working with such large values in JS in inconvenient.

**Comment by ethanfrey** [comment]
The Cosmos SDK does use big.Int and allows arbitrarily large numbers here.
As Simon says, anything over Uint53 must be string encoded, and it is unclear how to work with them well in JS land. Long can handle Uint64. Larger numbers (I assume you are working with Ethereum-like 18 decimal places?) would need bn.js or another big number library.

All of these are much more annoying to work with than simple `number`, so they are not default.

**Comment by cdc-Hitesh** [comment]
Thanks @webmaster128 @ethanfrey 

> Could you describe your use case in which you need larger values? It can be done using strings directly and the Uint64

As @ethanfrey  guessed it correctly we are dealing with EVM compatible version values as part of IBC transfers.
Even `Uint64` won't sustain our use case hence resorted to replacing `Uint53`  with `bignumber` library for our usecase.

Is `Cosmjs` team looking at supporting arbitrarily large numbers?

**Comment by webmaster128** [comment]
> Is `Cosmjs` team looking at supporting arbitrarily large numbers?

I think it already does of you skip the `coin` helper and create the coin manually or through your own `Coin` maker helper. Or is there anything else that needs to be adapted?

Regarding `coin` I think we can easily accept `number | string` as an amount argument to support both use cases.

**Comment by webmaster128** [comment]
Could you please have a look at https://github.com/cosmos/cosmjs/pull/923 to see if that serves your needs and the implementation is solid?

**Comment by webmaster128** [comment]
ping @cdc-Hitesh. Could you check out #923?

**Comment by cdc-Hitesh** [comment]
@webmaster128 
Yeah, that looks like an amazing implementation.

For now, I have written my own implementation matching almost yours.

Are you planning to merge it in a future version of cosmJs?

**Comment by webmaster128** [comment]
> For now, I have written my own implementation matching almost yours.
> 
> Are you planning to merge it in a future version of cosmJs?

I'd love to. The case is valid: an SDK coin is of arbitrary length and right now we only support up to 53 bit. This might be good for most users but we also want to support advanced use cases as long as they are in line with main Cosmos SDK development.

Ideally you can drop your own implementation and share the one in #923 with other CosmJS users.

**Comment by webmaster128** [comment]
Done in https://github.com/cosmos/cosmjs/pull/923. Will be released as partof the next 0.26.x.
