### ISSUE TITLE
Query delegationRewards not working properly

### ISSUE THREAD

**Issue by msteiner96** [cosmos/cosmjs#924]
Hi,

when calling delegationRewards or delegationTotalRewards, the responded amount seems random and is WAY to high. 

**Test example for rewards from a single validator:**

```javascript
    const tmClient = await Tendermint34Client.connect("https://rpc-juno.itastakers.com");
    const client = QueryClient.withExtensions(tmClient, setupDistributionExtension);
    const reward = await client?.distribution.delegationRewards("juno1qd3p79cd82hz8p20gr4gcqze33eauuka6929w0", "junovaloper1juczud9nep06t0khghvm643hf9usw45r23gsmr");
    console.log(reward);
```

Output:
```javascript
{ rewards: [ { denom: 'ujuno', amount: '1519502928575099600000' } ] }
```

**Test example for total rewards from all validators:**
```javascript
    const tmClient = await Tendermint34Client.connect("https://rpc-juno.itastakers.com");
    const client = QueryClient.withExtensions(tmClient, setupDistributionExtension);
    const reward = await client?.distribution.delegationTotalRewards("juno1qd3p79cd82hz8p20gr4gcqze33eauuka6929w0");
    console.log(reward);
```

Output:
```javascript
{
  rewards: [
    {
      validatorAddress: 'junovaloper1juczud9nep06t0khghvm643hf9usw45r23gsmr',
      reward: [Array]
    }
  ],
  total: [ { denom: 'ujuno', amount: '1519872422095573900000' } ]
}
```

In both cases, the amount is too high.

**Comment by msteiner96** [comment]
Okay found out what's the problem. 

For people with similar issues:
Seems that staking rewards are expressed in the minimal denomination, which means you need to divide by 1000000000000000000.

So the response is actually correct.

**Comment by webmaster128** [comment]
Jupp, the protobuf representation of Cosmos SDK's Decimal type is not exactly intuitive. 1000000000000000000 is 10**18, which comes from the 18 decimal places from the Decimal type.

**Comment by webmaster128** [comment]
See https://github.com/cosmos/cosmjs/wiki/What-can-CosmJS-do-for-me%3F#parse-cosmos-sdk-decimal-type for a new example how to use the `Decimal` type from @cosmjs/math to work with those values.
