### ISSUE TITLE
invalid response data format when querying testnet address

### ISSUE THREAD

**Issue by ap-justin** [cosmos/cosmjs#940]
Hi! I've been trying to get account data using `getAccount` using `SigningCosmosClient` and gets this error `Error: Unexpected response data format` which can be traced from here
```
function setupAuthExtension(base) {
    return {
        auth: {
            account: async (address) => {
                const path = `/auth/accounts/${address}`;
                const responseData = await base.get(path);
                if (responseData.result.type !== "cosmos-sdk/Account") {
                    throw new Error("Unexpected response data format");
                }
                return responseData;
            },
        },
    };
}
```

here's the results of my `getAccount` queries
when querying address in `https://api.testnet.cosmos.network:443` the result is
```
{
    "height": "284526",
    "result": {
        "type": "cosmos-sdk/BaseAccount",
        "value": {
            "address": "cosmos1epw9e02r3cdgem0c74847v2fm529rxatsm2v3x",
            "public_key": {
                "type": "tendermint/PubKeySecp256k1",
                "value": "Aili+kjInFCt97zozhB6r7XxvTtF1gjXjvqJuRqB/qFh"
            },
            "account_number": "160",
            "sequence": "11"
        }
    }
}
```

and when querying address in `https://bombay-lcd.terra.dev`
```
{
    "height": "6682223",
    "result": {
        "type": "core/Account",
        "value": {
            "address": "terra1epw9e02r3cdgem0c74847v2fm529rxatklsvnx",
            "public_key": {
                "type": "tendermint/PubKeySecp256k1",
                "value": "Aili+kjInFCt97zozhB6r7XxvTtF1gjXjvqJuRqB/qFh"
            },
            "account_number": "91824",
            "sequence": "3"
        }
    }
}

```
is there a way to get around this error of having different `result.type` 
`"core/Account"`
` "cosmos-sdk/BaseAccount"`
`cosmos-sdk/Account`

any enlightenment would be really appreciated!
Here's a live example
https://stackblitz.com/edit/react-ts-pezzyd?file=Keplr.tsx

**Comment by webmaster128** [comment]
The code you're using there is from the @cosmjs/launchpad client. Launhchpad referes to Cosmos SDK version 0.37-0.39. This is not used anymore by any major network I am aware of. You'll need to switch to @cosmjs/stargate.

**Comment by ap-justin** [comment]
Hi @webmaster128, I've tried to use stargate client but seems to only work on rpc endpoints - is that how it is?
I've updated https://stackblitz.com/edit/react-ts-pezzyd?file=Keplr.tsx with the stargate client. I am hopeful to make things work only with the REST endpoint.

**Comment by webmaster128** [comment]
> I've tried to use stargate client but seems to only work on rpc endpoints - is that how it is?

Exactly. Right now we solely support Tendermint RPC connections. In the future, support for gRPC is panned as well. The LCD API is not going to have a comeback.

**Comment by ap-justin** [comment]
Thank you ser @webmaster128 !
