### ISSUE TITLE
Checking `BaseAccount` in launchpad/auth.js

### ISSUE THREAD

**Issue by gsk967** [cosmos/cosmjs#954]
When i did `send ` method call I am getting the error 

When i request the account info by api `http://localhost:1317/auth/accounts/cosmos1hz7ytcz5eftcm6sy2crlprhmgey6z05k7rjjc8`
 
I am getting this 
```json
{"height":"6780","result":{"type":"cosmos-sdk/BaseAccount","value":{"address":"cosmos1hz7ytcz5eftcm6sy2crlprhmgey6z05k7rjjc8","account_number":"8"}}}
```
 
But in `auth.js` you are checking the `Account`

https://github.com/cosmos/cosmjs/blob/1d0f9f5096afd66238e7dfa1d7e5d2beb973b6e2/packages/launchpad/src/lcdapi/auth.ts#L71

**Comment by webmaster128** [comment]
@cosmjs/launchpad does not support Stargate chains. It's made for Cosmos SDK 0.37-0.39 backends.

**Comment by gsk967** [comment]
Thanks @webmaster128
