### ISSUE TITLE
Error: 404 page not found

### ISSUE THREAD

**Issue by arunsybex** [cosmos/cosmjs#957]
While try to sign Tx giving error

Error

![image](https://user-images.githubusercontent.com/20275068/144630206-241694b6-6828-4d63-b147-9d09f0132bb9.png)

`
var cosmjs = require('@cosmjs/launchpad')

async function main() {
          
      const wallet = await cosmjs.Secp256k1HdWallet.fromMnemonic(
            // your mnemonic here 👇
            "enlist hip relief stomach skate base shallow young switch frequent cry park", {
            prefix:"fetch"
            }
        );
      const [{ address }] = await wallet.getAccounts();
      console.log("Address:", address);
      
      // Ensure the address has some tokens to spend
      
      const lcdApi = "https://rpc-andromeda.fetch.ai";
      const client = new cosmjs.SigningCosmosClient(lcdApi, address, wallet);
      
      // check our balance
      const account = await client.getAccount();
      console.log("Account:", account);
      
      // Send tokens
      const recipient = "fetch1h8em6zhfpn7zhedxk2gulh5yvyhcr6thc0xh29";
      await client.sendTokens(recipient, coins(123, "uatom"));
}

main()

`

**Comment by webmaster128** [comment]
@cosmjs/launchpad only supports Cosmos SDK 0.37–0.39 backends. For all modern backends, you need to migrate to @cosmjs/stargate.

**Comment by arunsybex** [comment]
@webmaster128  Please provide some examples for Signing Txs.

**Comment by arunsybex** [comment]
Fixed by downgrading libs
