### ISSUE TITLE
Signature verification failed: when account number is 0

### ISSUE THREAD

**Issue by angelorc** [cosmos/cosmjs#961]
## Summary of Bug
When an account number `0` tries to sign any transaction through the lib `@cosmjs/proto-signing` always gets the following error: 

```
Broadcasting transaction failed with code 4 (codespace: sdk). Log: signature verification failed; please verify account number (0) and chain-id (localnet): unauthorized.
```

## Versions
- CosmJS - `v0.26.5`
- Cosmos-SDK - `v0.42.10`

## Step to Reproduce
1. Start a new chain `v0.42.10`
2. Add 2 accounts
3. Import the first (account 0) and the second (account 1) to Keplr
4. Connect keplr with your application `window.getOfflineSigner(chainId)`
5. Send tokens from the account 0
   ```
	{
		"typeUrl": "/cosmos.bank.v1beta1.MsgSend",
		"value": {
			"fromAddress": "bitsong1vgpsha4f8grmsqr6krfdxwpcf3x20h0q3ztaj2",
			"toAddress": "bitsong1vgpsha4f8grmsqr6krfdxwpcf3x20h0q3ztaj2",
			"amount": [
				{
					"amount": "1000000",
					"denom": "ubtsg"
				}
			]
		}
	}
	```
	- The transaction receive an error
	  ```
	  Broadcasting transaction failed with code 4 (codespace: sdk). Log: signature verification failed; please verify account number (0) and chain-id (localnet): unauthorized.
	  ```
6. Send tokens from the account 1
   ```
	{
		"typeUrl": "/cosmos.bank.v1beta1.MsgSend",
		"value": {
			"fromAddress": "bitsong1zm6wlhr622yr9d7hh4t70acdfg6c32kcv34duw",
			"toAddress": "bitsong1zm6wlhr622yr9d7hh4t70acdfg6c32kcv34duw",
			"amount": [
				{
					"amount": "1000000",
					"denom": "ubtsg"
				}
			]
		}
	}
	```
	- The transaction will pass `Successful Send`

## Side note
Looks like this error has already been reported in another issue: https://github.com/cosmos/cosmjs/issues/549

If instead we try to perform the same operation via command line (`bitsongd tx send.....`) no errors are found.

**Comment by webmaster128** [comment]
Could you try the same with a local wallet from CosmJS instead of Keplr? It's not unlikely that this is a bug in Keplr.

**Comment by angelorc** [comment]
I tryed with 
```
const { DirectSecp256k1HdWallet } = await import('@cosmjs/proto-signing')
const wallet = await DirectSecp256k1HdWallet.fromMnemonic(this.seed, {
  hdPaths: [await getHDPath(network.HDPath)],
  prefix: network.addressPrefix,
})
```
and the bug is related to Keplr. For some reason I didn't test it with a locawallet before. Sorry!
