### ISSUE TITLE
Faucet limit from draining

### ISSUE THREAD

**Issue by skosito** [cosmos/cosmjs#962]
Hey,

Is there currently a way in the faucet to limit faucet users from draining it, like IP rate limiter per day or something like that, which would prevent somebody from spamming the faucet?

**Comment by webmaster128** [comment]
The faucet itself does not implement something like that. I think the best way to achieve this is using HTTP reverse proxies and configure it in threre.

For more app specific logic like faucet usages per address it would be good to have the feature in the faucet. However, this is not trivial to implement because the faucet does not have any storage implemented right now.

**Comment by skosito** [comment]
@webmaster128 thanks for answer. I will be adding this for my needs anyways, so maybe we can coordinate if it would be useful to integrate here as well? I saw couple implementations using simple sql storage to store both ip and address with cooldown, but might be easier and simpler to use redis cache or something like that.

**Comment by webmaster128** [comment]
I think it would be very cool if that was developed and integrated here. Then we can best maintain it and make it accessable for everyone.

It would be good to have a solution that works in a single docker container. So I have a tendency towards sqlite databases, which already handles a lot of parallelization pretty well. Then you only need to start and maintain one process.

**Comment by skosito** [comment]
@webmaster128 thanks, I can do this on my fork and maybe create PR after I have something?

**Comment by webmaster128** [comment]
Sounds good, thank you! Feel free to open a draft PR if you want to get some early feedback.

**Comment by vishrutsingh** [comment]
@webmaster128 you might want to look at [express rate limiter](https://www.npmjs.com/package/express-rate-limit). I used this to limit max drips from an IP and set a time limit of 24 hrs for that IP, pretty useful for limiting public APIs.

**Comment by webmaster128** [comment]
A general purpose HTTP rete limiter can be achieved with any proxy solution. If we want this to matter, we should add app logic in there by at least rate limiting the target address.
