### ISSUE TITLE
Add a utility function to get query responses to Decimal.

### ISSUE THREAD

**Issue by puneet2019** [cosmos/cosmjs#965]
```
import {Tendermint34Client} from "@cosmjs/tendermint-rpc";
import {createProtobufRpcClient, QueryClient} from "@cosmjs/stargate";
import {QueryClientImpl as MintQueryClientImpl} from 'cosmjs-types/cosmos/mint/v1beta1/query';
import { Decimal } from "@cosmjs/math";

       const tendermintClient = await Tendermint34Client.connect("rpc.cosmos....");
       const queryClient = new QueryClient(tendermintClient);
       const rpcClient = createProtobufRpcClient(queryClient);
       const queryService = new MintQueryClientImpl(rpcClient);
       const response = await queryService.Inflation({});
       console.log(response.inflation)
```

Here `response.infaltion` returns a uint8array.

```
        let decoder = new TextDecoder('utf8');
        let decimalString = Decimal.fromAtomics(decoder.decode(response.inflation),18).toString()
```
Is there another way to do this?

**Comment by webmaster128** [comment]
Yeah, the proto encoding of Cosmos SDK decimals (github.com/cosmos/cosmos-sdk/types.Dec) is annoying.

`decoder.decode(response.inflation)` can be replaced with `fromUtf8(response.inflation)`.

I was looking for an example how we do it in CosmJS but it seems like all the queries that return decimals are only implemented for Launchpad, not Stargate. I'd very much appreciate a port of `packages/launchpad/src/lcdapi/mint.ts` to `packages/stargate/src/queries/`.

**Comment by vishrutsingh** [comment]
@webmaster128 I'd like to take up the task. Thanks

**Comment by webmaster128** [comment]
What's really strange is the binary encoding in 

```proto
// QueryInflationResponse is the response type for the Query/Inflation RPC
// method.
message QueryInflationResponse {
  // inflation is the current minting inflation value.
  bytes inflation = 1 [(gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (gogoproto.nullable) = false];
}
```

vs the string encoding in

```proto
// CommissionRates defines the initial commission rates to be used for creating
// a validator.
message CommissionRates {
  option (gogoproto.equal)            = true;
  option (gogoproto.goproto_stringer) = false;

  // rate is the commission rate charged to delegators, as a fraction.
  string rate = 1 [(gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (gogoproto.nullable) = false];
  // max_rate defines the maximum commission rate which validator can ever charge, as a fraction.
  string max_rate = 2 [
    (gogoproto.moretags)   = "yaml:\"max_rate\"",
    (gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec",
    (gogoproto.nullable)   = false
  ];
  // max_change_rate defines the maximum daily increase of the validator commission, as a fraction.
  string max_change_rate = 3 [
    (gogoproto.moretags)   = "yaml:\"max_change_rate\"",
    (gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec",
    (gogoproto.nullable)   = false
  ];
}
```

**Comment by webmaster128** [comment]
Could you have a look at #969 (new `decodeCosmosSdkDecFromProto` function) and see if that serves your needs?

**Comment by webmaster128** [comment]
#969 now conntains a full MintExtension for queries. Here I took the approch to wrap the whole protobuf API in custom types and do the decimal parsing internally. So it should be easy to use. It is somewhat inconsistent to many other query extensions that expose the original proto type. Happy for some 👀 on the PR.

**Comment by puneet2019** [comment]
Will check it out  with @blackpanther1881

**Comment by webmaster128** [comment]
Please also note https://github.com/cosmos/cosmos-sdk/issues/10863 if you care about the future of Decimals in Cosmos SDK.

**Comment by blackpanther1881** [comment]
@webmaster128 both decodeCosmosSdkDecFromProto and MintExtension from #969 working fine. decodeCosmosSdkDecFromProto response.toString() giving required result.
