### ISSUE TITLE
Float numbers are decoded in a strange way

### ISSUE THREAD

**Issue by catrias** [cosmos/cosmjs#968]
Cosmos REST ([https://api.cosmos.network/cosmos/staking/v1beta1/validators](https://api.cosmos.network/cosmos/staking/v1beta1/validators)) returns correct string values. I took staking/validators as an example.
```
"commission_rates": {
  "rate": "0.000000000000000000",
   "max_rate": "0.200000000000000000",
   "max_change_rate": "0.010000000000000000"
},
```

But when I use tendermint RPC

```
import { QueryClient, setupStakingExtension } from '@cosmjs/stargate';
import { Tendermint34Client } from '@cosmjs/tendermint-rpc';

const tendermintClient = await Tendermint34Client.connect('http://rpc.cosmos.network');
const queryClient = QueryClient.withExtensions(
  tendermintClient,
  setupStakingExtension,
);
const validators = await queryClient.staking.validators('BOND_STATUS_BONDED');
console.log(validators);
```

I get
![image](https://user-images.githubusercontent.com/12990544/147768741-08da8a14-f49c-4d80-a192-3406ca231fde.png)

Is it a correct behavior?

**Comment by webmaster128** [comment]
This has been discussed recently in https://github.com/cosmos/cosmjs/issues/965. So yeah, it is expected and correct but very inconvenient. Hope this hint unblocks you.
