### ISSUE TITLE
ERROR claim

### ISSUE THREAD

**Issue by denispro2015** [cosmos/cosmjs#983]
Type URL does not exist in the Amino message type register. If you need support for this message type, you can pass in additional entries to the AminoTypes constructor. If you think this message type should be included by default, please open an issue at https://github.com/cosmos/cosmjs/issues.

**Comment by Chikaboomboom** [comment]
I have the same issue as above.  Error in claiming: https://app.stargaze.zone/airdrop

**Comment by majortom1979** [comment]
Same here :-/

**Comment by Thib01** [comment]
same ;(

**Comment by MrRoFlo** [comment]
Same - I also created the account on Ledger. Idk if that might be a theme here.

**Comment by domashno** [comment]
not cool :/

**Comment by ethanfrey** [comment]
Same as #987 

Confio did not write the app. This is a custom message type and must be supported by the Stargaze team.
@shanev should know who to direct this to
