### ISSUE TITLE
https://github.com/cosmos/cosmjs/issues

### ISSUE THREAD

**Issue by currypaul93** [cosmos/cosmjs#984]
Im having some issues claiming the first 20% of my initial stars airdrop can somebody please help?

**Comment by FoggyWorld** [comment]
Hello me too : Kepler + Ledger Nano X 
Address : stars1akv78wqjzvmyuyvaf93vss4fnh2utsfkr9cf4d
Error Message : 

![image](https://user-images.githubusercontent.com/75080862/149819537-d480a016-05c4-4b8b-ac7e-705261d88253.png)

**Comment by FoggyWorld** [comment]
Same behavior with Chrome and Brave FYI

**Comment by HofZion** [comment]
I'm having the same issue. People are saying that the server is full as to why it is not working. Someone said he was able to claim his and to just continue trying to claim. Not sure how accurate that info is though.

**Comment by Andrey12323** [comment]
Do you have a Ledger? They say that such an error is due to the ledger.

**Comment by polo6411** [comment]
Bonjour, j'ai le même problème. En passant par firefox ça ne change rien ?

**Comment by FoggyWorld** [comment]
Yes indeed Ledger Nano X, but what is strange is that Kepler doesn't seem to be triggered at all

**Comment by Andrey12323** [comment]
I have the same thing, Keplr does not open at all, but many of those who just have Keplr without a ledger calmly and successfully took the tokens. Developers from project to project basically do not notice the users of the ledger. It's horrible.

**Comment by ethanfrey** [comment]
Same as #987 

Confio did not write the app. This is a custom message type and must be supported by the Stargaze team.
@shanev should know who to direct this to
