### ISSUE TITLE
Claim error

### ISSUE THREAD

**Issue by pavvelmistrz** [cosmos/cosmjs#985]
Hi I have folowing error 

Type URL does not exist in the Amino message type register. If you need support for this message type, you can pass in additional entries to the AminoTypes constructor. If you think this message type should be included by default, please open an issue at https://github.com/cosmos/cosmjs/issues.

My address stars1sm0w0356enp4zqg7t3en5p779ljhhd0wj47t9p

Can you help ?

**Comment by Andrey12323** [comment]
Аналогично! Говорят, что это из-за леджера.

**Comment by Andrey12323** [comment]
Developers are stepping on the same rake. From project to project - fundamentally do not notice ledger users! Ugliness!

**Comment by ethanfrey** [comment]
Same as #987 

Confio did not write the app. This is a custom message type and must be supported by the Stargaze team.
@shanev should know who to direct this to
