### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by Andrey12323** [cosmos/cosmjs#986]
Developers are stepping on the same rake. From project to project - fundamentally do not notice ledger users! What is this nonsense?

**Comment by Andrey12323** [comment]
Type URL does not exist in the Amino message type register. If you need support for this message type, you can pass in additional entries to the AminoTypes constructor. If you think this message type should be included by default, please open an issue at https://github.com/cosmos/cosmjs/issues.

**Comment by Andrey12323** [comment]
Is this discrimination against cold wallet users - ledger?!!!!

**Comment by micada79** [comment]
<img width="1270" alt="Zrzut ekranu 2022-01-17 o 19 55 54" src="https://user-images.githubusercontent.com/97912098/149824648-24f3bc3d-9ee7-4be8-9c64-b431a85c99b6.png">
I have the same issue via Ledger.
Hope they will fix this soon. Anyway we are able to claim from mission 2 and 3.

**Comment by Woidwofei** [comment]
wow, it is such a hassle to collect all these airdrops with my ledger. It's never just "claim", always some workaround that you need to do. I hate to pay this price for security.

**Comment by ethanfrey** [comment]
Same as #987 

Confio did not write the app. This is a custom message type and must be supported by the Stargaze team.
@shanev should know who to direct this to
