### ISSUE TITLE
Error For Stargaze airdrop in Mission #1, Claim initial 20%

### ISSUE THREAD

**Issue by emzycoi** [cosmos/cosmjs#987]
Error

Type URL does not exist in the Amino message type register. If you need support for this message type, you can pass in additional entries to the AminoTypes constructor. If you think this message type should be included by default, please open an issue at https://github.com/cosmos/cosmjs/issues.

Is this because I use a ledger?

my address is stars1zdw82cflxz4hanmc55ermc649d5ec6rklzxjf

![Screenshot 2022-01-18 025325](https://user-images.githubusercontent.com/81348398/149824149-3931c543-3763-402b-8a28-9bb1b86dc479.png)

**Comment by akrueger** [comment]
I also get this using Ledger Nano X

**Comment by denispro2015** [comment]
The same problem with ledger

**Comment by PiotrSobiecki** [comment]
Yes , I have the same problem, but other 2 actions I've done :)

**Comment by denispro2015** [comment]
Me too)))

**Comment by Woidwofei** [comment]
Same, ledger Nano S

**Comment by drewangell** [comment]
Same here with Ledger X

**Comment by anishp55** [comment]
same.  i have a ledger and am getting this error

**Comment by ethanfrey** [comment]
Stargaze needs to add amino support for this message in the blockchain and ensure they register the amino mapping for this protobuf message in the cosmjs app.

@shanev may be able to respond on this one

**Comment by stewbz** [comment]
Same here, Also using a Ledger

**Comment by shanev** [comment]
Hey all, the Stargaze team is working on a fix this. We are aware of the issue. It has nothing to do with CosmJS and opening issues in this repo won't help.

**Comment by drewangell** [comment]
@shanev I would suggest that they change the error message so it doesn't tell people to create issues here then.  :)

**Comment by webmaster128** [comment]
The error message is pretty good, but meant for a different audience. But yeah, not ideal this way. We'll figure something out and the Stargaze app is getting fixed in parallel.

**Comment by shanev** [comment]
Stargaze has fixed this issue: https://github.com/public-awesome/stargaze/pull/522, so this can be closed.

**Comment by webmaster128** [comment]
🚀🚀🚀🚀🌟🌠✨🌟🌠✨🌟🌠✨
