### ISSUE TITLE
Stargaze New Error Message

### ISSUE THREAD

**Issue by HofZion** [cosmos/cosmjs#988]
I am trying to claim my stargaze and after the first initial error message, I am now able to connect my ledger with keplr. However, when I approve transaction through my ledger to get the initial 20% Stargaze claim, a new error message shows up. Is it happening to anyone else?
![20220117_163401](https://user-images.githubusercontent.com/97909577/149840072-6b6fb392-aa71-4b14-8052-13c7ba524c70.jpg)

**Comment by StephenMinty** [comment]
I'm having the same issue, but with a different account number and sequence number (1). I'm using a different physical Ledger device than the one I used to set up the wallet, but with the same wallet imported on to it. Not sure if that would make a difference at all?

**Comment by webmaster128** [comment]
The error message is a complicated and confusing way of saying: "signature invalid". There is nothing you can do about it other than waiting for a fix. See also https://github.com/cosmos/cosmjs/issues/987#issuecomment-1014878386

**Comment by HofZion** [comment]
Alright, well we have to wish for the best
