### ISSUE TITLE
Error for Stargaze airdrop mission One initial 20%

### ISSUE THREAD

**Issue by malakayahoga** [cosmos/cosmjs#991]
I use a ledger nano with a Keplr wallet and received this Error when when i try to sign the transaction:

Broadcasting transaction failed with code 
4 (codespace:sdk).  Log: signature
verification failed; please verifyaccount
number (7279), sequence (8) and chain-id
(stargaze-1): unauthorized

**Comment by godula10** [comment]
The same problem I have. Do you have solution ?
