### ISSUE TITLE
Not Compatible with Webpack 5

### ISSUE THREAD

**Issue by aaely** [cosmos/cosmjs#992]
New creat-react-apps are being forced onto webpack v 5.66 and its causing issues with instantiating a new cosmJS signing client. Create-react-app is preventing me from downgrading effectively and this is a major holdup. Im leaving the error message here but its honestly rather worthless.

![image](https://user-images.githubusercontent.com/40217979/149864349-82cba096-45bc-4f60-b383-6babda4b6e8e.png)

**Comment by webmaster128** [comment]
The error message is pretty good and explains well what the problem is and how to solve it.

CosmJS works with webpack 5 but due to dependencies we use, you have to configure webpack. Here is a webpack config that we use which solves the problems above: https://github.com/cosmos/cosmjs/blob/main/packages/stargate/webpack.web.config.js#L25-L38.

Can you create a custom pabpack config in CRA?

**Comment by aaely** [comment]
Adding the polyfills and fixing this breaks polkadot-js. I have them integrated and am using the two on the same platform along with Solana and Eth.

**Comment by webmaster128** [comment]
Which of those configs makes prokadot-js break and how? Maybe we can change them a bit or get rid of some dependencies that make the config necessary.

**Comment by aaely** [comment]
Upon further investigation, it appears to be Web3.js that has the breaking issue. CosmJS and Polkadot-js are compatible; however, react has made this much more difficult to achieve.

**Comment by webmaster128** [comment]
Yeah, requiring this webpack config entries is far from ideal. We already put effort into reducing the dependencies. But the reality is that many of the npm modules used today were written for Node.js long time ago and still assume the Node environment is available.

**Comment by webmaster128** [comment]
With https://github.com/cosmos/cosmjs/pull/966 we seem to get rid of the stream fallback requirement 🎉.

**Comment by webmaster128** [comment]
See also #1061

**Comment by webmaster128** [comment]
https://github.com/cosmos/cosmjs/pull/1088 adds documentation how Webpack 5 needs to be configured to allow using CosmJS smoothly.
