### ISSUE TITLE
Let Registry constructor argument override default types

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmjs#994]
With the addition systen, the constructor argument and the `register` method do the same and there is no way to get rid of `Coin` and `MsgSend`.

**Comment by webmaster128** [comment]
This requires adding `Coin` to `defaultRegistryTypes`.

**Comment by msteiner96** [comment]
Just to be sure: You mean these two methods here?

```ts
  public constructor(customTypes: Iterable<[string, GeneratedType]> = []) {
    const { cosmosCoin, cosmosMsgSend } = defaultTypeUrls;
    this.types = new Map<string, GeneratedType>([
      [cosmosCoin, Coin],
      [cosmosMsgSend, MsgSend],
      ...customTypes,
    ]);
  }


  public register(typeUrl: string, type: GeneratedType): void {
    this.types.set(typeUrl, type);
  }
```

So the result should look like that?
```js
public constructor(customTypes: Iterable<[string, GeneratedType]> = []) {
    this.types = new Map<string, GeneratedType>([
      ...customTypes,
    ]);
  }


  public register(typeUrl: string, type: GeneratedType): void {
    this.types.set(typeUrl, type);
  }
```

**Comment by webmaster128** [comment]
The old types

```
      [cosmosCoin, Coin],
      [cosmosMsgSend, MsgSend],
 ```
 
 could remain in the registry when no constructor argument is set. Then `new Registry()` is non-breaking. For this to happen we need to turn the default `= []` to an optional. Once the constructor argument is set, it overrides the defaults instead of appending.
